export type { PetsoClientConfig } from "./client";
export { PetsoClient, PetsoClientError } from "./client";

export type {
	TAuthCredentials,
	TAuthResult,
	TApiResponse,
	TCreateOrderInput,
	TCreateOrderItemInput,
	TCreateOrderPaymentInput,
	TCustomerDto,
	TCustomerOrderDto,
	TCustomerRecordDto,
	TCreateCustomerInput,
	TUpdateCustomerInput,
	TDashboardMetrics,
	TDashboardSummaryDto,
	TLowStockItem,
	TOrderDto,
	TOrderItemDto,
	TOrderListItemDto,
	TOrderListParams,
	TOrderListResult,
	TOrderPaymentDto,
	TOrderTimelineEntry,
	TPaginated,
	TPaginationInput,
	TProductDto,
	TAdminProductInput,
	TProductListParams,
	TProductListResult,
	TProductSuggestResult,
	TProductVariantDto,
	TPetDto,
	TCreatePetInput,
	TUpdatePetInput,
	TStaffMemberDto,
	TAdjustStockInput,
	TInventoryBatchDto,
	TInventoryMovementDto,
	TInventorySnapshot,
	TSessionDto,
	TSignupInput,
	TSignupResult,
	TUpdateStatusInput,
	TValidateVoucherInput,
	TVoucherDto,
	TVoucherValidationResult,
	TWebhookEndpoint,
	TWebhookEventPayload,
} from "./types";
