export type { PetsoClientConfig } from "./client";
export { PetsoClient, PetsoClientError } from "./client";

export type {
	TApiResponse,
	TCreateOrderInput,
	TCreateOrderItemInput,
	TCreateOrderPaymentInput,
	TCustomerDto,
	TCustomerOrderDto,
	TDashboardMetrics,
	TDashboardSummaryDto,
	TLowStockItem,
	TOrderDto,
	TOrderItemDto,
	TOrderListItemDto,
	TOrderListParams,
	TOrderListResult,
	TOrderPaymentDto,
	TOrderTimelineEntry,
	TPaginated,
	TPaginationInput,
	TProductDto,
	TProductListParams,
	TProductListResult,
	TProductSuggestResult,
	TProductVariantDto,
	TUpdateStatusInput,
	TValidateVoucherInput,
	TVoucherDto,
	TVoucherValidationResult,
	TWebhookEndpoint,
	TWebhookEventPayload,
} from "./types";
