# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - security
  - pinned

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hey! The issue has been automatically marked as stale because it has not had
  recent activity. It will be closed soon if no further activity occurs. Please
  reply here if you wish for the issue to be kept open.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
