// flow-typed signature: d7b43b337317496a8e8de0dda8c841ff
// flow-typed version: <<STUB>>/aws-sdk_v^2.135.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-sdk/browser' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/accessanalyzer' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/acm' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/acmpca' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/alexaforbusiness' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/all' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/amplify' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/apigateway' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/apigatewaymanagementapi' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/apigatewayv2' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/appconfig' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/applicationautoscaling' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/applicationinsights' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/appmesh' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/appstream' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/appsync' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/athena' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/augmentedairuntime' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/autoscaling' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/autoscalingplans' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/backup' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/batch' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/browser_default' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/budgets' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/chime' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloud9' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/clouddirectory' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudformation' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudfront' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudhsm' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudhsmv2' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudsearch' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudsearchdomain' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudtrail' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudwatch' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudwatchevents' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cloudwatchlogs' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codebuild' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codecommit' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codedeploy' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codeguruprofiler' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codegurureviewer' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codepipeline' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codestar' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codestarconnections' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/codestarnotifications' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cognitoidentity' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cognitoidentityserviceprovider' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cognitosync' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/comprehend' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/comprehendmedical' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/computeoptimizer' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/configservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/connect' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/connectparticipant' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/costexplorer' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/cur' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/dataexchange' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/datapipeline' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/datasync' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/dax' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/detective' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/devicefarm' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/directconnect' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/directoryservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/discovery' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/dlm' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/dms' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/docdb' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/dynamodb' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/dynamodbstreams' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ebs' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ec2' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ec2instanceconnect' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ecr' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ecs' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/efs' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/eks' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/elasticache' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/elasticbeanstalk' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/elasticinference' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/elastictranscoder' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/elb' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/elbv2' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/emr' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/es' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/eventbridge' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/firehose' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/fms' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/forecastqueryservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/forecastservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/frauddetector' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/fsx' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/gamelift' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/glacier' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/globalaccelerator' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/glue' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/greengrass' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/groundstation' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/guardduty' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/health' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iam' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/imagebuilder' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/importexport' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/inspector' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iot' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iot1clickdevicesservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iot1clickprojects' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iotanalytics' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iotdata' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iotevents' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ioteventsdata' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iotjobsdataplane' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iotsecuretunneling' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/iotthingsgraph' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kafka' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kendra' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kinesis' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kinesisanalytics' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kinesisanalyticsv2' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kinesisvideo' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kinesisvideoarchivedmedia' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kinesisvideomedia' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kinesisvideosignalingchannels' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/kms' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/lakeformation' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/lambda' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/lexmodelbuildingservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/lexruntime' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/licensemanager' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/lightsail' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/machinelearning' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/macie' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/managedblockchain' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/marketplacecatalog' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/marketplacecommerceanalytics' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/marketplaceentitlementservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/marketplacemetering' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mediaconnect' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mediaconvert' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/medialive' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mediapackage' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mediapackagevod' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mediastore' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mediastoredata' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mediatailor' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/migrationhub' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/migrationhubconfig' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mobile' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mobileanalytics' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mq' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/mturk' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/neptune' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/networkmanager' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/opsworks' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/opsworkscm' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/organizations' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/outposts' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/personalize' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/personalizeevents' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/personalizeruntime' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/pi' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/pinpoint' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/pinpointemail' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/pinpointsmsvoice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/polly' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/pricing' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/qldb' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/qldbsession' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/quicksight' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ram' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/rds' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/rdsdataservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/redshift' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/rekognition' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/resourcegroups' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/resourcegroupstaggingapi' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/robomaker' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/route53' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/route53domains' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/route53resolver' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/s3' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/s3control' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/sagemaker' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/sagemakerruntime' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/savingsplans' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/schemas' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/secretsmanager' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/securityhub' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/serverlessapplicationrepository' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/servicecatalog' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/servicediscovery' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/servicequotas' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ses' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/sesv2' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/shield' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/signer' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/simpledb' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/sms' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/snowball' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/sns' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/sqs' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ssm' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/sso' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/ssooidc' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/stepfunctions' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/storagegateway' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/sts' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/support' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/swf' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/textract' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/transcribeservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/transfer' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/translate' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/waf' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/wafregional' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/wafv2' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/workdocs' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/worklink' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/workmail' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/workmailmessageflow' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/workspaces' {
  declare module.exports: any;
}

declare module 'aws-sdk/clients/xray' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/browser-builder' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/client-creator' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/create-all-services' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/service-collector' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/transform' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/webpack.config.rn-core' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/webpack.config.rn-dep' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist-tools/webpack.config.rn' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist/aws-sdk-core-react-native' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist/aws-sdk-react-native' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist/aws-sdk' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist/aws-sdk.min' {
  declare module.exports: any;
}

declare module 'aws-sdk/dist/xml2js' {
  declare module.exports: any;
}

declare module 'aws-sdk/global' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/api_loader' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/aws' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browser_loader' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browser' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browserCryptoLib' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browserHashUtils' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browserHmac' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browserMd5' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browserSha1' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/browserSha256' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/cloudfront/signer' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/config_regional_endpoint' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/config' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/core' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/chainable_temporary_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/cognito_identity_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/credential_provider_chain' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/ec2_metadata_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/ecs_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/environment_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/file_system_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/process_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/remote_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/saml_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/shared_ini_file_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/temporary_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/token_file_web_identity_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/credentials/web_identity_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/discover_endpoint' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/dynamodb/converter' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/dynamodb/document_client' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/dynamodb/numberValue' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/dynamodb/set' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/dynamodb/translator' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/dynamodb/types' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/empty' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event_listeners' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/buffered-create-event-stream' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/build-message' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/event-message-chunker-stream' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/event-message-chunker' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/event-message-unmarshaller-stream' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/int64' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/parse-event' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/parse-message' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/split-message' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/event-stream/streaming-create-event-stream' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/http' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/http/node' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/http/xhr' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/json/builder' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/json/parser' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/metadata_service' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/api' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/collection' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/operation' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/paginator' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/resource_waiter' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/model/shape' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/node_loader' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/param_validator' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/polly/presigner' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/helpers' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/json' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/query' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/rest_json' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/rest_xml' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/protocol/rest' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/publisher/configuration' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/publisher' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/query/query_param_serializer' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/rds/signer' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/react-native-loader' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/react-native/add-content-type' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/realclock/browserClock' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/realclock/nodeClock' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/region_config' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/request' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/resource_waiter' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/response' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/s3/managed_upload' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/sequential_executor' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/service' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/apigateway' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/cloudfront' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/cloudsearchdomain' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/cognitoidentity' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/dynamodb' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/ec2' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/glacier' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/iotdata' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/lambda' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/machinelearning' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/polly' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/rds' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/rdsdataservice' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/route53' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/s3' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/s3control' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/sqs' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/sts' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/services/swf' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/shared-ini' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/shared-ini/ini-loader' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/presign' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/request_signer' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/s3' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v2' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v3' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v3https' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v4_credentials' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/signers/v4' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/state_machine' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/util' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/browser_parser' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/builder' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/escape-attribute' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/escape-element' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/node_parser' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/xml-node' {
  declare module.exports: any;
}

declare module 'aws-sdk/lib/xml/xml-text' {
  declare module.exports: any;
}

declare module 'aws-sdk/react-native' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/changelog/add-change' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/changelog/change-creator' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/changelog/util' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/composite-test' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/lib/get-operation-shape-names' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/lib/prune-shapes' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/lib/remove-event-stream-ops' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/lib/test-helper' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/lib/translator' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/lib/ts-generator' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/lib/visit-related-shape-names' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/region-checker' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/region-checker/whitelist' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/services-table-generator' {
  declare module.exports: any;
}

declare module 'aws-sdk/scripts/typings-generator' {
  declare module.exports: any;
}

declare module 'aws-sdk/vendor/endpoint-cache' {
  declare module.exports: any;
}

declare module 'aws-sdk/vendor/endpoint-cache/utils/LRU' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-sdk/browser.js' {
  declare module.exports: $Exports<'aws-sdk/browser'>;
}
declare module 'aws-sdk/clients/accessanalyzer.js' {
  declare module.exports: $Exports<'aws-sdk/clients/accessanalyzer'>;
}
declare module 'aws-sdk/clients/acm.js' {
  declare module.exports: $Exports<'aws-sdk/clients/acm'>;
}
declare module 'aws-sdk/clients/acmpca.js' {
  declare module.exports: $Exports<'aws-sdk/clients/acmpca'>;
}
declare module 'aws-sdk/clients/alexaforbusiness.js' {
  declare module.exports: $Exports<'aws-sdk/clients/alexaforbusiness'>;
}
declare module 'aws-sdk/clients/all.js' {
  declare module.exports: $Exports<'aws-sdk/clients/all'>;
}
declare module 'aws-sdk/clients/amplify.js' {
  declare module.exports: $Exports<'aws-sdk/clients/amplify'>;
}
declare module 'aws-sdk/clients/apigateway.js' {
  declare module.exports: $Exports<'aws-sdk/clients/apigateway'>;
}
declare module 'aws-sdk/clients/apigatewaymanagementapi.js' {
  declare module.exports: $Exports<'aws-sdk/clients/apigatewaymanagementapi'>;
}
declare module 'aws-sdk/clients/apigatewayv2.js' {
  declare module.exports: $Exports<'aws-sdk/clients/apigatewayv2'>;
}
declare module 'aws-sdk/clients/appconfig.js' {
  declare module.exports: $Exports<'aws-sdk/clients/appconfig'>;
}
declare module 'aws-sdk/clients/applicationautoscaling.js' {
  declare module.exports: $Exports<'aws-sdk/clients/applicationautoscaling'>;
}
declare module 'aws-sdk/clients/applicationinsights.js' {
  declare module.exports: $Exports<'aws-sdk/clients/applicationinsights'>;
}
declare module 'aws-sdk/clients/appmesh.js' {
  declare module.exports: $Exports<'aws-sdk/clients/appmesh'>;
}
declare module 'aws-sdk/clients/appstream.js' {
  declare module.exports: $Exports<'aws-sdk/clients/appstream'>;
}
declare module 'aws-sdk/clients/appsync.js' {
  declare module.exports: $Exports<'aws-sdk/clients/appsync'>;
}
declare module 'aws-sdk/clients/athena.js' {
  declare module.exports: $Exports<'aws-sdk/clients/athena'>;
}
declare module 'aws-sdk/clients/augmentedairuntime.js' {
  declare module.exports: $Exports<'aws-sdk/clients/augmentedairuntime'>;
}
declare module 'aws-sdk/clients/autoscaling.js' {
  declare module.exports: $Exports<'aws-sdk/clients/autoscaling'>;
}
declare module 'aws-sdk/clients/autoscalingplans.js' {
  declare module.exports: $Exports<'aws-sdk/clients/autoscalingplans'>;
}
declare module 'aws-sdk/clients/backup.js' {
  declare module.exports: $Exports<'aws-sdk/clients/backup'>;
}
declare module 'aws-sdk/clients/batch.js' {
  declare module.exports: $Exports<'aws-sdk/clients/batch'>;
}
declare module 'aws-sdk/clients/browser_default.js' {
  declare module.exports: $Exports<'aws-sdk/clients/browser_default'>;
}
declare module 'aws-sdk/clients/budgets.js' {
  declare module.exports: $Exports<'aws-sdk/clients/budgets'>;
}
declare module 'aws-sdk/clients/chime.js' {
  declare module.exports: $Exports<'aws-sdk/clients/chime'>;
}
declare module 'aws-sdk/clients/cloud9.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloud9'>;
}
declare module 'aws-sdk/clients/clouddirectory.js' {
  declare module.exports: $Exports<'aws-sdk/clients/clouddirectory'>;
}
declare module 'aws-sdk/clients/cloudformation.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudformation'>;
}
declare module 'aws-sdk/clients/cloudfront.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudfront'>;
}
declare module 'aws-sdk/clients/cloudhsm.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudhsm'>;
}
declare module 'aws-sdk/clients/cloudhsmv2.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudhsmv2'>;
}
declare module 'aws-sdk/clients/cloudsearch.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudsearch'>;
}
declare module 'aws-sdk/clients/cloudsearchdomain.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudsearchdomain'>;
}
declare module 'aws-sdk/clients/cloudtrail.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudtrail'>;
}
declare module 'aws-sdk/clients/cloudwatch.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudwatch'>;
}
declare module 'aws-sdk/clients/cloudwatchevents.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudwatchevents'>;
}
declare module 'aws-sdk/clients/cloudwatchlogs.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cloudwatchlogs'>;
}
declare module 'aws-sdk/clients/codebuild.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codebuild'>;
}
declare module 'aws-sdk/clients/codecommit.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codecommit'>;
}
declare module 'aws-sdk/clients/codedeploy.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codedeploy'>;
}
declare module 'aws-sdk/clients/codeguruprofiler.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codeguruprofiler'>;
}
declare module 'aws-sdk/clients/codegurureviewer.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codegurureviewer'>;
}
declare module 'aws-sdk/clients/codepipeline.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codepipeline'>;
}
declare module 'aws-sdk/clients/codestar.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codestar'>;
}
declare module 'aws-sdk/clients/codestarconnections.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codestarconnections'>;
}
declare module 'aws-sdk/clients/codestarnotifications.js' {
  declare module.exports: $Exports<'aws-sdk/clients/codestarnotifications'>;
}
declare module 'aws-sdk/clients/cognitoidentity.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cognitoidentity'>;
}
declare module 'aws-sdk/clients/cognitoidentityserviceprovider.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cognitoidentityserviceprovider'>;
}
declare module 'aws-sdk/clients/cognitosync.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cognitosync'>;
}
declare module 'aws-sdk/clients/comprehend.js' {
  declare module.exports: $Exports<'aws-sdk/clients/comprehend'>;
}
declare module 'aws-sdk/clients/comprehendmedical.js' {
  declare module.exports: $Exports<'aws-sdk/clients/comprehendmedical'>;
}
declare module 'aws-sdk/clients/computeoptimizer.js' {
  declare module.exports: $Exports<'aws-sdk/clients/computeoptimizer'>;
}
declare module 'aws-sdk/clients/configservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/configservice'>;
}
declare module 'aws-sdk/clients/connect.js' {
  declare module.exports: $Exports<'aws-sdk/clients/connect'>;
}
declare module 'aws-sdk/clients/connectparticipant.js' {
  declare module.exports: $Exports<'aws-sdk/clients/connectparticipant'>;
}
declare module 'aws-sdk/clients/costexplorer.js' {
  declare module.exports: $Exports<'aws-sdk/clients/costexplorer'>;
}
declare module 'aws-sdk/clients/cur.js' {
  declare module.exports: $Exports<'aws-sdk/clients/cur'>;
}
declare module 'aws-sdk/clients/dataexchange.js' {
  declare module.exports: $Exports<'aws-sdk/clients/dataexchange'>;
}
declare module 'aws-sdk/clients/datapipeline.js' {
  declare module.exports: $Exports<'aws-sdk/clients/datapipeline'>;
}
declare module 'aws-sdk/clients/datasync.js' {
  declare module.exports: $Exports<'aws-sdk/clients/datasync'>;
}
declare module 'aws-sdk/clients/dax.js' {
  declare module.exports: $Exports<'aws-sdk/clients/dax'>;
}
declare module 'aws-sdk/clients/detective.js' {
  declare module.exports: $Exports<'aws-sdk/clients/detective'>;
}
declare module 'aws-sdk/clients/devicefarm.js' {
  declare module.exports: $Exports<'aws-sdk/clients/devicefarm'>;
}
declare module 'aws-sdk/clients/directconnect.js' {
  declare module.exports: $Exports<'aws-sdk/clients/directconnect'>;
}
declare module 'aws-sdk/clients/directoryservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/directoryservice'>;
}
declare module 'aws-sdk/clients/discovery.js' {
  declare module.exports: $Exports<'aws-sdk/clients/discovery'>;
}
declare module 'aws-sdk/clients/dlm.js' {
  declare module.exports: $Exports<'aws-sdk/clients/dlm'>;
}
declare module 'aws-sdk/clients/dms.js' {
  declare module.exports: $Exports<'aws-sdk/clients/dms'>;
}
declare module 'aws-sdk/clients/docdb.js' {
  declare module.exports: $Exports<'aws-sdk/clients/docdb'>;
}
declare module 'aws-sdk/clients/dynamodb.js' {
  declare module.exports: $Exports<'aws-sdk/clients/dynamodb'>;
}
declare module 'aws-sdk/clients/dynamodbstreams.js' {
  declare module.exports: $Exports<'aws-sdk/clients/dynamodbstreams'>;
}
declare module 'aws-sdk/clients/ebs.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ebs'>;
}
declare module 'aws-sdk/clients/ec2.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ec2'>;
}
declare module 'aws-sdk/clients/ec2instanceconnect.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ec2instanceconnect'>;
}
declare module 'aws-sdk/clients/ecr.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ecr'>;
}
declare module 'aws-sdk/clients/ecs.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ecs'>;
}
declare module 'aws-sdk/clients/efs.js' {
  declare module.exports: $Exports<'aws-sdk/clients/efs'>;
}
declare module 'aws-sdk/clients/eks.js' {
  declare module.exports: $Exports<'aws-sdk/clients/eks'>;
}
declare module 'aws-sdk/clients/elasticache.js' {
  declare module.exports: $Exports<'aws-sdk/clients/elasticache'>;
}
declare module 'aws-sdk/clients/elasticbeanstalk.js' {
  declare module.exports: $Exports<'aws-sdk/clients/elasticbeanstalk'>;
}
declare module 'aws-sdk/clients/elasticinference.js' {
  declare module.exports: $Exports<'aws-sdk/clients/elasticinference'>;
}
declare module 'aws-sdk/clients/elastictranscoder.js' {
  declare module.exports: $Exports<'aws-sdk/clients/elastictranscoder'>;
}
declare module 'aws-sdk/clients/elb.js' {
  declare module.exports: $Exports<'aws-sdk/clients/elb'>;
}
declare module 'aws-sdk/clients/elbv2.js' {
  declare module.exports: $Exports<'aws-sdk/clients/elbv2'>;
}
declare module 'aws-sdk/clients/emr.js' {
  declare module.exports: $Exports<'aws-sdk/clients/emr'>;
}
declare module 'aws-sdk/clients/es.js' {
  declare module.exports: $Exports<'aws-sdk/clients/es'>;
}
declare module 'aws-sdk/clients/eventbridge.js' {
  declare module.exports: $Exports<'aws-sdk/clients/eventbridge'>;
}
declare module 'aws-sdk/clients/firehose.js' {
  declare module.exports: $Exports<'aws-sdk/clients/firehose'>;
}
declare module 'aws-sdk/clients/fms.js' {
  declare module.exports: $Exports<'aws-sdk/clients/fms'>;
}
declare module 'aws-sdk/clients/forecastqueryservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/forecastqueryservice'>;
}
declare module 'aws-sdk/clients/forecastservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/forecastservice'>;
}
declare module 'aws-sdk/clients/frauddetector.js' {
  declare module.exports: $Exports<'aws-sdk/clients/frauddetector'>;
}
declare module 'aws-sdk/clients/fsx.js' {
  declare module.exports: $Exports<'aws-sdk/clients/fsx'>;
}
declare module 'aws-sdk/clients/gamelift.js' {
  declare module.exports: $Exports<'aws-sdk/clients/gamelift'>;
}
declare module 'aws-sdk/clients/glacier.js' {
  declare module.exports: $Exports<'aws-sdk/clients/glacier'>;
}
declare module 'aws-sdk/clients/globalaccelerator.js' {
  declare module.exports: $Exports<'aws-sdk/clients/globalaccelerator'>;
}
declare module 'aws-sdk/clients/glue.js' {
  declare module.exports: $Exports<'aws-sdk/clients/glue'>;
}
declare module 'aws-sdk/clients/greengrass.js' {
  declare module.exports: $Exports<'aws-sdk/clients/greengrass'>;
}
declare module 'aws-sdk/clients/groundstation.js' {
  declare module.exports: $Exports<'aws-sdk/clients/groundstation'>;
}
declare module 'aws-sdk/clients/guardduty.js' {
  declare module.exports: $Exports<'aws-sdk/clients/guardduty'>;
}
declare module 'aws-sdk/clients/health.js' {
  declare module.exports: $Exports<'aws-sdk/clients/health'>;
}
declare module 'aws-sdk/clients/iam.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iam'>;
}
declare module 'aws-sdk/clients/imagebuilder.js' {
  declare module.exports: $Exports<'aws-sdk/clients/imagebuilder'>;
}
declare module 'aws-sdk/clients/importexport.js' {
  declare module.exports: $Exports<'aws-sdk/clients/importexport'>;
}
declare module 'aws-sdk/clients/inspector.js' {
  declare module.exports: $Exports<'aws-sdk/clients/inspector'>;
}
declare module 'aws-sdk/clients/iot.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iot'>;
}
declare module 'aws-sdk/clients/iot1clickdevicesservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iot1clickdevicesservice'>;
}
declare module 'aws-sdk/clients/iot1clickprojects.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iot1clickprojects'>;
}
declare module 'aws-sdk/clients/iotanalytics.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iotanalytics'>;
}
declare module 'aws-sdk/clients/iotdata.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iotdata'>;
}
declare module 'aws-sdk/clients/iotevents.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iotevents'>;
}
declare module 'aws-sdk/clients/ioteventsdata.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ioteventsdata'>;
}
declare module 'aws-sdk/clients/iotjobsdataplane.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iotjobsdataplane'>;
}
declare module 'aws-sdk/clients/iotsecuretunneling.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iotsecuretunneling'>;
}
declare module 'aws-sdk/clients/iotthingsgraph.js' {
  declare module.exports: $Exports<'aws-sdk/clients/iotthingsgraph'>;
}
declare module 'aws-sdk/clients/kafka.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kafka'>;
}
declare module 'aws-sdk/clients/kendra.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kendra'>;
}
declare module 'aws-sdk/clients/kinesis.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kinesis'>;
}
declare module 'aws-sdk/clients/kinesisanalytics.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kinesisanalytics'>;
}
declare module 'aws-sdk/clients/kinesisanalyticsv2.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kinesisanalyticsv2'>;
}
declare module 'aws-sdk/clients/kinesisvideo.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kinesisvideo'>;
}
declare module 'aws-sdk/clients/kinesisvideoarchivedmedia.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kinesisvideoarchivedmedia'>;
}
declare module 'aws-sdk/clients/kinesisvideomedia.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kinesisvideomedia'>;
}
declare module 'aws-sdk/clients/kinesisvideosignalingchannels.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kinesisvideosignalingchannels'>;
}
declare module 'aws-sdk/clients/kms.js' {
  declare module.exports: $Exports<'aws-sdk/clients/kms'>;
}
declare module 'aws-sdk/clients/lakeformation.js' {
  declare module.exports: $Exports<'aws-sdk/clients/lakeformation'>;
}
declare module 'aws-sdk/clients/lambda.js' {
  declare module.exports: $Exports<'aws-sdk/clients/lambda'>;
}
declare module 'aws-sdk/clients/lexmodelbuildingservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/lexmodelbuildingservice'>;
}
declare module 'aws-sdk/clients/lexruntime.js' {
  declare module.exports: $Exports<'aws-sdk/clients/lexruntime'>;
}
declare module 'aws-sdk/clients/licensemanager.js' {
  declare module.exports: $Exports<'aws-sdk/clients/licensemanager'>;
}
declare module 'aws-sdk/clients/lightsail.js' {
  declare module.exports: $Exports<'aws-sdk/clients/lightsail'>;
}
declare module 'aws-sdk/clients/machinelearning.js' {
  declare module.exports: $Exports<'aws-sdk/clients/machinelearning'>;
}
declare module 'aws-sdk/clients/macie.js' {
  declare module.exports: $Exports<'aws-sdk/clients/macie'>;
}
declare module 'aws-sdk/clients/managedblockchain.js' {
  declare module.exports: $Exports<'aws-sdk/clients/managedblockchain'>;
}
declare module 'aws-sdk/clients/marketplacecatalog.js' {
  declare module.exports: $Exports<'aws-sdk/clients/marketplacecatalog'>;
}
declare module 'aws-sdk/clients/marketplacecommerceanalytics.js' {
  declare module.exports: $Exports<'aws-sdk/clients/marketplacecommerceanalytics'>;
}
declare module 'aws-sdk/clients/marketplaceentitlementservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/marketplaceentitlementservice'>;
}
declare module 'aws-sdk/clients/marketplacemetering.js' {
  declare module.exports: $Exports<'aws-sdk/clients/marketplacemetering'>;
}
declare module 'aws-sdk/clients/mediaconnect.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mediaconnect'>;
}
declare module 'aws-sdk/clients/mediaconvert.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mediaconvert'>;
}
declare module 'aws-sdk/clients/medialive.js' {
  declare module.exports: $Exports<'aws-sdk/clients/medialive'>;
}
declare module 'aws-sdk/clients/mediapackage.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mediapackage'>;
}
declare module 'aws-sdk/clients/mediapackagevod.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mediapackagevod'>;
}
declare module 'aws-sdk/clients/mediastore.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mediastore'>;
}
declare module 'aws-sdk/clients/mediastoredata.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mediastoredata'>;
}
declare module 'aws-sdk/clients/mediatailor.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mediatailor'>;
}
declare module 'aws-sdk/clients/migrationhub.js' {
  declare module.exports: $Exports<'aws-sdk/clients/migrationhub'>;
}
declare module 'aws-sdk/clients/migrationhubconfig.js' {
  declare module.exports: $Exports<'aws-sdk/clients/migrationhubconfig'>;
}
declare module 'aws-sdk/clients/mobile.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mobile'>;
}
declare module 'aws-sdk/clients/mobileanalytics.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mobileanalytics'>;
}
declare module 'aws-sdk/clients/mq.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mq'>;
}
declare module 'aws-sdk/clients/mturk.js' {
  declare module.exports: $Exports<'aws-sdk/clients/mturk'>;
}
declare module 'aws-sdk/clients/neptune.js' {
  declare module.exports: $Exports<'aws-sdk/clients/neptune'>;
}
declare module 'aws-sdk/clients/networkmanager.js' {
  declare module.exports: $Exports<'aws-sdk/clients/networkmanager'>;
}
declare module 'aws-sdk/clients/opsworks.js' {
  declare module.exports: $Exports<'aws-sdk/clients/opsworks'>;
}
declare module 'aws-sdk/clients/opsworkscm.js' {
  declare module.exports: $Exports<'aws-sdk/clients/opsworkscm'>;
}
declare module 'aws-sdk/clients/organizations.js' {
  declare module.exports: $Exports<'aws-sdk/clients/organizations'>;
}
declare module 'aws-sdk/clients/outposts.js' {
  declare module.exports: $Exports<'aws-sdk/clients/outposts'>;
}
declare module 'aws-sdk/clients/personalize.js' {
  declare module.exports: $Exports<'aws-sdk/clients/personalize'>;
}
declare module 'aws-sdk/clients/personalizeevents.js' {
  declare module.exports: $Exports<'aws-sdk/clients/personalizeevents'>;
}
declare module 'aws-sdk/clients/personalizeruntime.js' {
  declare module.exports: $Exports<'aws-sdk/clients/personalizeruntime'>;
}
declare module 'aws-sdk/clients/pi.js' {
  declare module.exports: $Exports<'aws-sdk/clients/pi'>;
}
declare module 'aws-sdk/clients/pinpoint.js' {
  declare module.exports: $Exports<'aws-sdk/clients/pinpoint'>;
}
declare module 'aws-sdk/clients/pinpointemail.js' {
  declare module.exports: $Exports<'aws-sdk/clients/pinpointemail'>;
}
declare module 'aws-sdk/clients/pinpointsmsvoice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/pinpointsmsvoice'>;
}
declare module 'aws-sdk/clients/polly.js' {
  declare module.exports: $Exports<'aws-sdk/clients/polly'>;
}
declare module 'aws-sdk/clients/pricing.js' {
  declare module.exports: $Exports<'aws-sdk/clients/pricing'>;
}
declare module 'aws-sdk/clients/qldb.js' {
  declare module.exports: $Exports<'aws-sdk/clients/qldb'>;
}
declare module 'aws-sdk/clients/qldbsession.js' {
  declare module.exports: $Exports<'aws-sdk/clients/qldbsession'>;
}
declare module 'aws-sdk/clients/quicksight.js' {
  declare module.exports: $Exports<'aws-sdk/clients/quicksight'>;
}
declare module 'aws-sdk/clients/ram.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ram'>;
}
declare module 'aws-sdk/clients/rds.js' {
  declare module.exports: $Exports<'aws-sdk/clients/rds'>;
}
declare module 'aws-sdk/clients/rdsdataservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/rdsdataservice'>;
}
declare module 'aws-sdk/clients/redshift.js' {
  declare module.exports: $Exports<'aws-sdk/clients/redshift'>;
}
declare module 'aws-sdk/clients/rekognition.js' {
  declare module.exports: $Exports<'aws-sdk/clients/rekognition'>;
}
declare module 'aws-sdk/clients/resourcegroups.js' {
  declare module.exports: $Exports<'aws-sdk/clients/resourcegroups'>;
}
declare module 'aws-sdk/clients/resourcegroupstaggingapi.js' {
  declare module.exports: $Exports<'aws-sdk/clients/resourcegroupstaggingapi'>;
}
declare module 'aws-sdk/clients/robomaker.js' {
  declare module.exports: $Exports<'aws-sdk/clients/robomaker'>;
}
declare module 'aws-sdk/clients/route53.js' {
  declare module.exports: $Exports<'aws-sdk/clients/route53'>;
}
declare module 'aws-sdk/clients/route53domains.js' {
  declare module.exports: $Exports<'aws-sdk/clients/route53domains'>;
}
declare module 'aws-sdk/clients/route53resolver.js' {
  declare module.exports: $Exports<'aws-sdk/clients/route53resolver'>;
}
declare module 'aws-sdk/clients/s3.js' {
  declare module.exports: $Exports<'aws-sdk/clients/s3'>;
}
declare module 'aws-sdk/clients/s3control.js' {
  declare module.exports: $Exports<'aws-sdk/clients/s3control'>;
}
declare module 'aws-sdk/clients/sagemaker.js' {
  declare module.exports: $Exports<'aws-sdk/clients/sagemaker'>;
}
declare module 'aws-sdk/clients/sagemakerruntime.js' {
  declare module.exports: $Exports<'aws-sdk/clients/sagemakerruntime'>;
}
declare module 'aws-sdk/clients/savingsplans.js' {
  declare module.exports: $Exports<'aws-sdk/clients/savingsplans'>;
}
declare module 'aws-sdk/clients/schemas.js' {
  declare module.exports: $Exports<'aws-sdk/clients/schemas'>;
}
declare module 'aws-sdk/clients/secretsmanager.js' {
  declare module.exports: $Exports<'aws-sdk/clients/secretsmanager'>;
}
declare module 'aws-sdk/clients/securityhub.js' {
  declare module.exports: $Exports<'aws-sdk/clients/securityhub'>;
}
declare module 'aws-sdk/clients/serverlessapplicationrepository.js' {
  declare module.exports: $Exports<'aws-sdk/clients/serverlessapplicationrepository'>;
}
declare module 'aws-sdk/clients/servicecatalog.js' {
  declare module.exports: $Exports<'aws-sdk/clients/servicecatalog'>;
}
declare module 'aws-sdk/clients/servicediscovery.js' {
  declare module.exports: $Exports<'aws-sdk/clients/servicediscovery'>;
}
declare module 'aws-sdk/clients/servicequotas.js' {
  declare module.exports: $Exports<'aws-sdk/clients/servicequotas'>;
}
declare module 'aws-sdk/clients/ses.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ses'>;
}
declare module 'aws-sdk/clients/sesv2.js' {
  declare module.exports: $Exports<'aws-sdk/clients/sesv2'>;
}
declare module 'aws-sdk/clients/shield.js' {
  declare module.exports: $Exports<'aws-sdk/clients/shield'>;
}
declare module 'aws-sdk/clients/signer.js' {
  declare module.exports: $Exports<'aws-sdk/clients/signer'>;
}
declare module 'aws-sdk/clients/simpledb.js' {
  declare module.exports: $Exports<'aws-sdk/clients/simpledb'>;
}
declare module 'aws-sdk/clients/sms.js' {
  declare module.exports: $Exports<'aws-sdk/clients/sms'>;
}
declare module 'aws-sdk/clients/snowball.js' {
  declare module.exports: $Exports<'aws-sdk/clients/snowball'>;
}
declare module 'aws-sdk/clients/sns.js' {
  declare module.exports: $Exports<'aws-sdk/clients/sns'>;
}
declare module 'aws-sdk/clients/sqs.js' {
  declare module.exports: $Exports<'aws-sdk/clients/sqs'>;
}
declare module 'aws-sdk/clients/ssm.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ssm'>;
}
declare module 'aws-sdk/clients/sso.js' {
  declare module.exports: $Exports<'aws-sdk/clients/sso'>;
}
declare module 'aws-sdk/clients/ssooidc.js' {
  declare module.exports: $Exports<'aws-sdk/clients/ssooidc'>;
}
declare module 'aws-sdk/clients/stepfunctions.js' {
  declare module.exports: $Exports<'aws-sdk/clients/stepfunctions'>;
}
declare module 'aws-sdk/clients/storagegateway.js' {
  declare module.exports: $Exports<'aws-sdk/clients/storagegateway'>;
}
declare module 'aws-sdk/clients/sts.js' {
  declare module.exports: $Exports<'aws-sdk/clients/sts'>;
}
declare module 'aws-sdk/clients/support.js' {
  declare module.exports: $Exports<'aws-sdk/clients/support'>;
}
declare module 'aws-sdk/clients/swf.js' {
  declare module.exports: $Exports<'aws-sdk/clients/swf'>;
}
declare module 'aws-sdk/clients/textract.js' {
  declare module.exports: $Exports<'aws-sdk/clients/textract'>;
}
declare module 'aws-sdk/clients/transcribeservice.js' {
  declare module.exports: $Exports<'aws-sdk/clients/transcribeservice'>;
}
declare module 'aws-sdk/clients/transfer.js' {
  declare module.exports: $Exports<'aws-sdk/clients/transfer'>;
}
declare module 'aws-sdk/clients/translate.js' {
  declare module.exports: $Exports<'aws-sdk/clients/translate'>;
}
declare module 'aws-sdk/clients/waf.js' {
  declare module.exports: $Exports<'aws-sdk/clients/waf'>;
}
declare module 'aws-sdk/clients/wafregional.js' {
  declare module.exports: $Exports<'aws-sdk/clients/wafregional'>;
}
declare module 'aws-sdk/clients/wafv2.js' {
  declare module.exports: $Exports<'aws-sdk/clients/wafv2'>;
}
declare module 'aws-sdk/clients/workdocs.js' {
  declare module.exports: $Exports<'aws-sdk/clients/workdocs'>;
}
declare module 'aws-sdk/clients/worklink.js' {
  declare module.exports: $Exports<'aws-sdk/clients/worklink'>;
}
declare module 'aws-sdk/clients/workmail.js' {
  declare module.exports: $Exports<'aws-sdk/clients/workmail'>;
}
declare module 'aws-sdk/clients/workmailmessageflow.js' {
  declare module.exports: $Exports<'aws-sdk/clients/workmailmessageflow'>;
}
declare module 'aws-sdk/clients/workspaces.js' {
  declare module.exports: $Exports<'aws-sdk/clients/workspaces'>;
}
declare module 'aws-sdk/clients/xray.js' {
  declare module.exports: $Exports<'aws-sdk/clients/xray'>;
}
declare module 'aws-sdk/dist-tools/browser-builder.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/browser-builder'>;
}
declare module 'aws-sdk/dist-tools/client-creator.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/client-creator'>;
}
declare module 'aws-sdk/dist-tools/create-all-services.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/create-all-services'>;
}
declare module 'aws-sdk/dist-tools/service-collector.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/service-collector'>;
}
declare module 'aws-sdk/dist-tools/transform.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/transform'>;
}
declare module 'aws-sdk/dist-tools/webpack.config.rn-core.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/webpack.config.rn-core'>;
}
declare module 'aws-sdk/dist-tools/webpack.config.rn-dep.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/webpack.config.rn-dep'>;
}
declare module 'aws-sdk/dist-tools/webpack.config.rn.js' {
  declare module.exports: $Exports<'aws-sdk/dist-tools/webpack.config.rn'>;
}
declare module 'aws-sdk/dist/aws-sdk-core-react-native.js' {
  declare module.exports: $Exports<'aws-sdk/dist/aws-sdk-core-react-native'>;
}
declare module 'aws-sdk/dist/aws-sdk-react-native.js' {
  declare module.exports: $Exports<'aws-sdk/dist/aws-sdk-react-native'>;
}
declare module 'aws-sdk/dist/aws-sdk.js' {
  declare module.exports: $Exports<'aws-sdk/dist/aws-sdk'>;
}
declare module 'aws-sdk/dist/aws-sdk.min.js' {
  declare module.exports: $Exports<'aws-sdk/dist/aws-sdk.min'>;
}
declare module 'aws-sdk/dist/xml2js.js' {
  declare module.exports: $Exports<'aws-sdk/dist/xml2js'>;
}
declare module 'aws-sdk/global.js' {
  declare module.exports: $Exports<'aws-sdk/global'>;
}
declare module 'aws-sdk/index' {
  declare module.exports: $Exports<'aws-sdk'>;
}
declare module 'aws-sdk/index.js' {
  declare module.exports: $Exports<'aws-sdk'>;
}
declare module 'aws-sdk/lib/api_loader.js' {
  declare module.exports: $Exports<'aws-sdk/lib/api_loader'>;
}
declare module 'aws-sdk/lib/aws.js' {
  declare module.exports: $Exports<'aws-sdk/lib/aws'>;
}
declare module 'aws-sdk/lib/browser_loader.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browser_loader'>;
}
declare module 'aws-sdk/lib/browser.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browser'>;
}
declare module 'aws-sdk/lib/browserCryptoLib.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browserCryptoLib'>;
}
declare module 'aws-sdk/lib/browserHashUtils.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browserHashUtils'>;
}
declare module 'aws-sdk/lib/browserHmac.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browserHmac'>;
}
declare module 'aws-sdk/lib/browserMd5.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browserMd5'>;
}
declare module 'aws-sdk/lib/browserSha1.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browserSha1'>;
}
declare module 'aws-sdk/lib/browserSha256.js' {
  declare module.exports: $Exports<'aws-sdk/lib/browserSha256'>;
}
declare module 'aws-sdk/lib/cloudfront/signer.js' {
  declare module.exports: $Exports<'aws-sdk/lib/cloudfront/signer'>;
}
declare module 'aws-sdk/lib/config_regional_endpoint.js' {
  declare module.exports: $Exports<'aws-sdk/lib/config_regional_endpoint'>;
}
declare module 'aws-sdk/lib/config.js' {
  declare module.exports: $Exports<'aws-sdk/lib/config'>;
}
declare module 'aws-sdk/lib/core.js' {
  declare module.exports: $Exports<'aws-sdk/lib/core'>;
}
declare module 'aws-sdk/lib/credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials'>;
}
declare module 'aws-sdk/lib/credentials/chainable_temporary_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/chainable_temporary_credentials'>;
}
declare module 'aws-sdk/lib/credentials/cognito_identity_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/cognito_identity_credentials'>;
}
declare module 'aws-sdk/lib/credentials/credential_provider_chain.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/credential_provider_chain'>;
}
declare module 'aws-sdk/lib/credentials/ec2_metadata_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/ec2_metadata_credentials'>;
}
declare module 'aws-sdk/lib/credentials/ecs_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/ecs_credentials'>;
}
declare module 'aws-sdk/lib/credentials/environment_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/environment_credentials'>;
}
declare module 'aws-sdk/lib/credentials/file_system_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/file_system_credentials'>;
}
declare module 'aws-sdk/lib/credentials/process_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/process_credentials'>;
}
declare module 'aws-sdk/lib/credentials/remote_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/remote_credentials'>;
}
declare module 'aws-sdk/lib/credentials/saml_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/saml_credentials'>;
}
declare module 'aws-sdk/lib/credentials/shared_ini_file_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/shared_ini_file_credentials'>;
}
declare module 'aws-sdk/lib/credentials/temporary_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/temporary_credentials'>;
}
declare module 'aws-sdk/lib/credentials/token_file_web_identity_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/token_file_web_identity_credentials'>;
}
declare module 'aws-sdk/lib/credentials/web_identity_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/credentials/web_identity_credentials'>;
}
declare module 'aws-sdk/lib/discover_endpoint.js' {
  declare module.exports: $Exports<'aws-sdk/lib/discover_endpoint'>;
}
declare module 'aws-sdk/lib/dynamodb/converter.js' {
  declare module.exports: $Exports<'aws-sdk/lib/dynamodb/converter'>;
}
declare module 'aws-sdk/lib/dynamodb/document_client.js' {
  declare module.exports: $Exports<'aws-sdk/lib/dynamodb/document_client'>;
}
declare module 'aws-sdk/lib/dynamodb/numberValue.js' {
  declare module.exports: $Exports<'aws-sdk/lib/dynamodb/numberValue'>;
}
declare module 'aws-sdk/lib/dynamodb/set.js' {
  declare module.exports: $Exports<'aws-sdk/lib/dynamodb/set'>;
}
declare module 'aws-sdk/lib/dynamodb/translator.js' {
  declare module.exports: $Exports<'aws-sdk/lib/dynamodb/translator'>;
}
declare module 'aws-sdk/lib/dynamodb/types.js' {
  declare module.exports: $Exports<'aws-sdk/lib/dynamodb/types'>;
}
declare module 'aws-sdk/lib/empty.js' {
  declare module.exports: $Exports<'aws-sdk/lib/empty'>;
}
declare module 'aws-sdk/lib/event_listeners.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event_listeners'>;
}
declare module 'aws-sdk/lib/event-stream/buffered-create-event-stream.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/buffered-create-event-stream'>;
}
declare module 'aws-sdk/lib/event-stream/build-message.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/build-message'>;
}
declare module 'aws-sdk/lib/event-stream/event-message-chunker-stream.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/event-message-chunker-stream'>;
}
declare module 'aws-sdk/lib/event-stream/event-message-chunker.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/event-message-chunker'>;
}
declare module 'aws-sdk/lib/event-stream/event-message-unmarshaller-stream.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/event-message-unmarshaller-stream'>;
}
declare module 'aws-sdk/lib/event-stream/int64.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/int64'>;
}
declare module 'aws-sdk/lib/event-stream/parse-event.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/parse-event'>;
}
declare module 'aws-sdk/lib/event-stream/parse-message.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/parse-message'>;
}
declare module 'aws-sdk/lib/event-stream/split-message.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/split-message'>;
}
declare module 'aws-sdk/lib/event-stream/streaming-create-event-stream.js' {
  declare module.exports: $Exports<'aws-sdk/lib/event-stream/streaming-create-event-stream'>;
}
declare module 'aws-sdk/lib/http.js' {
  declare module.exports: $Exports<'aws-sdk/lib/http'>;
}
declare module 'aws-sdk/lib/http/node.js' {
  declare module.exports: $Exports<'aws-sdk/lib/http/node'>;
}
declare module 'aws-sdk/lib/http/xhr.js' {
  declare module.exports: $Exports<'aws-sdk/lib/http/xhr'>;
}
declare module 'aws-sdk/lib/json/builder.js' {
  declare module.exports: $Exports<'aws-sdk/lib/json/builder'>;
}
declare module 'aws-sdk/lib/json/parser.js' {
  declare module.exports: $Exports<'aws-sdk/lib/json/parser'>;
}
declare module 'aws-sdk/lib/metadata_service.js' {
  declare module.exports: $Exports<'aws-sdk/lib/metadata_service'>;
}
declare module 'aws-sdk/lib/model/api.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/api'>;
}
declare module 'aws-sdk/lib/model/collection.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/collection'>;
}
declare module 'aws-sdk/lib/model/operation.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/operation'>;
}
declare module 'aws-sdk/lib/model/paginator.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/paginator'>;
}
declare module 'aws-sdk/lib/model/resource_waiter.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/resource_waiter'>;
}
declare module 'aws-sdk/lib/model/shape.js' {
  declare module.exports: $Exports<'aws-sdk/lib/model/shape'>;
}
declare module 'aws-sdk/lib/node_loader.js' {
  declare module.exports: $Exports<'aws-sdk/lib/node_loader'>;
}
declare module 'aws-sdk/lib/param_validator.js' {
  declare module.exports: $Exports<'aws-sdk/lib/param_validator'>;
}
declare module 'aws-sdk/lib/polly/presigner.js' {
  declare module.exports: $Exports<'aws-sdk/lib/polly/presigner'>;
}
declare module 'aws-sdk/lib/protocol/helpers.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/helpers'>;
}
declare module 'aws-sdk/lib/protocol/json.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/json'>;
}
declare module 'aws-sdk/lib/protocol/query.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/query'>;
}
declare module 'aws-sdk/lib/protocol/rest_json.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/rest_json'>;
}
declare module 'aws-sdk/lib/protocol/rest_xml.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/rest_xml'>;
}
declare module 'aws-sdk/lib/protocol/rest.js' {
  declare module.exports: $Exports<'aws-sdk/lib/protocol/rest'>;
}
declare module 'aws-sdk/lib/publisher/configuration.js' {
  declare module.exports: $Exports<'aws-sdk/lib/publisher/configuration'>;
}
declare module 'aws-sdk/lib/publisher/index' {
  declare module.exports: $Exports<'aws-sdk/lib/publisher'>;
}
declare module 'aws-sdk/lib/publisher/index.js' {
  declare module.exports: $Exports<'aws-sdk/lib/publisher'>;
}
declare module 'aws-sdk/lib/query/query_param_serializer.js' {
  declare module.exports: $Exports<'aws-sdk/lib/query/query_param_serializer'>;
}
declare module 'aws-sdk/lib/rds/signer.js' {
  declare module.exports: $Exports<'aws-sdk/lib/rds/signer'>;
}
declare module 'aws-sdk/lib/react-native-loader.js' {
  declare module.exports: $Exports<'aws-sdk/lib/react-native-loader'>;
}
declare module 'aws-sdk/lib/react-native/add-content-type.js' {
  declare module.exports: $Exports<'aws-sdk/lib/react-native/add-content-type'>;
}
declare module 'aws-sdk/lib/realclock/browserClock.js' {
  declare module.exports: $Exports<'aws-sdk/lib/realclock/browserClock'>;
}
declare module 'aws-sdk/lib/realclock/nodeClock.js' {
  declare module.exports: $Exports<'aws-sdk/lib/realclock/nodeClock'>;
}
declare module 'aws-sdk/lib/region_config.js' {
  declare module.exports: $Exports<'aws-sdk/lib/region_config'>;
}
declare module 'aws-sdk/lib/request.js' {
  declare module.exports: $Exports<'aws-sdk/lib/request'>;
}
declare module 'aws-sdk/lib/resource_waiter.js' {
  declare module.exports: $Exports<'aws-sdk/lib/resource_waiter'>;
}
declare module 'aws-sdk/lib/response.js' {
  declare module.exports: $Exports<'aws-sdk/lib/response'>;
}
declare module 'aws-sdk/lib/s3/managed_upload.js' {
  declare module.exports: $Exports<'aws-sdk/lib/s3/managed_upload'>;
}
declare module 'aws-sdk/lib/sequential_executor.js' {
  declare module.exports: $Exports<'aws-sdk/lib/sequential_executor'>;
}
declare module 'aws-sdk/lib/service.js' {
  declare module.exports: $Exports<'aws-sdk/lib/service'>;
}
declare module 'aws-sdk/lib/services/apigateway.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/apigateway'>;
}
declare module 'aws-sdk/lib/services/cloudfront.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/cloudfront'>;
}
declare module 'aws-sdk/lib/services/cloudsearchdomain.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/cloudsearchdomain'>;
}
declare module 'aws-sdk/lib/services/cognitoidentity.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/cognitoidentity'>;
}
declare module 'aws-sdk/lib/services/dynamodb.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/dynamodb'>;
}
declare module 'aws-sdk/lib/services/ec2.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/ec2'>;
}
declare module 'aws-sdk/lib/services/glacier.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/glacier'>;
}
declare module 'aws-sdk/lib/services/iotdata.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/iotdata'>;
}
declare module 'aws-sdk/lib/services/lambda.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/lambda'>;
}
declare module 'aws-sdk/lib/services/machinelearning.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/machinelearning'>;
}
declare module 'aws-sdk/lib/services/polly.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/polly'>;
}
declare module 'aws-sdk/lib/services/rds.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/rds'>;
}
declare module 'aws-sdk/lib/services/rdsdataservice.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/rdsdataservice'>;
}
declare module 'aws-sdk/lib/services/route53.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/route53'>;
}
declare module 'aws-sdk/lib/services/s3.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/s3'>;
}
declare module 'aws-sdk/lib/services/s3control.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/s3control'>;
}
declare module 'aws-sdk/lib/services/sqs.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/sqs'>;
}
declare module 'aws-sdk/lib/services/sts.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/sts'>;
}
declare module 'aws-sdk/lib/services/swf.js' {
  declare module.exports: $Exports<'aws-sdk/lib/services/swf'>;
}
declare module 'aws-sdk/lib/shared-ini/index' {
  declare module.exports: $Exports<'aws-sdk/lib/shared-ini'>;
}
declare module 'aws-sdk/lib/shared-ini/index.js' {
  declare module.exports: $Exports<'aws-sdk/lib/shared-ini'>;
}
declare module 'aws-sdk/lib/shared-ini/ini-loader.js' {
  declare module.exports: $Exports<'aws-sdk/lib/shared-ini/ini-loader'>;
}
declare module 'aws-sdk/lib/signers/presign.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/presign'>;
}
declare module 'aws-sdk/lib/signers/request_signer.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/request_signer'>;
}
declare module 'aws-sdk/lib/signers/s3.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/s3'>;
}
declare module 'aws-sdk/lib/signers/v2.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v2'>;
}
declare module 'aws-sdk/lib/signers/v3.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v3'>;
}
declare module 'aws-sdk/lib/signers/v3https.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v3https'>;
}
declare module 'aws-sdk/lib/signers/v4_credentials.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v4_credentials'>;
}
declare module 'aws-sdk/lib/signers/v4.js' {
  declare module.exports: $Exports<'aws-sdk/lib/signers/v4'>;
}
declare module 'aws-sdk/lib/state_machine.js' {
  declare module.exports: $Exports<'aws-sdk/lib/state_machine'>;
}
declare module 'aws-sdk/lib/util.js' {
  declare module.exports: $Exports<'aws-sdk/lib/util'>;
}
declare module 'aws-sdk/lib/xml/browser_parser.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/browser_parser'>;
}
declare module 'aws-sdk/lib/xml/builder.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/builder'>;
}
declare module 'aws-sdk/lib/xml/escape-attribute.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/escape-attribute'>;
}
declare module 'aws-sdk/lib/xml/escape-element.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/escape-element'>;
}
declare module 'aws-sdk/lib/xml/node_parser.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/node_parser'>;
}
declare module 'aws-sdk/lib/xml/xml-node.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/xml-node'>;
}
declare module 'aws-sdk/lib/xml/xml-text.js' {
  declare module.exports: $Exports<'aws-sdk/lib/xml/xml-text'>;
}
declare module 'aws-sdk/react-native.js' {
  declare module.exports: $Exports<'aws-sdk/react-native'>;
}
declare module 'aws-sdk/scripts/changelog/add-change.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/changelog/add-change'>;
}
declare module 'aws-sdk/scripts/changelog/change-creator.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/changelog/change-creator'>;
}
declare module 'aws-sdk/scripts/changelog/util.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/changelog/util'>;
}
declare module 'aws-sdk/scripts/composite-test.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/composite-test'>;
}
declare module 'aws-sdk/scripts/lib/get-operation-shape-names.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/lib/get-operation-shape-names'>;
}
declare module 'aws-sdk/scripts/lib/prune-shapes.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/lib/prune-shapes'>;
}
declare module 'aws-sdk/scripts/lib/remove-event-stream-ops.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/lib/remove-event-stream-ops'>;
}
declare module 'aws-sdk/scripts/lib/test-helper.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/lib/test-helper'>;
}
declare module 'aws-sdk/scripts/lib/translator.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/lib/translator'>;
}
declare module 'aws-sdk/scripts/lib/ts-generator.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/lib/ts-generator'>;
}
declare module 'aws-sdk/scripts/lib/visit-related-shape-names.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/lib/visit-related-shape-names'>;
}
declare module 'aws-sdk/scripts/region-checker/index' {
  declare module.exports: $Exports<'aws-sdk/scripts/region-checker'>;
}
declare module 'aws-sdk/scripts/region-checker/index.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/region-checker'>;
}
declare module 'aws-sdk/scripts/region-checker/whitelist.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/region-checker/whitelist'>;
}
declare module 'aws-sdk/scripts/services-table-generator.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/services-table-generator'>;
}
declare module 'aws-sdk/scripts/typings-generator.js' {
  declare module.exports: $Exports<'aws-sdk/scripts/typings-generator'>;
}
declare module 'aws-sdk/vendor/endpoint-cache/index' {
  declare module.exports: $Exports<'aws-sdk/vendor/endpoint-cache'>;
}
declare module 'aws-sdk/vendor/endpoint-cache/index.js' {
  declare module.exports: $Exports<'aws-sdk/vendor/endpoint-cache'>;
}
declare module 'aws-sdk/vendor/endpoint-cache/utils/LRU.js' {
  declare module.exports: $Exports<'aws-sdk/vendor/endpoint-cache/utils/LRU'>;
}
