// flow-typed signature: 312645f2a8bab19c593f2670a7ff103f
// flow-typed version: <<STUB>>/babel-plugin-lodash_v^3.2.11/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-lodash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-lodash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-lodash/lib/config' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/importModule' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/Map' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/MapCache' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/mapping' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/ModuleCache' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/Package' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/Store' {
  declare module.exports: any;
}

declare module 'babel-plugin-lodash/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-lodash/lib/config.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/config'>;
}
declare module 'babel-plugin-lodash/lib/importModule.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/importModule'>;
}
declare module 'babel-plugin-lodash/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/index'>;
}
declare module 'babel-plugin-lodash/lib/Map.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/Map'>;
}
declare module 'babel-plugin-lodash/lib/MapCache.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/MapCache'>;
}
declare module 'babel-plugin-lodash/lib/mapping.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/mapping'>;
}
declare module 'babel-plugin-lodash/lib/ModuleCache.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/ModuleCache'>;
}
declare module 'babel-plugin-lodash/lib/Package.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/Package'>;
}
declare module 'babel-plugin-lodash/lib/Store.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/Store'>;
}
declare module 'babel-plugin-lodash/lib/util.js' {
  declare module.exports: $Exports<'babel-plugin-lodash/lib/util'>;
}
