// flow-typed signature: 3abd654a395868c66a1c68d8267ff856
// flow-typed version: <<STUB>>/babel-preset-react-hmre_v1.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react-hmre'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react-hmre' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-react-hmre/test/Test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-react-hmre/index' {
  declare module.exports: $Exports<'babel-preset-react-hmre'>;
}
declare module 'babel-preset-react-hmre/index.js' {
  declare module.exports: $Exports<'babel-preset-react-hmre'>;
}
declare module 'babel-preset-react-hmre/test/Test.js' {
  declare module.exports: $Exports<'babel-preset-react-hmre/test/Test'>;
}
