// flow-typed signature: 81720de1e8cfea1529815ce45326fdff
// flow-typed version: <<STUB>>/boundless-popover_v^1.0.4/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boundless-popover'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boundless-popover' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boundless-popover/build' {
  declare module.exports: any;
}

declare module 'boundless-popover/demo' {
  declare module.exports: any;
}

declare module 'boundless-popover/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boundless-popover/build/index' {
  declare module.exports: $Exports<'boundless-popover/build'>;
}
declare module 'boundless-popover/build/index.js' {
  declare module.exports: $Exports<'boundless-popover/build'>;
}
declare module 'boundless-popover/demo/index' {
  declare module.exports: $Exports<'boundless-popover/demo'>;
}
declare module 'boundless-popover/demo/index.js' {
  declare module.exports: $Exports<'boundless-popover/demo'>;
}
declare module 'boundless-popover/index' {
  declare module.exports: $Exports<'boundless-popover'>;
}
declare module 'boundless-popover/index.js' {
  declare module.exports: $Exports<'boundless-popover'>;
}
declare module 'boundless-popover/index.spec.js' {
  declare module.exports: $Exports<'boundless-popover/index.spec'>;
}
