// flow-typed signature: 59397ad69c376794e3d306a1bd552752
// flow-typed version: <<STUB>>/boundless-arrow-key-navigation_v^1.0.4/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'boundless-arrow-key-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'boundless-arrow-key-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'boundless-arrow-key-navigation/build/index' {
  declare module.exports: any;
}

declare module 'boundless-arrow-key-navigation/demo/index' {
  declare module.exports: any;
}

declare module 'boundless-arrow-key-navigation/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'boundless-arrow-key-navigation/build/index.js' {
  declare module.exports: $Exports<'boundless-arrow-key-navigation/build/index'>;
}
declare module 'boundless-arrow-key-navigation/demo/index.js' {
  declare module.exports: $Exports<'boundless-arrow-key-navigation/demo/index'>;
}
declare module 'boundless-arrow-key-navigation/index' {
  declare module.exports: $Exports<'boundless-arrow-key-navigation'>;
}
declare module 'boundless-arrow-key-navigation/index.js' {
  declare module.exports: $Exports<'boundless-arrow-key-navigation'>;
}
declare module 'boundless-arrow-key-navigation/index.spec.js' {
  declare module.exports: $Exports<'boundless-arrow-key-navigation/index.spec'>;
}
