// flow-typed signature: e7351cb87cdb4db5495da290ee62842d
// flow-typed version: <<STUB>>/bugsnag_v^1.7.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bugsnag/Gruntfile' {
  declare module.exports: any;
}

declare module 'bugsnag/lib/bugsnag' {
  declare module.exports: any;
}

declare module 'bugsnag/lib/configuration' {
  declare module.exports: any;
}

declare module 'bugsnag/lib/error' {
  declare module.exports: any;
}

declare module 'bugsnag/lib/logger' {
  declare module.exports: any;
}

declare module 'bugsnag/lib/notification' {
  declare module.exports: any;
}

declare module 'bugsnag/lib/request_info' {
  declare module.exports: any;
}

declare module 'bugsnag/lib/utils' {
  declare module.exports: any;
}

declare module 'bugsnag/test/bugsnag' {
  declare module.exports: any;
}

declare module 'bugsnag/test/error' {
  declare module.exports: any;
}

declare module 'bugsnag/test/express' {
  declare module.exports: any;
}

declare module 'bugsnag/test/notification' {
  declare module.exports: any;
}

declare module 'bugsnag/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bugsnag/Gruntfile.js' {
  declare module.exports: $Exports<'bugsnag/Gruntfile'>;
}
declare module 'bugsnag/lib/bugsnag.js' {
  declare module.exports: $Exports<'bugsnag/lib/bugsnag'>;
}
declare module 'bugsnag/lib/configuration.js' {
  declare module.exports: $Exports<'bugsnag/lib/configuration'>;
}
declare module 'bugsnag/lib/error.js' {
  declare module.exports: $Exports<'bugsnag/lib/error'>;
}
declare module 'bugsnag/lib/logger.js' {
  declare module.exports: $Exports<'bugsnag/lib/logger'>;
}
declare module 'bugsnag/lib/notification.js' {
  declare module.exports: $Exports<'bugsnag/lib/notification'>;
}
declare module 'bugsnag/lib/request_info.js' {
  declare module.exports: $Exports<'bugsnag/lib/request_info'>;
}
declare module 'bugsnag/lib/utils.js' {
  declare module.exports: $Exports<'bugsnag/lib/utils'>;
}
declare module 'bugsnag/test/bugsnag.js' {
  declare module.exports: $Exports<'bugsnag/test/bugsnag'>;
}
declare module 'bugsnag/test/error.js' {
  declare module.exports: $Exports<'bugsnag/test/error'>;
}
declare module 'bugsnag/test/express.js' {
  declare module.exports: $Exports<'bugsnag/test/express'>;
}
declare module 'bugsnag/test/notification.js' {
  declare module.exports: $Exports<'bugsnag/test/notification'>;
}
declare module 'bugsnag/test/utils.js' {
  declare module.exports: $Exports<'bugsnag/test/utils'>;
}
