// flow-typed signature: 9a572b6bb9612e8d029312779affa26b
// flow-typed version: <<STUB>>/cancan_v3.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cancan'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cancan' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'cancan/index' {
  declare module.exports: $Exports<'cancan'>;
}
declare module 'cancan/index.js' {
  declare module.exports: $Exports<'cancan'>;
}
