// flow-typed signature: 0f5b991da0eab55a46333d265138ba11
// flow-typed version: <<STUB>>/diff_v3.5.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'diff/dist/diff' {
  declare module.exports: any;
}

declare module 'diff/dist/diff.min' {
  declare module.exports: any;
}

declare module 'diff/lib/convert/dmp' {
  declare module.exports: any;
}

declare module 'diff/lib/convert/xml' {
  declare module.exports: any;
}

declare module 'diff/lib/diff/array' {
  declare module.exports: any;
}

declare module 'diff/lib/diff/base' {
  declare module.exports: any;
}

declare module 'diff/lib/diff/character' {
  declare module.exports: any;
}

declare module 'diff/lib/diff/css' {
  declare module.exports: any;
}

declare module 'diff/lib/diff/json' {
  declare module.exports: any;
}

declare module 'diff/lib/diff/line' {
  declare module.exports: any;
}

declare module 'diff/lib/diff/sentence' {
  declare module.exports: any;
}

declare module 'diff/lib/diff/word' {
  declare module.exports: any;
}

declare module 'diff/lib/index' {
  declare module.exports: any;
}

declare module 'diff/lib/patch/apply' {
  declare module.exports: any;
}

declare module 'diff/lib/patch/create' {
  declare module.exports: any;
}

declare module 'diff/lib/patch/merge' {
  declare module.exports: any;
}

declare module 'diff/lib/patch/parse' {
  declare module.exports: any;
}

declare module 'diff/lib/util/array' {
  declare module.exports: any;
}

declare module 'diff/lib/util/distance-iterator' {
  declare module.exports: any;
}

declare module 'diff/lib/util/params' {
  declare module.exports: any;
}

declare module 'diff/runtime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'diff/dist/diff.js' {
  declare module.exports: $Exports<'diff/dist/diff'>;
}
declare module 'diff/dist/diff.min.js' {
  declare module.exports: $Exports<'diff/dist/diff.min'>;
}
declare module 'diff/lib/convert/dmp.js' {
  declare module.exports: $Exports<'diff/lib/convert/dmp'>;
}
declare module 'diff/lib/convert/xml.js' {
  declare module.exports: $Exports<'diff/lib/convert/xml'>;
}
declare module 'diff/lib/diff/array.js' {
  declare module.exports: $Exports<'diff/lib/diff/array'>;
}
declare module 'diff/lib/diff/base.js' {
  declare module.exports: $Exports<'diff/lib/diff/base'>;
}
declare module 'diff/lib/diff/character.js' {
  declare module.exports: $Exports<'diff/lib/diff/character'>;
}
declare module 'diff/lib/diff/css.js' {
  declare module.exports: $Exports<'diff/lib/diff/css'>;
}
declare module 'diff/lib/diff/json.js' {
  declare module.exports: $Exports<'diff/lib/diff/json'>;
}
declare module 'diff/lib/diff/line.js' {
  declare module.exports: $Exports<'diff/lib/diff/line'>;
}
declare module 'diff/lib/diff/sentence.js' {
  declare module.exports: $Exports<'diff/lib/diff/sentence'>;
}
declare module 'diff/lib/diff/word.js' {
  declare module.exports: $Exports<'diff/lib/diff/word'>;
}
declare module 'diff/lib/index.js' {
  declare module.exports: $Exports<'diff/lib/index'>;
}
declare module 'diff/lib/patch/apply.js' {
  declare module.exports: $Exports<'diff/lib/patch/apply'>;
}
declare module 'diff/lib/patch/create.js' {
  declare module.exports: $Exports<'diff/lib/patch/create'>;
}
declare module 'diff/lib/patch/merge.js' {
  declare module.exports: $Exports<'diff/lib/patch/merge'>;
}
declare module 'diff/lib/patch/parse.js' {
  declare module.exports: $Exports<'diff/lib/patch/parse'>;
}
declare module 'diff/lib/util/array.js' {
  declare module.exports: $Exports<'diff/lib/util/array'>;
}
declare module 'diff/lib/util/distance-iterator.js' {
  declare module.exports: $Exports<'diff/lib/util/distance-iterator'>;
}
declare module 'diff/lib/util/params.js' {
  declare module.exports: $Exports<'diff/lib/util/params'>;
}
declare module 'diff/runtime.js' {
  declare module.exports: $Exports<'diff/runtime'>;
}
