// flow-typed signature: df3a77883deb7981fa0bc043d8bd64b5
// flow-typed version: <<STUB>>/emoji-regex_v^6.5.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emoji-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emoji-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emoji-regex/es2015' {
  declare module.exports: any;
}

declare module 'emoji-regex/es2015/text' {
  declare module.exports: any;
}

declare module 'emoji-regex/text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emoji-regex/es2015/index' {
  declare module.exports: $Exports<'emoji-regex/es2015'>;
}
declare module 'emoji-regex/es2015/index.js' {
  declare module.exports: $Exports<'emoji-regex/es2015'>;
}
declare module 'emoji-regex/es2015/text.js' {
  declare module.exports: $Exports<'emoji-regex/es2015/text'>;
}
declare module 'emoji-regex/index' {
  declare module.exports: $Exports<'emoji-regex'>;
}
declare module 'emoji-regex/index.js' {
  declare module.exports: $Exports<'emoji-regex'>;
}
declare module 'emoji-regex/text.js' {
  declare module.exports: $Exports<'emoji-regex/text'>;
}
