// flow-typed signature: c88c3c46cc897461015c0a4f444f830b
// flow-typed version: <<STUB>>/extract-text-webpack-plugin_v1.0.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-text-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-text-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-text-webpack-plugin/ExtractedModule' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/loader' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/OrderUndefinedError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-text-webpack-plugin/ExtractedModule.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/ExtractedModule'>;
}
declare module 'extract-text-webpack-plugin/index' {
  declare module.exports: $Exports<'extract-text-webpack-plugin'>;
}
declare module 'extract-text-webpack-plugin/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin'>;
}
declare module 'extract-text-webpack-plugin/loader.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/loader'>;
}
declare module 'extract-text-webpack-plugin/OrderUndefinedError.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/OrderUndefinedError'>;
}
