// flow-typed signature: 13580009774392276ae66bdb72190d37
// flow-typed version: <<STUB>>/extract-text-webpack-plugin_v^3.0.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-text-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-text-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-text-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/lib/ExtractedModule' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/lib/ExtractTextPluginCompilation' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/lib/helpers' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/lib/OrderUndefinedError' {
  declare module.exports: any;
}

declare module 'extract-text-webpack-plugin/dist/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-text-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/cjs'>;
}
declare module 'extract-text-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/index'>;
}
declare module 'extract-text-webpack-plugin/dist/lib/ExtractedModule.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/lib/ExtractedModule'>;
}
declare module 'extract-text-webpack-plugin/dist/lib/ExtractTextPluginCompilation.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/lib/ExtractTextPluginCompilation'>;
}
declare module 'extract-text-webpack-plugin/dist/lib/helpers.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/lib/helpers'>;
}
declare module 'extract-text-webpack-plugin/dist/lib/OrderUndefinedError.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/lib/OrderUndefinedError'>;
}
declare module 'extract-text-webpack-plugin/dist/loader.js' {
  declare module.exports: $Exports<'extract-text-webpack-plugin/dist/loader'>;
}
