// flow-typed signature: 81f85c5fc3eb62a3d795e2e4240e438b
// flow-typed version: <<STUB>>/fbemitter_v^2.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fbemitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fbemitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fbemitter/lib/BaseEventEmitter' {
  declare module.exports: any;
}

declare module 'fbemitter/lib/EmitterSubscription' {
  declare module.exports: any;
}

declare module 'fbemitter/lib/EventSubscription' {
  declare module.exports: any;
}

declare module 'fbemitter/lib/EventSubscriptionVendor' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fbemitter/index' {
  declare module.exports: $Exports<'fbemitter'>;
}
declare module 'fbemitter/index.js' {
  declare module.exports: $Exports<'fbemitter'>;
}
declare module 'fbemitter/lib/BaseEventEmitter.js' {
  declare module.exports: $Exports<'fbemitter/lib/BaseEventEmitter'>;
}
declare module 'fbemitter/lib/EmitterSubscription.js' {
  declare module.exports: $Exports<'fbemitter/lib/EmitterSubscription'>;
}
declare module 'fbemitter/lib/EventSubscription.js' {
  declare module.exports: $Exports<'fbemitter/lib/EventSubscription'>;
}
declare module 'fbemitter/lib/EventSubscriptionVendor.js' {
  declare module.exports: $Exports<'fbemitter/lib/EventSubscriptionVendor'>;
}
