// flow-typed signature: 2d5889838efad90a1105daea66313af7
// flow-typed version: <<STUB>>/html-webpack-plugin_v2.17.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-webpack-plugin/lib/chunksorter' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/compiler' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/errors' {
  declare module.exports: any;
}

declare module 'html-webpack-plugin/lib/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-webpack-plugin/index' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/index.js' {
  declare module.exports: $Exports<'html-webpack-plugin'>;
}
declare module 'html-webpack-plugin/lib/chunksorter.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/chunksorter'>;
}
declare module 'html-webpack-plugin/lib/compiler.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/compiler'>;
}
declare module 'html-webpack-plugin/lib/errors.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/errors'>;
}
declare module 'html-webpack-plugin/lib/loader.js' {
  declare module.exports: $Exports<'html-webpack-plugin/lib/loader'>;
}
