// flow-typed signature: 27c00cb1bc9a39b5242058a544265b1b
// flow-typed version: <<STUB>>/identity-obj-proxy_v^3.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'identity-obj-proxy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'identity-obj-proxy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'identity-obj-proxy/src/__tests__/import-es6-export-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/__tests__/import-es6-import-export-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/__tests__/import-es6-import-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/__tests__/import-vanilla-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/__tests__/require-es6-export-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/__tests__/require-es6-import-export-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/__tests__/require-es6-import-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/__tests__/require-vanilla-test' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/index' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/test-redirections/idObjES6Export' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/test-redirections/idObjES6Import' {
  declare module.exports: any;
}

declare module 'identity-obj-proxy/src/test-redirections/idObjES6ImportExport' {
  declare module.exports: any;
}

// Filename aliases
declare module 'identity-obj-proxy/src/__tests__/import-es6-export-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/import-es6-export-test'>;
}
declare module 'identity-obj-proxy/src/__tests__/import-es6-import-export-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/import-es6-import-export-test'>;
}
declare module 'identity-obj-proxy/src/__tests__/import-es6-import-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/import-es6-import-test'>;
}
declare module 'identity-obj-proxy/src/__tests__/import-vanilla-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/import-vanilla-test'>;
}
declare module 'identity-obj-proxy/src/__tests__/index-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/index-test'>;
}
declare module 'identity-obj-proxy/src/__tests__/require-es6-export-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/require-es6-export-test'>;
}
declare module 'identity-obj-proxy/src/__tests__/require-es6-import-export-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/require-es6-import-export-test'>;
}
declare module 'identity-obj-proxy/src/__tests__/require-es6-import-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/require-es6-import-test'>;
}
declare module 'identity-obj-proxy/src/__tests__/require-vanilla-test.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/__tests__/require-vanilla-test'>;
}
declare module 'identity-obj-proxy/src/index.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/index'>;
}
declare module 'identity-obj-proxy/src/test-redirections/idObjES6Export.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/test-redirections/idObjES6Export'>;
}
declare module 'identity-obj-proxy/src/test-redirections/idObjES6Import.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/test-redirections/idObjES6Import'>;
}
declare module 'identity-obj-proxy/src/test-redirections/idObjES6ImportExport.js' {
  declare module.exports: $Exports<'identity-obj-proxy/src/test-redirections/idObjES6ImportExport'>;
}
