// flow-typed signature: b22b4468bfca789ab7d226b932705f45
// flow-typed version: <<STUB>>/ioredis_v^4.14.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ioredis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ioredis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ioredis/built/cluster/ClusterOptions' {
  declare module.exports: any;
}

declare module 'ioredis/built/cluster/ClusterSubscriber' {
  declare module.exports: any;
}

declare module 'ioredis/built/cluster/ConnectionPool' {
  declare module.exports: any;
}

declare module 'ioredis/built/cluster/DelayQueue' {
  declare module.exports: any;
}

declare module 'ioredis/built/cluster' {
  declare module.exports: any;
}

declare module 'ioredis/built/cluster/util' {
  declare module.exports: any;
}

declare module 'ioredis/built/command' {
  declare module.exports: any;
}

declare module 'ioredis/built/commander' {
  declare module.exports: any;
}

declare module 'ioredis/built/connectors/AbstractConnector' {
  declare module.exports: any;
}

declare module 'ioredis/built/connectors' {
  declare module.exports: any;
}

declare module 'ioredis/built/connectors/SentinelConnector' {
  declare module.exports: any;
}

declare module 'ioredis/built/connectors/SentinelConnector/SentinelIterator' {
  declare module.exports: any;
}

declare module 'ioredis/built/connectors/SentinelConnector/types' {
  declare module.exports: any;
}

declare module 'ioredis/built/connectors/StandaloneConnector' {
  declare module.exports: any;
}

declare module 'ioredis/built/DataHandler' {
  declare module.exports: any;
}

declare module 'ioredis/built/errors/ClusterAllFailedError' {
  declare module.exports: any;
}

declare module 'ioredis/built/errors' {
  declare module.exports: any;
}

declare module 'ioredis/built/errors/MaxRetriesPerRequestError' {
  declare module.exports: any;
}

declare module 'ioredis/built' {
  declare module.exports: any;
}

declare module 'ioredis/built/pipeline' {
  declare module.exports: any;
}

declare module 'ioredis/built/promiseContainer' {
  declare module.exports: any;
}

declare module 'ioredis/built/redis/event_handler' {
  declare module.exports: any;
}

declare module 'ioredis/built/redis' {
  declare module.exports: any;
}

declare module 'ioredis/built/redis/RedisOptions' {
  declare module.exports: any;
}

declare module 'ioredis/built/ScanStream' {
  declare module.exports: any;
}

declare module 'ioredis/built/script' {
  declare module.exports: any;
}

declare module 'ioredis/built/SubscriptionSet' {
  declare module.exports: any;
}

declare module 'ioredis/built/transaction' {
  declare module.exports: any;
}

declare module 'ioredis/built/types' {
  declare module.exports: any;
}

declare module 'ioredis/built/utils/debug' {
  declare module.exports: any;
}

declare module 'ioredis/built/utils' {
  declare module.exports: any;
}

declare module 'ioredis/built/utils/lodash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ioredis/built/cluster/ClusterOptions.js' {
  declare module.exports: $Exports<'ioredis/built/cluster/ClusterOptions'>;
}
declare module 'ioredis/built/cluster/ClusterSubscriber.js' {
  declare module.exports: $Exports<'ioredis/built/cluster/ClusterSubscriber'>;
}
declare module 'ioredis/built/cluster/ConnectionPool.js' {
  declare module.exports: $Exports<'ioredis/built/cluster/ConnectionPool'>;
}
declare module 'ioredis/built/cluster/DelayQueue.js' {
  declare module.exports: $Exports<'ioredis/built/cluster/DelayQueue'>;
}
declare module 'ioredis/built/cluster/index' {
  declare module.exports: $Exports<'ioredis/built/cluster'>;
}
declare module 'ioredis/built/cluster/index.js' {
  declare module.exports: $Exports<'ioredis/built/cluster'>;
}
declare module 'ioredis/built/cluster/util.js' {
  declare module.exports: $Exports<'ioredis/built/cluster/util'>;
}
declare module 'ioredis/built/command.js' {
  declare module.exports: $Exports<'ioredis/built/command'>;
}
declare module 'ioredis/built/commander.js' {
  declare module.exports: $Exports<'ioredis/built/commander'>;
}
declare module 'ioredis/built/connectors/AbstractConnector.js' {
  declare module.exports: $Exports<'ioredis/built/connectors/AbstractConnector'>;
}
declare module 'ioredis/built/connectors/index' {
  declare module.exports: $Exports<'ioredis/built/connectors'>;
}
declare module 'ioredis/built/connectors/index.js' {
  declare module.exports: $Exports<'ioredis/built/connectors'>;
}
declare module 'ioredis/built/connectors/SentinelConnector/index' {
  declare module.exports: $Exports<'ioredis/built/connectors/SentinelConnector'>;
}
declare module 'ioredis/built/connectors/SentinelConnector/index.js' {
  declare module.exports: $Exports<'ioredis/built/connectors/SentinelConnector'>;
}
declare module 'ioredis/built/connectors/SentinelConnector/SentinelIterator.js' {
  declare module.exports: $Exports<'ioredis/built/connectors/SentinelConnector/SentinelIterator'>;
}
declare module 'ioredis/built/connectors/SentinelConnector/types.js' {
  declare module.exports: $Exports<'ioredis/built/connectors/SentinelConnector/types'>;
}
declare module 'ioredis/built/connectors/StandaloneConnector.js' {
  declare module.exports: $Exports<'ioredis/built/connectors/StandaloneConnector'>;
}
declare module 'ioredis/built/DataHandler.js' {
  declare module.exports: $Exports<'ioredis/built/DataHandler'>;
}
declare module 'ioredis/built/errors/ClusterAllFailedError.js' {
  declare module.exports: $Exports<'ioredis/built/errors/ClusterAllFailedError'>;
}
declare module 'ioredis/built/errors/index' {
  declare module.exports: $Exports<'ioredis/built/errors'>;
}
declare module 'ioredis/built/errors/index.js' {
  declare module.exports: $Exports<'ioredis/built/errors'>;
}
declare module 'ioredis/built/errors/MaxRetriesPerRequestError.js' {
  declare module.exports: $Exports<'ioredis/built/errors/MaxRetriesPerRequestError'>;
}
declare module 'ioredis/built/index' {
  declare module.exports: $Exports<'ioredis/built'>;
}
declare module 'ioredis/built/index.js' {
  declare module.exports: $Exports<'ioredis/built'>;
}
declare module 'ioredis/built/pipeline.js' {
  declare module.exports: $Exports<'ioredis/built/pipeline'>;
}
declare module 'ioredis/built/promiseContainer.js' {
  declare module.exports: $Exports<'ioredis/built/promiseContainer'>;
}
declare module 'ioredis/built/redis/event_handler.js' {
  declare module.exports: $Exports<'ioredis/built/redis/event_handler'>;
}
declare module 'ioredis/built/redis/index' {
  declare module.exports: $Exports<'ioredis/built/redis'>;
}
declare module 'ioredis/built/redis/index.js' {
  declare module.exports: $Exports<'ioredis/built/redis'>;
}
declare module 'ioredis/built/redis/RedisOptions.js' {
  declare module.exports: $Exports<'ioredis/built/redis/RedisOptions'>;
}
declare module 'ioredis/built/ScanStream.js' {
  declare module.exports: $Exports<'ioredis/built/ScanStream'>;
}
declare module 'ioredis/built/script.js' {
  declare module.exports: $Exports<'ioredis/built/script'>;
}
declare module 'ioredis/built/SubscriptionSet.js' {
  declare module.exports: $Exports<'ioredis/built/SubscriptionSet'>;
}
declare module 'ioredis/built/transaction.js' {
  declare module.exports: $Exports<'ioredis/built/transaction'>;
}
declare module 'ioredis/built/types.js' {
  declare module.exports: $Exports<'ioredis/built/types'>;
}
declare module 'ioredis/built/utils/debug.js' {
  declare module.exports: $Exports<'ioredis/built/utils/debug'>;
}
declare module 'ioredis/built/utils/index' {
  declare module.exports: $Exports<'ioredis/built/utils'>;
}
declare module 'ioredis/built/utils/index.js' {
  declare module.exports: $Exports<'ioredis/built/utils'>;
}
declare module 'ioredis/built/utils/lodash.js' {
  declare module.exports: $Exports<'ioredis/built/utils/lodash'>;
}
