// flow-typed signature: 3b9af3a3b964e60dad18b033f1820e60
// flow-typed version: <<STUB>>/jest-cli_v^20.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-cli/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/args' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/getJest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/index' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/runCLI' {
  declare module.exports: any;
}

declare module 'jest-cli/build/constants' {
  declare module.exports: any;
}

declare module 'jest-cli/build/generateEmptyCoverage' {
  declare module.exports: any;
}

declare module 'jest-cli/build/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/BufferedConsole' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/colorize' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/createContext' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/formatTestNameByPattern' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/getMaxWorkers' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/getTestPathPattern' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/handleDeprecationWarnings' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/highlight' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/isValidPath' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/logDebugMessages' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/patternModeHelpers' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/Prompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/scrollList' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/terminalUtils' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/updateArgv' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/validatePattern' {
  declare module.exports: any;
}

declare module 'jest-cli/build/PatternPrompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/preRunMessage' {
  declare module.exports: any;
}

declare module 'jest-cli/build/ReporterDispatcher' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/BaseReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/CoverageReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/CoverageWorker' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/DefaultReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/getConsoleOutput' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/getResultHeader' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/NotifyReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/Status' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/SummaryReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/utils' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/VerboseReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/runJest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/runTest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/SearchSource' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestNamePatternPrompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestPathPatternPrompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestRunner' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestSequencer' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestWatcher' {
  declare module.exports: any;
}

declare module 'jest-cli/build/TestWorker' {
  declare module.exports: any;
}

declare module 'jest-cli/build/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-cli/bin/jest.js' {
  declare module.exports: $Exports<'jest-cli/bin/jest'>;
}
declare module 'jest-cli/build/cli/args.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/args'>;
}
declare module 'jest-cli/build/cli/getJest.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/getJest'>;
}
declare module 'jest-cli/build/cli/index.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/index'>;
}
declare module 'jest-cli/build/cli/runCLI.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/runCLI'>;
}
declare module 'jest-cli/build/constants.js' {
  declare module.exports: $Exports<'jest-cli/build/constants'>;
}
declare module 'jest-cli/build/generateEmptyCoverage.js' {
  declare module.exports: $Exports<'jest-cli/build/generateEmptyCoverage'>;
}
declare module 'jest-cli/build/jest.js' {
  declare module.exports: $Exports<'jest-cli/build/jest'>;
}
declare module 'jest-cli/build/lib/BufferedConsole.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/BufferedConsole'>;
}
declare module 'jest-cli/build/lib/colorize.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/colorize'>;
}
declare module 'jest-cli/build/lib/createContext.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/createContext'>;
}
declare module 'jest-cli/build/lib/formatTestNameByPattern.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/formatTestNameByPattern'>;
}
declare module 'jest-cli/build/lib/getMaxWorkers.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/getMaxWorkers'>;
}
declare module 'jest-cli/build/lib/getTestPathPattern.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/getTestPathPattern'>;
}
declare module 'jest-cli/build/lib/handleDeprecationWarnings.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/handleDeprecationWarnings'>;
}
declare module 'jest-cli/build/lib/highlight.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/highlight'>;
}
declare module 'jest-cli/build/lib/isValidPath.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/isValidPath'>;
}
declare module 'jest-cli/build/lib/logDebugMessages.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/logDebugMessages'>;
}
declare module 'jest-cli/build/lib/patternModeHelpers.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/patternModeHelpers'>;
}
declare module 'jest-cli/build/lib/Prompt.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/Prompt'>;
}
declare module 'jest-cli/build/lib/scrollList.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/scrollList'>;
}
declare module 'jest-cli/build/lib/terminalUtils.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/terminalUtils'>;
}
declare module 'jest-cli/build/lib/updateArgv.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/updateArgv'>;
}
declare module 'jest-cli/build/lib/validatePattern.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/validatePattern'>;
}
declare module 'jest-cli/build/PatternPrompt.js' {
  declare module.exports: $Exports<'jest-cli/build/PatternPrompt'>;
}
declare module 'jest-cli/build/preRunMessage.js' {
  declare module.exports: $Exports<'jest-cli/build/preRunMessage'>;
}
declare module 'jest-cli/build/ReporterDispatcher.js' {
  declare module.exports: $Exports<'jest-cli/build/ReporterDispatcher'>;
}
declare module 'jest-cli/build/reporters/BaseReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/BaseReporter'>;
}
declare module 'jest-cli/build/reporters/CoverageReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/CoverageReporter'>;
}
declare module 'jest-cli/build/reporters/CoverageWorker.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/CoverageWorker'>;
}
declare module 'jest-cli/build/reporters/DefaultReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/DefaultReporter'>;
}
declare module 'jest-cli/build/reporters/getConsoleOutput.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/getConsoleOutput'>;
}
declare module 'jest-cli/build/reporters/getResultHeader.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/getResultHeader'>;
}
declare module 'jest-cli/build/reporters/NotifyReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/NotifyReporter'>;
}
declare module 'jest-cli/build/reporters/Status.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/Status'>;
}
declare module 'jest-cli/build/reporters/SummaryReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/SummaryReporter'>;
}
declare module 'jest-cli/build/reporters/utils.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/utils'>;
}
declare module 'jest-cli/build/reporters/VerboseReporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/VerboseReporter'>;
}
declare module 'jest-cli/build/runJest.js' {
  declare module.exports: $Exports<'jest-cli/build/runJest'>;
}
declare module 'jest-cli/build/runTest.js' {
  declare module.exports: $Exports<'jest-cli/build/runTest'>;
}
declare module 'jest-cli/build/SearchSource.js' {
  declare module.exports: $Exports<'jest-cli/build/SearchSource'>;
}
declare module 'jest-cli/build/TestNamePatternPrompt.js' {
  declare module.exports: $Exports<'jest-cli/build/TestNamePatternPrompt'>;
}
declare module 'jest-cli/build/TestPathPatternPrompt.js' {
  declare module.exports: $Exports<'jest-cli/build/TestPathPatternPrompt'>;
}
declare module 'jest-cli/build/TestRunner.js' {
  declare module.exports: $Exports<'jest-cli/build/TestRunner'>;
}
declare module 'jest-cli/build/TestSequencer.js' {
  declare module.exports: $Exports<'jest-cli/build/TestSequencer'>;
}
declare module 'jest-cli/build/TestWatcher.js' {
  declare module.exports: $Exports<'jest-cli/build/TestWatcher'>;
}
declare module 'jest-cli/build/TestWorker.js' {
  declare module.exports: $Exports<'jest-cli/build/TestWorker'>;
}
declare module 'jest-cli/build/watch.js' {
  declare module.exports: $Exports<'jest-cli/build/watch'>;
}
