// flow-typed signature: f779571d521232ddbbf7cc505053d0de
// flow-typed version: <<STUB>>/jest-cli_v22/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-cli/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/args' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/get_jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/cli/index' {
  declare module.exports: any;
}

declare module 'jest-cli/build/constants' {
  declare module.exports: any;
}

declare module 'jest-cli/build/failed_tests_cache' {
  declare module.exports: any;
}

declare module 'jest-cli/build/generate_empty_coverage' {
  declare module.exports: any;
}

declare module 'jest-cli/build/get_changed_files_promise' {
  declare module.exports: any;
}

declare module 'jest-cli/build/get_no_test_found_failed' {
  declare module.exports: any;
}

declare module 'jest-cli/build/get_no_test_found_message' {
  declare module.exports: any;
}

declare module 'jest-cli/build/get_no_test_found_related_to_changed_files' {
  declare module.exports: any;
}

declare module 'jest-cli/build/get_no_test_found_verbose' {
  declare module.exports: any;
}

declare module 'jest-cli/build/get_no_test_found' {
  declare module.exports: any;
}

declare module 'jest-cli/build/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/colorize' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/create_context' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/format_test_name_by_pattern' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/handle_deprecation_warnings' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/is_valid_path' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/log_debug_messages' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/pattern_mode_helpers' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/Prompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/scroll_list' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/terminal_utils' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/update_global_config' {
  declare module.exports: any;
}

declare module 'jest-cli/build/lib/watch_plugin_registry' {
  declare module.exports: any;
}

declare module 'jest-cli/build/pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/pluralize' {
  declare module.exports: any;
}

declare module 'jest-cli/build/pre_run_message' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporter_dispatcher' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/base_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/coverage_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/coverage_worker' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/default_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/get_result_header' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/get_snapshot_status' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/get_snapshot_summary' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/notify_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/Status' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/summary_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/utils' {
  declare module.exports: any;
}

declare module 'jest-cli/build/reporters/verbose_reporter' {
  declare module.exports: any;
}

declare module 'jest-cli/build/run_jest' {
  declare module.exports: any;
}

declare module 'jest-cli/build/search_source' {
  declare module.exports: any;
}

declare module 'jest-cli/build/test_name_pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/test_path_pattern_prompt' {
  declare module.exports: any;
}

declare module 'jest-cli/build/test_path_pattern_to_regexp' {
  declare module.exports: any;
}

declare module 'jest-cli/build/test_result_helpers' {
  declare module.exports: any;
}

declare module 'jest-cli/build/test_scheduler' {
  declare module.exports: any;
}

declare module 'jest-cli/build/test_sequencer' {
  declare module.exports: any;
}

declare module 'jest-cli/build/test_watcher' {
  declare module.exports: any;
}

declare module 'jest-cli/build/types' {
  declare module.exports: any;
}

declare module 'jest-cli/build/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-cli/bin/jest.js' {
  declare module.exports: $Exports<'jest-cli/bin/jest'>;
}
declare module 'jest-cli/build/cli/args.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/args'>;
}
declare module 'jest-cli/build/cli/get_jest.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/get_jest'>;
}
declare module 'jest-cli/build/cli/index.js' {
  declare module.exports: $Exports<'jest-cli/build/cli/index'>;
}
declare module 'jest-cli/build/constants.js' {
  declare module.exports: $Exports<'jest-cli/build/constants'>;
}
declare module 'jest-cli/build/failed_tests_cache.js' {
  declare module.exports: $Exports<'jest-cli/build/failed_tests_cache'>;
}
declare module 'jest-cli/build/generate_empty_coverage.js' {
  declare module.exports: $Exports<'jest-cli/build/generate_empty_coverage'>;
}
declare module 'jest-cli/build/get_changed_files_promise.js' {
  declare module.exports: $Exports<'jest-cli/build/get_changed_files_promise'>;
}
declare module 'jest-cli/build/get_no_test_found_failed.js' {
  declare module.exports: $Exports<'jest-cli/build/get_no_test_found_failed'>;
}
declare module 'jest-cli/build/get_no_test_found_message.js' {
  declare module.exports: $Exports<'jest-cli/build/get_no_test_found_message'>;
}
declare module 'jest-cli/build/get_no_test_found_related_to_changed_files.js' {
  declare module.exports: $Exports<'jest-cli/build/get_no_test_found_related_to_changed_files'>;
}
declare module 'jest-cli/build/get_no_test_found_verbose.js' {
  declare module.exports: $Exports<'jest-cli/build/get_no_test_found_verbose'>;
}
declare module 'jest-cli/build/get_no_test_found.js' {
  declare module.exports: $Exports<'jest-cli/build/get_no_test_found'>;
}
declare module 'jest-cli/build/jest.js' {
  declare module.exports: $Exports<'jest-cli/build/jest'>;
}
declare module 'jest-cli/build/lib/colorize.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/colorize'>;
}
declare module 'jest-cli/build/lib/create_context.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/create_context'>;
}
declare module 'jest-cli/build/lib/format_test_name_by_pattern.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/format_test_name_by_pattern'>;
}
declare module 'jest-cli/build/lib/handle_deprecation_warnings.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/handle_deprecation_warnings'>;
}
declare module 'jest-cli/build/lib/is_valid_path.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/is_valid_path'>;
}
declare module 'jest-cli/build/lib/log_debug_messages.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/log_debug_messages'>;
}
declare module 'jest-cli/build/lib/pattern_mode_helpers.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/pattern_mode_helpers'>;
}
declare module 'jest-cli/build/lib/Prompt.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/Prompt'>;
}
declare module 'jest-cli/build/lib/scroll_list.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/scroll_list'>;
}
declare module 'jest-cli/build/lib/terminal_utils.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/terminal_utils'>;
}
declare module 'jest-cli/build/lib/update_global_config.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/update_global_config'>;
}
declare module 'jest-cli/build/lib/watch_plugin_registry.js' {
  declare module.exports: $Exports<'jest-cli/build/lib/watch_plugin_registry'>;
}
declare module 'jest-cli/build/pattern_prompt.js' {
  declare module.exports: $Exports<'jest-cli/build/pattern_prompt'>;
}
declare module 'jest-cli/build/pluralize.js' {
  declare module.exports: $Exports<'jest-cli/build/pluralize'>;
}
declare module 'jest-cli/build/pre_run_message.js' {
  declare module.exports: $Exports<'jest-cli/build/pre_run_message'>;
}
declare module 'jest-cli/build/reporter_dispatcher.js' {
  declare module.exports: $Exports<'jest-cli/build/reporter_dispatcher'>;
}
declare module 'jest-cli/build/reporters/base_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/base_reporter'>;
}
declare module 'jest-cli/build/reporters/coverage_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/coverage_reporter'>;
}
declare module 'jest-cli/build/reporters/coverage_worker.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/coverage_worker'>;
}
declare module 'jest-cli/build/reporters/default_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/default_reporter'>;
}
declare module 'jest-cli/build/reporters/get_result_header.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/get_result_header'>;
}
declare module 'jest-cli/build/reporters/get_snapshot_status.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/get_snapshot_status'>;
}
declare module 'jest-cli/build/reporters/get_snapshot_summary.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/get_snapshot_summary'>;
}
declare module 'jest-cli/build/reporters/notify_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/notify_reporter'>;
}
declare module 'jest-cli/build/reporters/Status.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/Status'>;
}
declare module 'jest-cli/build/reporters/summary_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/summary_reporter'>;
}
declare module 'jest-cli/build/reporters/utils.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/utils'>;
}
declare module 'jest-cli/build/reporters/verbose_reporter.js' {
  declare module.exports: $Exports<'jest-cli/build/reporters/verbose_reporter'>;
}
declare module 'jest-cli/build/run_jest.js' {
  declare module.exports: $Exports<'jest-cli/build/run_jest'>;
}
declare module 'jest-cli/build/search_source.js' {
  declare module.exports: $Exports<'jest-cli/build/search_source'>;
}
declare module 'jest-cli/build/test_name_pattern_prompt.js' {
  declare module.exports: $Exports<'jest-cli/build/test_name_pattern_prompt'>;
}
declare module 'jest-cli/build/test_path_pattern_prompt.js' {
  declare module.exports: $Exports<'jest-cli/build/test_path_pattern_prompt'>;
}
declare module 'jest-cli/build/test_path_pattern_to_regexp.js' {
  declare module.exports: $Exports<'jest-cli/build/test_path_pattern_to_regexp'>;
}
declare module 'jest-cli/build/test_result_helpers.js' {
  declare module.exports: $Exports<'jest-cli/build/test_result_helpers'>;
}
declare module 'jest-cli/build/test_scheduler.js' {
  declare module.exports: $Exports<'jest-cli/build/test_scheduler'>;
}
declare module 'jest-cli/build/test_sequencer.js' {
  declare module.exports: $Exports<'jest-cli/build/test_sequencer'>;
}
declare module 'jest-cli/build/test_watcher.js' {
  declare module.exports: $Exports<'jest-cli/build/test_watcher'>;
}
declare module 'jest-cli/build/types.js' {
  declare module.exports: $Exports<'jest-cli/build/types'>;
}
declare module 'jest-cli/build/watch.js' {
  declare module.exports: $Exports<'jest-cli/build/watch'>;
}
