// flow-typed signature: 0c1b27b8baedf441980d09ebd62250b0
// flow-typed version: <<STUB>>/js-tree_v1.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-tree/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-tree/index' {
  declare module.exports: $Exports<'js-tree'>;
}
declare module 'js-tree/index.js' {
  declare module.exports: $Exports<'js-tree'>;
}
declare module 'js-tree/test.js' {
  declare module.exports: $Exports<'js-tree/test'>;
}
