// flow-typed signature: 40db2407a2ea13a54c84b1a8c0a8cc0b
// flow-typed version: <<STUB>>/koa-jwt_v^3.6.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-jwt/lib/get-secret' {
  declare module.exports: any;
}

declare module 'koa-jwt/lib' {
  declare module.exports: any;
}

declare module 'koa-jwt/lib/resolvers/auth-header' {
  declare module.exports: any;
}

declare module 'koa-jwt/lib/resolvers/cookie' {
  declare module.exports: any;
}

declare module 'koa-jwt/lib/verify' {
  declare module.exports: any;
}

declare module 'koa-jwt/test/test-server' {
  declare module.exports: any;
}

declare module 'koa-jwt/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-jwt/lib/get-secret.js' {
  declare module.exports: $Exports<'koa-jwt/lib/get-secret'>;
}
declare module 'koa-jwt/lib/index' {
  declare module.exports: $Exports<'koa-jwt/lib'>;
}
declare module 'koa-jwt/lib/index.js' {
  declare module.exports: $Exports<'koa-jwt/lib'>;
}
declare module 'koa-jwt/lib/resolvers/auth-header.js' {
  declare module.exports: $Exports<'koa-jwt/lib/resolvers/auth-header'>;
}
declare module 'koa-jwt/lib/resolvers/cookie.js' {
  declare module.exports: $Exports<'koa-jwt/lib/resolvers/cookie'>;
}
declare module 'koa-jwt/lib/verify.js' {
  declare module.exports: $Exports<'koa-jwt/lib/verify'>;
}
declare module 'koa-jwt/test/test-server.js' {
  declare module.exports: $Exports<'koa-jwt/test/test-server'>;
}
declare module 'koa-jwt/test/test.js' {
  declare module.exports: $Exports<'koa-jwt/test/test'>;
}
