// flow-typed signature: d55e35ed3f2fe1449b25bb21fde8c810
// flow-typed version: <<STUB>>/koa-sendfile_v2.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-sendfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-sendfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-sendfile/index' {
  declare module.exports: $Exports<'koa-sendfile'>;
}
declare module 'koa-sendfile/index.js' {
  declare module.exports: $Exports<'koa-sendfile'>;
}
