// flow-typed signature: 9505cb4568f30f07959d9aacbd66f36a
// flow-typed version: <<STUB>>/koa-connect_v1.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-connect/examples/auth' {
  declare module.exports: any;
}

declare module 'koa-connect/examples/directory' {
  declare module.exports: any;
}

declare module 'koa-connect/examples/logger' {
  declare module.exports: any;
}

declare module 'koa-connect/examples/session' {
  declare module.exports: any;
}

declare module 'koa-connect/examples/simple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-connect/examples/auth.js' {
  declare module.exports: $Exports<'koa-connect/examples/auth'>;
}
declare module 'koa-connect/examples/directory.js' {
  declare module.exports: $Exports<'koa-connect/examples/directory'>;
}
declare module 'koa-connect/examples/logger.js' {
  declare module.exports: $Exports<'koa-connect/examples/logger'>;
}
declare module 'koa-connect/examples/session.js' {
  declare module.exports: $Exports<'koa-connect/examples/session'>;
}
declare module 'koa-connect/examples/simple.js' {
  declare module.exports: $Exports<'koa-connect/examples/simple'>;
}
declare module 'koa-connect/index' {
  declare module.exports: $Exports<'koa-connect'>;
}
declare module 'koa-connect/index.js' {
  declare module.exports: $Exports<'koa-connect'>;
}
