// flow-typed signature: 89306ac915701480b6045ee8a6fb6fd8
// flow-typed version: <<STUB>>/koa-onerror_v^4.0.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-onerror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-onerror' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-onerror/index' {
  declare module.exports: $Exports<'koa-onerror'>;
}
declare module 'koa-onerror/index.js' {
  declare module.exports: $Exports<'koa-onerror'>;
}
