// flow-typed signature: 67f955aa47ef544703526f425d601f4d
// flow-typed version: <<STUB>>/marked-sanitized_v^0.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marked-sanitized'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marked-sanitized' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marked-sanitized/lib/markedSanitize' {
  declare module.exports: any;
}

declare module 'marked-sanitized/test/markedSanitize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marked-sanitized/lib/markedSanitize.js' {
  declare module.exports: $Exports<'marked-sanitized/lib/markedSanitize'>;
}
declare module 'marked-sanitized/test/markedSanitize.js' {
  declare module.exports: $Exports<'marked-sanitized/test/markedSanitize'>;
}
