// flow-typed signature: 72f4dda370c62477740e019492f5b339
// flow-typed version: <<STUB>>/mobx-react_v^4.1.8/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mobx-react/build-rollup' {
  declare module.exports: any;
}

declare module 'mobx-react/custom' {
  declare module.exports: any;
}

declare module 'mobx-react/empty' {
  declare module.exports: any;
}

declare module 'mobx-react/index.min' {
  declare module.exports: any;
}

declare module 'mobx-react/native' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mobx-react/build-rollup.js' {
  declare module.exports: $Exports<'mobx-react/build-rollup'>;
}
declare module 'mobx-react/custom.js' {
  declare module.exports: $Exports<'mobx-react/custom'>;
}
declare module 'mobx-react/empty.js' {
  declare module.exports: $Exports<'mobx-react/empty'>;
}
declare module 'mobx-react/index' {
  declare module.exports: $Exports<'mobx-react'>;
}
declare module 'mobx-react/index.js' {
  declare module.exports: $Exports<'mobx-react'>;
}
declare module 'mobx-react/index.min.js' {
  declare module.exports: $Exports<'mobx-react/index.min'>;
}
declare module 'mobx-react/native.js' {
  declare module.exports: $Exports<'mobx-react/native'>;
}
