// flow-typed signature: 89b05c482deef90c424f9328d76844ed
// flow-typed version: <<STUB>>/natural-sort_v^1.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'natural-sort'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'natural-sort' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'natural-sort/dist/natural-sort' {
  declare module.exports: any;
}

// Filename aliases
declare module 'natural-sort/dist/natural-sort.js' {
  declare module.exports: $Exports<'natural-sort/dist/natural-sort'>;
}
