// flow-typed signature: 64ddca47610bf9f3b3493cd68aa6f946
// flow-typed version: <<STUB>>/nodemailer_v^4.4.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemailer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemailer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemailer/lib/addressparser/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/base64/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/dkim/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/dkim/message-parser' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/dkim/relaxed-body' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/dkim/sign' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/fetch/cookies' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/fetch/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/json-transport/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/mail-composer/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/mailer/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/mailer/mail-message' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/mime-funcs/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/mime-funcs/mime-types' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/mime-node/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/mime-node/last-newline' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/nodemailer' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/qp/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/sendmail-transport/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/sendmail-transport/le-unix' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/sendmail-transport/le-windows' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/ses-transport/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/shared/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/smtp-connection/data-stream' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/smtp-connection/http-proxy-client' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/smtp-connection/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/smtp-pool/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/smtp-pool/pool-resource' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/smtp-transport/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/stream-transport/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/well-known/index' {
  declare module.exports: any;
}

declare module 'nodemailer/lib/xoauth2/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemailer/lib/addressparser/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/addressparser/index'>;
}
declare module 'nodemailer/lib/base64/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/base64/index'>;
}
declare module 'nodemailer/lib/dkim/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/dkim/index'>;
}
declare module 'nodemailer/lib/dkim/message-parser.js' {
  declare module.exports: $Exports<'nodemailer/lib/dkim/message-parser'>;
}
declare module 'nodemailer/lib/dkim/relaxed-body.js' {
  declare module.exports: $Exports<'nodemailer/lib/dkim/relaxed-body'>;
}
declare module 'nodemailer/lib/dkim/sign.js' {
  declare module.exports: $Exports<'nodemailer/lib/dkim/sign'>;
}
declare module 'nodemailer/lib/fetch/cookies.js' {
  declare module.exports: $Exports<'nodemailer/lib/fetch/cookies'>;
}
declare module 'nodemailer/lib/fetch/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/fetch/index'>;
}
declare module 'nodemailer/lib/json-transport/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/json-transport/index'>;
}
declare module 'nodemailer/lib/mail-composer/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/mail-composer/index'>;
}
declare module 'nodemailer/lib/mailer/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/mailer/index'>;
}
declare module 'nodemailer/lib/mailer/mail-message.js' {
  declare module.exports: $Exports<'nodemailer/lib/mailer/mail-message'>;
}
declare module 'nodemailer/lib/mime-funcs/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/mime-funcs/index'>;
}
declare module 'nodemailer/lib/mime-funcs/mime-types.js' {
  declare module.exports: $Exports<'nodemailer/lib/mime-funcs/mime-types'>;
}
declare module 'nodemailer/lib/mime-node/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/mime-node/index'>;
}
declare module 'nodemailer/lib/mime-node/last-newline.js' {
  declare module.exports: $Exports<'nodemailer/lib/mime-node/last-newline'>;
}
declare module 'nodemailer/lib/nodemailer.js' {
  declare module.exports: $Exports<'nodemailer/lib/nodemailer'>;
}
declare module 'nodemailer/lib/qp/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/qp/index'>;
}
declare module 'nodemailer/lib/sendmail-transport/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/sendmail-transport/index'>;
}
declare module 'nodemailer/lib/sendmail-transport/le-unix.js' {
  declare module.exports: $Exports<'nodemailer/lib/sendmail-transport/le-unix'>;
}
declare module 'nodemailer/lib/sendmail-transport/le-windows.js' {
  declare module.exports: $Exports<'nodemailer/lib/sendmail-transport/le-windows'>;
}
declare module 'nodemailer/lib/ses-transport/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/ses-transport/index'>;
}
declare module 'nodemailer/lib/shared/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/shared/index'>;
}
declare module 'nodemailer/lib/smtp-connection/data-stream.js' {
  declare module.exports: $Exports<'nodemailer/lib/smtp-connection/data-stream'>;
}
declare module 'nodemailer/lib/smtp-connection/http-proxy-client.js' {
  declare module.exports: $Exports<'nodemailer/lib/smtp-connection/http-proxy-client'>;
}
declare module 'nodemailer/lib/smtp-connection/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/smtp-connection/index'>;
}
declare module 'nodemailer/lib/smtp-pool/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/smtp-pool/index'>;
}
declare module 'nodemailer/lib/smtp-pool/pool-resource.js' {
  declare module.exports: $Exports<'nodemailer/lib/smtp-pool/pool-resource'>;
}
declare module 'nodemailer/lib/smtp-transport/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/smtp-transport/index'>;
}
declare module 'nodemailer/lib/stream-transport/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/stream-transport/index'>;
}
declare module 'nodemailer/lib/well-known/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/well-known/index'>;
}
declare module 'nodemailer/lib/xoauth2/index.js' {
  declare module.exports: $Exports<'nodemailer/lib/xoauth2/index'>;
}
