// flow-typed signature: bb542302bc35e2d9212a92ff9be8869c
// flow-typed version: <<STUB>>/node-dev_v3.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-dev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-dev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-dev/lib/cfg' {
  declare module.exports: any;
}

declare module 'node-dev/lib/dedupe' {
  declare module.exports: any;
}

declare module 'node-dev/lib/hook' {
  declare module.exports: any;
}

declare module 'node-dev/lib/index' {
  declare module.exports: any;
}

declare module 'node-dev/lib/ipc' {
  declare module.exports: any;
}

declare module 'node-dev/lib/log' {
  declare module.exports: any;
}

declare module 'node-dev/lib/notify' {
  declare module.exports: any;
}

declare module 'node-dev/lib/resolveMain' {
  declare module.exports: any;
}

declare module 'node-dev/lib/wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-dev/lib/cfg.js' {
  declare module.exports: $Exports<'node-dev/lib/cfg'>;
}
declare module 'node-dev/lib/dedupe.js' {
  declare module.exports: $Exports<'node-dev/lib/dedupe'>;
}
declare module 'node-dev/lib/hook.js' {
  declare module.exports: $Exports<'node-dev/lib/hook'>;
}
declare module 'node-dev/lib/index.js' {
  declare module.exports: $Exports<'node-dev/lib/index'>;
}
declare module 'node-dev/lib/ipc.js' {
  declare module.exports: $Exports<'node-dev/lib/ipc'>;
}
declare module 'node-dev/lib/log.js' {
  declare module.exports: $Exports<'node-dev/lib/log'>;
}
declare module 'node-dev/lib/notify.js' {
  declare module.exports: $Exports<'node-dev/lib/notify'>;
}
declare module 'node-dev/lib/resolveMain.js' {
  declare module.exports: $Exports<'node-dev/lib/resolveMain'>;
}
declare module 'node-dev/lib/wrap.js' {
  declare module.exports: $Exports<'node-dev/lib/wrap'>;
}
