// flow-typed signature: 8d38c2d39417a7239f4f6895e58e62f6
// flow-typed version: <<STUB>>/nodemon_v^1.19.4/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nodemon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nodemon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nodemon/bin/nodemon' {
  declare module.exports: any;
}

declare module 'nodemon/bin/postinstall' {
  declare module.exports: any;
}

declare module 'nodemon/commitlint.config' {
  declare module.exports: any;
}

declare module 'nodemon/lib/cli' {
  declare module.exports: any;
}

declare module 'nodemon/lib/cli/parse' {
  declare module.exports: any;
}

declare module 'nodemon/lib/config/command' {
  declare module.exports: any;
}

declare module 'nodemon/lib/config/defaults' {
  declare module.exports: any;
}

declare module 'nodemon/lib/config/exec' {
  declare module.exports: any;
}

declare module 'nodemon/lib/config' {
  declare module.exports: any;
}

declare module 'nodemon/lib/config/load' {
  declare module.exports: any;
}

declare module 'nodemon/lib/help' {
  declare module.exports: any;
}

declare module 'nodemon/lib' {
  declare module.exports: any;
}

declare module 'nodemon/lib/monitor' {
  declare module.exports: any;
}

declare module 'nodemon/lib/monitor/match' {
  declare module.exports: any;
}

declare module 'nodemon/lib/monitor/run' {
  declare module.exports: any;
}

declare module 'nodemon/lib/monitor/signals' {
  declare module.exports: any;
}

declare module 'nodemon/lib/monitor/watch' {
  declare module.exports: any;
}

declare module 'nodemon/lib/nodemon' {
  declare module.exports: any;
}

declare module 'nodemon/lib/rules/add' {
  declare module.exports: any;
}

declare module 'nodemon/lib/rules' {
  declare module.exports: any;
}

declare module 'nodemon/lib/rules/parse' {
  declare module.exports: any;
}

declare module 'nodemon/lib/spawn' {
  declare module.exports: any;
}

declare module 'nodemon/lib/utils/bus' {
  declare module.exports: any;
}

declare module 'nodemon/lib/utils/clone' {
  declare module.exports: any;
}

declare module 'nodemon/lib/utils/colour' {
  declare module.exports: any;
}

declare module 'nodemon/lib/utils' {
  declare module.exports: any;
}

declare module 'nodemon/lib/utils/log' {
  declare module.exports: any;
}

declare module 'nodemon/lib/utils/merge' {
  declare module.exports: any;
}

declare module 'nodemon/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nodemon/bin/nodemon.js' {
  declare module.exports: $Exports<'nodemon/bin/nodemon'>;
}
declare module 'nodemon/bin/postinstall.js' {
  declare module.exports: $Exports<'nodemon/bin/postinstall'>;
}
declare module 'nodemon/commitlint.config.js' {
  declare module.exports: $Exports<'nodemon/commitlint.config'>;
}
declare module 'nodemon/lib/cli/index' {
  declare module.exports: $Exports<'nodemon/lib/cli'>;
}
declare module 'nodemon/lib/cli/index.js' {
  declare module.exports: $Exports<'nodemon/lib/cli'>;
}
declare module 'nodemon/lib/cli/parse.js' {
  declare module.exports: $Exports<'nodemon/lib/cli/parse'>;
}
declare module 'nodemon/lib/config/command.js' {
  declare module.exports: $Exports<'nodemon/lib/config/command'>;
}
declare module 'nodemon/lib/config/defaults.js' {
  declare module.exports: $Exports<'nodemon/lib/config/defaults'>;
}
declare module 'nodemon/lib/config/exec.js' {
  declare module.exports: $Exports<'nodemon/lib/config/exec'>;
}
declare module 'nodemon/lib/config/index' {
  declare module.exports: $Exports<'nodemon/lib/config'>;
}
declare module 'nodemon/lib/config/index.js' {
  declare module.exports: $Exports<'nodemon/lib/config'>;
}
declare module 'nodemon/lib/config/load.js' {
  declare module.exports: $Exports<'nodemon/lib/config/load'>;
}
declare module 'nodemon/lib/help/index' {
  declare module.exports: $Exports<'nodemon/lib/help'>;
}
declare module 'nodemon/lib/help/index.js' {
  declare module.exports: $Exports<'nodemon/lib/help'>;
}
declare module 'nodemon/lib/index' {
  declare module.exports: $Exports<'nodemon/lib'>;
}
declare module 'nodemon/lib/index.js' {
  declare module.exports: $Exports<'nodemon/lib'>;
}
declare module 'nodemon/lib/monitor/index' {
  declare module.exports: $Exports<'nodemon/lib/monitor'>;
}
declare module 'nodemon/lib/monitor/index.js' {
  declare module.exports: $Exports<'nodemon/lib/monitor'>;
}
declare module 'nodemon/lib/monitor/match.js' {
  declare module.exports: $Exports<'nodemon/lib/monitor/match'>;
}
declare module 'nodemon/lib/monitor/run.js' {
  declare module.exports: $Exports<'nodemon/lib/monitor/run'>;
}
declare module 'nodemon/lib/monitor/signals.js' {
  declare module.exports: $Exports<'nodemon/lib/monitor/signals'>;
}
declare module 'nodemon/lib/monitor/watch.js' {
  declare module.exports: $Exports<'nodemon/lib/monitor/watch'>;
}
declare module 'nodemon/lib/nodemon.js' {
  declare module.exports: $Exports<'nodemon/lib/nodemon'>;
}
declare module 'nodemon/lib/rules/add.js' {
  declare module.exports: $Exports<'nodemon/lib/rules/add'>;
}
declare module 'nodemon/lib/rules/index' {
  declare module.exports: $Exports<'nodemon/lib/rules'>;
}
declare module 'nodemon/lib/rules/index.js' {
  declare module.exports: $Exports<'nodemon/lib/rules'>;
}
declare module 'nodemon/lib/rules/parse.js' {
  declare module.exports: $Exports<'nodemon/lib/rules/parse'>;
}
declare module 'nodemon/lib/spawn.js' {
  declare module.exports: $Exports<'nodemon/lib/spawn'>;
}
declare module 'nodemon/lib/utils/bus.js' {
  declare module.exports: $Exports<'nodemon/lib/utils/bus'>;
}
declare module 'nodemon/lib/utils/clone.js' {
  declare module.exports: $Exports<'nodemon/lib/utils/clone'>;
}
declare module 'nodemon/lib/utils/colour.js' {
  declare module.exports: $Exports<'nodemon/lib/utils/colour'>;
}
declare module 'nodemon/lib/utils/index' {
  declare module.exports: $Exports<'nodemon/lib/utils'>;
}
declare module 'nodemon/lib/utils/index.js' {
  declare module.exports: $Exports<'nodemon/lib/utils'>;
}
declare module 'nodemon/lib/utils/log.js' {
  declare module.exports: $Exports<'nodemon/lib/utils/log'>;
}
declare module 'nodemon/lib/utils/merge.js' {
  declare module.exports: $Exports<'nodemon/lib/utils/merge'>;
}
declare module 'nodemon/lib/version.js' {
  declare module.exports: $Exports<'nodemon/lib/version'>;
}
