// flow-typed signature: 438806ae67b03fce866ea16b89cf8cf1
// flow-typed version: <<STUB>>/normalize.css_v4.1.1/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
