// flow-typed signature: f4c5cdcb9bb78a6558d6d86f40128474
// flow-typed version: <<STUB>>/oy-vey_v^0.10.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oy-vey'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oy-vey' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oy-vey/examples/hello/HelloWorldEmail' {
  declare module.exports: any;
}

declare module 'oy-vey/examples/hello/layouts/Layout' {
  declare module.exports: any;
}

declare module 'oy-vey/examples/hello/modules/Body' {
  declare module.exports: any;
}

declare module 'oy-vey/examples/hello/modules/EmptySpace' {
  declare module.exports: any;
}

declare module 'oy-vey/examples/hello/modules/Footer' {
  declare module.exports: any;
}

declare module 'oy-vey/examples/hello/modules/Header' {
  declare module.exports: any;
}

declare module 'oy-vey/examples/hello/server' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/__tests__/Oy-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/components/DefaultElement' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/Oy' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/BackgroundAbsoluteURLRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/EmptyTDRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/HrefAbsoluteURLRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/ImgAltTextRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/ImgAltTextStyleRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/ImgDimensionsRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/ShorthandFontRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/SixCharacterHexBackgroundColorRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/SrcAbsoluteURLRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/TableBorderRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/TableCellPaddingRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/__tests__/TableCellSpacingRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/BackgroundAbsoluteURLRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/EmptyTDRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/HrefAbsoluteURLRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/ImgAltTextRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/ImgAltTextStyleRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/ImgDimensionsRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/index' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/ShorthandFontRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/SixCharacterHexBackgroundColorRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/SrcAbsoluteURLRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/TableBorderRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/TableCellPaddingRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/rules/TableCellSpacingRule' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/utils/__tests__/CSS-test' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/utils/CSS' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/utils/HTML4' {
  declare module.exports: any;
}

declare module 'oy-vey/lib/utils/Renderer' {
  declare module.exports: any;
}

declare module 'oy-vey/src/components/DefaultElement' {
  declare module.exports: any;
}

declare module 'oy-vey/src/Oy' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/BackgroundAbsoluteURLRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/EmptyTDRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/HrefAbsoluteURLRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/ImgAltTextRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/ImgAltTextStyleRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/ImgDimensionsRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/ShorthandFontRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/SixCharacterHexBackgroundColorRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/SrcAbsoluteURLRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/TableBorderRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/TableCellPaddingRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/__tests__/TableCellSpacingRule-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/BackgroundAbsoluteURLRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/EmptyTDRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/HrefAbsoluteURLRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/ImgAltTextRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/ImgAltTextStyleRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/ImgDimensionsRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/index' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/ShorthandFontRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/SixCharacterHexBackgroundColorRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/SrcAbsoluteURLRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/TableBorderRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/TableCellPaddingRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/rules/TableCellSpacingRule' {
  declare module.exports: any;
}

declare module 'oy-vey/src/utils/__tests__/CSS-test' {
  declare module.exports: any;
}

declare module 'oy-vey/src/utils/CSS' {
  declare module.exports: any;
}

declare module 'oy-vey/src/utils/HTML4' {
  declare module.exports: any;
}

declare module 'oy-vey/src/utils/Renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oy-vey/examples/hello/HelloWorldEmail.jsx' {
  declare module.exports: $Exports<'oy-vey/examples/hello/HelloWorldEmail'>;
}
declare module 'oy-vey/examples/hello/layouts/Layout.jsx' {
  declare module.exports: $Exports<'oy-vey/examples/hello/layouts/Layout'>;
}
declare module 'oy-vey/examples/hello/modules/Body.jsx' {
  declare module.exports: $Exports<'oy-vey/examples/hello/modules/Body'>;
}
declare module 'oy-vey/examples/hello/modules/EmptySpace.jsx' {
  declare module.exports: $Exports<'oy-vey/examples/hello/modules/EmptySpace'>;
}
declare module 'oy-vey/examples/hello/modules/Footer.jsx' {
  declare module.exports: $Exports<'oy-vey/examples/hello/modules/Footer'>;
}
declare module 'oy-vey/examples/hello/modules/Header.jsx' {
  declare module.exports: $Exports<'oy-vey/examples/hello/modules/Header'>;
}
declare module 'oy-vey/examples/hello/server.js' {
  declare module.exports: $Exports<'oy-vey/examples/hello/server'>;
}
declare module 'oy-vey/lib/__tests__/Oy-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/__tests__/Oy-test'>;
}
declare module 'oy-vey/lib/components/DefaultElement.js' {
  declare module.exports: $Exports<'oy-vey/lib/components/DefaultElement'>;
}
declare module 'oy-vey/lib/Oy.js' {
  declare module.exports: $Exports<'oy-vey/lib/Oy'>;
}
declare module 'oy-vey/lib/rules/__tests__/BackgroundAbsoluteURLRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/BackgroundAbsoluteURLRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/EmptyTDRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/EmptyTDRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/HrefAbsoluteURLRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/HrefAbsoluteURLRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/ImgAltTextRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/ImgAltTextRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/ImgAltTextStyleRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/ImgAltTextStyleRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/ImgDimensionsRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/ImgDimensionsRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/ShorthandFontRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/ShorthandFontRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/SixCharacterHexBackgroundColorRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/SixCharacterHexBackgroundColorRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/SrcAbsoluteURLRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/SrcAbsoluteURLRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/TableBorderRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/TableBorderRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/TableCellPaddingRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/TableCellPaddingRule-test'>;
}
declare module 'oy-vey/lib/rules/__tests__/TableCellSpacingRule-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/__tests__/TableCellSpacingRule-test'>;
}
declare module 'oy-vey/lib/rules/BackgroundAbsoluteURLRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/BackgroundAbsoluteURLRule'>;
}
declare module 'oy-vey/lib/rules/EmptyTDRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/EmptyTDRule'>;
}
declare module 'oy-vey/lib/rules/HrefAbsoluteURLRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/HrefAbsoluteURLRule'>;
}
declare module 'oy-vey/lib/rules/ImgAltTextRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/ImgAltTextRule'>;
}
declare module 'oy-vey/lib/rules/ImgAltTextStyleRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/ImgAltTextStyleRule'>;
}
declare module 'oy-vey/lib/rules/ImgDimensionsRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/ImgDimensionsRule'>;
}
declare module 'oy-vey/lib/rules/index.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/index'>;
}
declare module 'oy-vey/lib/rules/ShorthandFontRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/ShorthandFontRule'>;
}
declare module 'oy-vey/lib/rules/SixCharacterHexBackgroundColorRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/SixCharacterHexBackgroundColorRule'>;
}
declare module 'oy-vey/lib/rules/SrcAbsoluteURLRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/SrcAbsoluteURLRule'>;
}
declare module 'oy-vey/lib/rules/TableBorderRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/TableBorderRule'>;
}
declare module 'oy-vey/lib/rules/TableCellPaddingRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/TableCellPaddingRule'>;
}
declare module 'oy-vey/lib/rules/TableCellSpacingRule.js' {
  declare module.exports: $Exports<'oy-vey/lib/rules/TableCellSpacingRule'>;
}
declare module 'oy-vey/lib/utils/__tests__/CSS-test.js' {
  declare module.exports: $Exports<'oy-vey/lib/utils/__tests__/CSS-test'>;
}
declare module 'oy-vey/lib/utils/CSS.js' {
  declare module.exports: $Exports<'oy-vey/lib/utils/CSS'>;
}
declare module 'oy-vey/lib/utils/HTML4.js' {
  declare module.exports: $Exports<'oy-vey/lib/utils/HTML4'>;
}
declare module 'oy-vey/lib/utils/Renderer.js' {
  declare module.exports: $Exports<'oy-vey/lib/utils/Renderer'>;
}
declare module 'oy-vey/src/components/DefaultElement.jsx' {
  declare module.exports: $Exports<'oy-vey/src/components/DefaultElement'>;
}
declare module 'oy-vey/src/Oy.js' {
  declare module.exports: $Exports<'oy-vey/src/Oy'>;
}
declare module 'oy-vey/src/rules/__tests__/BackgroundAbsoluteURLRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/BackgroundAbsoluteURLRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/EmptyTDRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/EmptyTDRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/HrefAbsoluteURLRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/HrefAbsoluteURLRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/ImgAltTextRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/ImgAltTextRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/ImgAltTextStyleRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/ImgAltTextStyleRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/ImgDimensionsRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/ImgDimensionsRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/ShorthandFontRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/ShorthandFontRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/SixCharacterHexBackgroundColorRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/SixCharacterHexBackgroundColorRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/SrcAbsoluteURLRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/SrcAbsoluteURLRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/TableBorderRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/TableBorderRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/TableCellPaddingRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/TableCellPaddingRule-test'>;
}
declare module 'oy-vey/src/rules/__tests__/TableCellSpacingRule-test.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/__tests__/TableCellSpacingRule-test'>;
}
declare module 'oy-vey/src/rules/BackgroundAbsoluteURLRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/BackgroundAbsoluteURLRule'>;
}
declare module 'oy-vey/src/rules/EmptyTDRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/EmptyTDRule'>;
}
declare module 'oy-vey/src/rules/HrefAbsoluteURLRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/HrefAbsoluteURLRule'>;
}
declare module 'oy-vey/src/rules/ImgAltTextRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/ImgAltTextRule'>;
}
declare module 'oy-vey/src/rules/ImgAltTextStyleRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/ImgAltTextStyleRule'>;
}
declare module 'oy-vey/src/rules/ImgDimensionsRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/ImgDimensionsRule'>;
}
declare module 'oy-vey/src/rules/index.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/index'>;
}
declare module 'oy-vey/src/rules/ShorthandFontRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/ShorthandFontRule'>;
}
declare module 'oy-vey/src/rules/SixCharacterHexBackgroundColorRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/SixCharacterHexBackgroundColorRule'>;
}
declare module 'oy-vey/src/rules/SrcAbsoluteURLRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/SrcAbsoluteURLRule'>;
}
declare module 'oy-vey/src/rules/TableBorderRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/TableBorderRule'>;
}
declare module 'oy-vey/src/rules/TableCellPaddingRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/TableCellPaddingRule'>;
}
declare module 'oy-vey/src/rules/TableCellSpacingRule.js' {
  declare module.exports: $Exports<'oy-vey/src/rules/TableCellSpacingRule'>;
}
declare module 'oy-vey/src/utils/__tests__/CSS-test.js' {
  declare module.exports: $Exports<'oy-vey/src/utils/__tests__/CSS-test'>;
}
declare module 'oy-vey/src/utils/CSS.js' {
  declare module.exports: $Exports<'oy-vey/src/utils/CSS'>;
}
declare module 'oy-vey/src/utils/HTML4.js' {
  declare module.exports: $Exports<'oy-vey/src/utils/HTML4'>;
}
declare module 'oy-vey/src/utils/Renderer.js' {
  declare module.exports: $Exports<'oy-vey/src/utils/Renderer'>;
}
