// flow-typed signature: 21d87fdf0efc02246bbb85ba4e27543e
// flow-typed version: <<STUB>>/parse-domain_v2.1.6/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-domain'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-domain' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-domain/lib/normalize' {
  declare module.exports: any;
}

declare module 'parse-domain/lib/parseDomain' {
  declare module.exports: any;
}

declare module 'parse-domain/lib/tries/lookUp' {
  declare module.exports: any;
}

declare module 'parse-domain/lib/tries/parsePubSuffixList' {
  declare module.exports: any;
}

declare module 'parse-domain/lib/tries/parseTrie' {
  declare module.exports: any;
}

declare module 'parse-domain/lib/tries/separators' {
  declare module.exports: any;
}

declare module 'parse-domain/lib/tries/serializeTrie' {
  declare module.exports: any;
}

declare module 'parse-domain/lists/icann.complete' {
  declare module.exports: any;
}

declare module 'parse-domain/lists/icann.light' {
  declare module.exports: any;
}

declare module 'parse-domain/lists/private.complete' {
  declare module.exports: any;
}

declare module 'parse-domain/scripts/build-tries' {
  declare module.exports: any;
}

declare module 'parse-domain/scripts/link-src' {
  declare module.exports: any;
}

declare module 'parse-domain/test/parseDomain.test' {
  declare module.exports: any;
}

declare module 'parse-domain/test/snapshots.test' {
  declare module.exports: any;
}

declare module 'parse-domain/test/tries/lookUp.test' {
  declare module.exports: any;
}

declare module 'parse-domain/test/tries/parsePubSuffixList.test' {
  declare module.exports: any;
}

declare module 'parse-domain/test/tries/parseTrie.test' {
  declare module.exports: any;
}

declare module 'parse-domain/test/tries/serializeTrie.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-domain/lib/normalize.js' {
  declare module.exports: $Exports<'parse-domain/lib/normalize'>;
}
declare module 'parse-domain/lib/parseDomain.js' {
  declare module.exports: $Exports<'parse-domain/lib/parseDomain'>;
}
declare module 'parse-domain/lib/tries/lookUp.js' {
  declare module.exports: $Exports<'parse-domain/lib/tries/lookUp'>;
}
declare module 'parse-domain/lib/tries/parsePubSuffixList.js' {
  declare module.exports: $Exports<'parse-domain/lib/tries/parsePubSuffixList'>;
}
declare module 'parse-domain/lib/tries/parseTrie.js' {
  declare module.exports: $Exports<'parse-domain/lib/tries/parseTrie'>;
}
declare module 'parse-domain/lib/tries/separators.js' {
  declare module.exports: $Exports<'parse-domain/lib/tries/separators'>;
}
declare module 'parse-domain/lib/tries/serializeTrie.js' {
  declare module.exports: $Exports<'parse-domain/lib/tries/serializeTrie'>;
}
declare module 'parse-domain/lists/icann.complete.js' {
  declare module.exports: $Exports<'parse-domain/lists/icann.complete'>;
}
declare module 'parse-domain/lists/icann.light.js' {
  declare module.exports: $Exports<'parse-domain/lists/icann.light'>;
}
declare module 'parse-domain/lists/private.complete.js' {
  declare module.exports: $Exports<'parse-domain/lists/private.complete'>;
}
declare module 'parse-domain/scripts/build-tries.js' {
  declare module.exports: $Exports<'parse-domain/scripts/build-tries'>;
}
declare module 'parse-domain/scripts/link-src.js' {
  declare module.exports: $Exports<'parse-domain/scripts/link-src'>;
}
declare module 'parse-domain/test/parseDomain.test.js' {
  declare module.exports: $Exports<'parse-domain/test/parseDomain.test'>;
}
declare module 'parse-domain/test/snapshots.test.js' {
  declare module.exports: $Exports<'parse-domain/test/snapshots.test'>;
}
declare module 'parse-domain/test/tries/lookUp.test.js' {
  declare module.exports: $Exports<'parse-domain/test/tries/lookUp.test'>;
}
declare module 'parse-domain/test/tries/parsePubSuffixList.test.js' {
  declare module.exports: $Exports<'parse-domain/test/tries/parsePubSuffixList.test'>;
}
declare module 'parse-domain/test/tries/parseTrie.test.js' {
  declare module.exports: $Exports<'parse-domain/test/tries/parseTrie.test'>;
}
declare module 'parse-domain/test/tries/serializeTrie.test.js' {
  declare module.exports: $Exports<'parse-domain/test/tries/serializeTrie.test'>;
}
