// flow-typed signature: fe73065ec979006bfab6a2fb250ce75e
// flow-typed version: <<STUB>>/passport-slack_v0.0.7/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-slack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-slack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-slack/lib/passport-slack/index' {
  declare module.exports: any;
}

declare module 'passport-slack/lib/passport-slack/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-slack/lib/passport-slack/index.js' {
  declare module.exports: $Exports<'passport-slack/lib/passport-slack/index'>;
}
declare module 'passport-slack/lib/passport-slack/strategy.js' {
  declare module.exports: $Exports<'passport-slack/lib/passport-slack/strategy'>;
}
