// flow-typed signature: 4f696097e83d338e379a6366a9a9a439
// flow-typed version: <<STUB>>/passport-oauth_v1.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-oauth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-oauth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-oauth/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-oauth/lib/index.js' {
  declare module.exports: $Exports<'passport-oauth/lib/index'>;
}
