// flow-typed signature: 42ad823ab37dde13ce79450fdc022ab4
// flow-typed version: <<STUB>>/pg-hstore_v2.3.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-hstore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-hstore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg-hstore/lib/index' {
  declare module.exports: any;
}

declare module 'pg-hstore/test/index' {
  declare module.exports: any;
}

declare module 'pg-hstore/test/parse' {
  declare module.exports: any;
}

declare module 'pg-hstore/test/stringify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg-hstore/lib/index.js' {
  declare module.exports: $Exports<'pg-hstore/lib/index'>;
}
declare module 'pg-hstore/test/index.js' {
  declare module.exports: $Exports<'pg-hstore/test/index'>;
}
declare module 'pg-hstore/test/parse.js' {
  declare module.exports: $Exports<'pg-hstore/test/parse'>;
}
declare module 'pg-hstore/test/stringify.js' {
  declare module.exports: $Exports<'pg-hstore/test/stringify'>;
}
