// flow-typed signature: c863df4d6a6503443aae949b78b7d534
// flow-typed version: <<STUB>>/pui-react-tooltip_v^8.3.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pui-react-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pui-react-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pui-react-tooltip/tooltip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pui-react-tooltip/tooltip.js' {
  declare module.exports: $Exports<'pui-react-tooltip/tooltip'>;
}
