// flow-typed signature: 0b5a9e3ddbb48e4532d5be95fa91a314
// flow-typed version: <<STUB>>/randomstring_v1.1.5/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'randomstring'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'randomstring' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'randomstring/lib/charset' {
  declare module.exports: any;
}

declare module 'randomstring/lib/randomstring' {
  declare module.exports: any;
}

declare module 'randomstring/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'randomstring/index' {
  declare module.exports: $Exports<'randomstring'>;
}
declare module 'randomstring/index.js' {
  declare module.exports: $Exports<'randomstring'>;
}
declare module 'randomstring/lib/charset.js' {
  declare module.exports: $Exports<'randomstring/lib/charset'>;
}
declare module 'randomstring/lib/randomstring.js' {
  declare module.exports: $Exports<'randomstring/lib/randomstring'>;
}
declare module 'randomstring/test/index.js' {
  declare module.exports: $Exports<'randomstring/test/index'>;
}
