// flow-typed signature: 288146b7c4a1ae6cfec86fa1bed560b4
// flow-typed version: <<STUB>>/react-markdown_v^3.0.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-markdown/demo/dist/js/codemirror' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/dist/js/demo' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/src/code-block' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/src/demo' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/src/editor' {
  declare module.exports: any;
}

declare module 'react-markdown/demo/src/markdown-controls' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/ast-to-react' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/get-definitions' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/plugins/disallow-node' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/plugins/naive-html' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/renderers' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/uriTransformer' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/wrap-table-rows' {
  declare module.exports: any;
}

declare module 'react-markdown/src/ast-to-react' {
  declare module.exports: any;
}

declare module 'react-markdown/src/get-definitions' {
  declare module.exports: any;
}

declare module 'react-markdown/src/plugins/disallow-node' {
  declare module.exports: any;
}

declare module 'react-markdown/src/plugins/naive-html' {
  declare module.exports: any;
}

declare module 'react-markdown/src/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/src/renderers' {
  declare module.exports: any;
}

declare module 'react-markdown/src/uriTransformer' {
  declare module.exports: any;
}

declare module 'react-markdown/src/wrap-table-rows' {
  declare module.exports: any;
}

declare module 'react-markdown/umd/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/webpack.config.demo' {
  declare module.exports: any;
}

declare module 'react-markdown/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-markdown/demo/dist/js/codemirror.js' {
  declare module.exports: $Exports<'react-markdown/demo/dist/js/codemirror'>;
}
declare module 'react-markdown/demo/dist/js/demo.js' {
  declare module.exports: $Exports<'react-markdown/demo/dist/js/demo'>;
}
declare module 'react-markdown/demo/src/code-block.js' {
  declare module.exports: $Exports<'react-markdown/demo/src/code-block'>;
}
declare module 'react-markdown/demo/src/demo.js' {
  declare module.exports: $Exports<'react-markdown/demo/src/demo'>;
}
declare module 'react-markdown/demo/src/editor.js' {
  declare module.exports: $Exports<'react-markdown/demo/src/editor'>;
}
declare module 'react-markdown/demo/src/markdown-controls.js' {
  declare module.exports: $Exports<'react-markdown/demo/src/markdown-controls'>;
}
declare module 'react-markdown/lib/ast-to-react.js' {
  declare module.exports: $Exports<'react-markdown/lib/ast-to-react'>;
}
declare module 'react-markdown/lib/get-definitions.js' {
  declare module.exports: $Exports<'react-markdown/lib/get-definitions'>;
}
declare module 'react-markdown/lib/plugins/disallow-node.js' {
  declare module.exports: $Exports<'react-markdown/lib/plugins/disallow-node'>;
}
declare module 'react-markdown/lib/plugins/naive-html.js' {
  declare module.exports: $Exports<'react-markdown/lib/plugins/naive-html'>;
}
declare module 'react-markdown/lib/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/lib/react-markdown'>;
}
declare module 'react-markdown/lib/renderers.js' {
  declare module.exports: $Exports<'react-markdown/lib/renderers'>;
}
declare module 'react-markdown/lib/uriTransformer.js' {
  declare module.exports: $Exports<'react-markdown/lib/uriTransformer'>;
}
declare module 'react-markdown/lib/wrap-table-rows.js' {
  declare module.exports: $Exports<'react-markdown/lib/wrap-table-rows'>;
}
declare module 'react-markdown/src/ast-to-react.js' {
  declare module.exports: $Exports<'react-markdown/src/ast-to-react'>;
}
declare module 'react-markdown/src/get-definitions.js' {
  declare module.exports: $Exports<'react-markdown/src/get-definitions'>;
}
declare module 'react-markdown/src/plugins/disallow-node.js' {
  declare module.exports: $Exports<'react-markdown/src/plugins/disallow-node'>;
}
declare module 'react-markdown/src/plugins/naive-html.js' {
  declare module.exports: $Exports<'react-markdown/src/plugins/naive-html'>;
}
declare module 'react-markdown/src/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/src/react-markdown'>;
}
declare module 'react-markdown/src/renderers.js' {
  declare module.exports: $Exports<'react-markdown/src/renderers'>;
}
declare module 'react-markdown/src/uriTransformer.js' {
  declare module.exports: $Exports<'react-markdown/src/uriTransformer'>;
}
declare module 'react-markdown/src/wrap-table-rows.js' {
  declare module.exports: $Exports<'react-markdown/src/wrap-table-rows'>;
}
declare module 'react-markdown/umd/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/umd/react-markdown'>;
}
declare module 'react-markdown/webpack.config.demo.js' {
  declare module.exports: $Exports<'react-markdown/webpack.config.demo'>;
}
declare module 'react-markdown/webpack.config.js' {
  declare module.exports: $Exports<'react-markdown/webpack.config'>;
}
