// flow-typed signature: b2e57725dbefc3fbf78a0e3c00570031
// flow-typed version: <<STUB>>/react-medium-image-zoom_v^3.0.10/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-medium-image-zoom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-medium-image-zoom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-medium-image-zoom/docs/app' {
  declare module.exports: any;
}

declare module 'react-medium-image-zoom/lib/defaults' {
  declare module.exports: any;
}

declare module 'react-medium-image-zoom/lib/EventsWrapper' {
  declare module.exports: any;
}

declare module 'react-medium-image-zoom/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-medium-image-zoom/lib/ImageZoom' {
  declare module.exports: any;
}

declare module 'react-medium-image-zoom/lib/index' {
  declare module.exports: any;
}

declare module 'react-medium-image-zoom/lib/keyboardEvents' {
  declare module.exports: any;
}

declare module 'react-medium-image-zoom/lib/Overlay' {
  declare module.exports: any;
}

declare module 'react-medium-image-zoom/lib/Zoom' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-medium-image-zoom/docs/app.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/docs/app'>;
}
declare module 'react-medium-image-zoom/index' {
  declare module.exports: $Exports<'react-medium-image-zoom'>;
}
declare module 'react-medium-image-zoom/index.js' {
  declare module.exports: $Exports<'react-medium-image-zoom'>;
}
declare module 'react-medium-image-zoom/lib/defaults.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/defaults'>;
}
declare module 'react-medium-image-zoom/lib/EventsWrapper.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/EventsWrapper'>;
}
declare module 'react-medium-image-zoom/lib/helpers.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/helpers'>;
}
declare module 'react-medium-image-zoom/lib/ImageZoom.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/ImageZoom'>;
}
declare module 'react-medium-image-zoom/lib/index.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/index'>;
}
declare module 'react-medium-image-zoom/lib/keyboardEvents.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/keyboardEvents'>;
}
declare module 'react-medium-image-zoom/lib/Overlay.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/Overlay'>;
}
declare module 'react-medium-image-zoom/lib/Zoom.js' {
  declare module.exports: $Exports<'react-medium-image-zoom/lib/Zoom'>;
}
