// flow-typed signature: 39f909e74e64eaf0770bcca744569611
// flow-typed version: <<STUB>>/react-waypoint_v^7.3.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-waypoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-waypoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-waypoint/cjs/index' {
  declare module.exports: any;
}

declare module 'react-waypoint/rollup.config' {
  declare module.exports: any;
}

declare module 'react-waypoint/webpack.config.performance-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-waypoint/cjs/index.js' {
  declare module.exports: $Exports<'react-waypoint/cjs/index'>;
}
declare module 'react-waypoint/rollup.config.js' {
  declare module.exports: $Exports<'react-waypoint/rollup.config'>;
}
declare module 'react-waypoint/webpack.config.performance-test.js' {
  declare module.exports: $Exports<'react-waypoint/webpack.config.performance-test'>;
}
