// flow-typed signature: 83d11d74aafca79519887b934bf9ec86
// flow-typed version: <<STUB>>/react-keydown_v^1.7.3/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-keydown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-keydown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-keydown/dist/decorators/class_decorator' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/decorators' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/decorators/method_decorator_scoped' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/decorators/method_decorator' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/event_handlers' {
  declare module.exports: any;
}

declare module 'react-keydown/dist' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/lib/array.from' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/lib/dom_helpers' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/lib/keys' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/lib/listeners' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/lib/match_keys' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/lib/parse_keys' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/lib/uuid' {
  declare module.exports: any;
}

declare module 'react-keydown/dist/store' {
  declare module.exports: any;
}

declare module 'react-keydown/es/decorators/class_decorator' {
  declare module.exports: any;
}

declare module 'react-keydown/es/decorators' {
  declare module.exports: any;
}

declare module 'react-keydown/es/decorators/method_decorator_scoped' {
  declare module.exports: any;
}

declare module 'react-keydown/es/decorators/method_decorator' {
  declare module.exports: any;
}

declare module 'react-keydown/es/event_handlers' {
  declare module.exports: any;
}

declare module 'react-keydown/es' {
  declare module.exports: any;
}

declare module 'react-keydown/es/lib/array.from' {
  declare module.exports: any;
}

declare module 'react-keydown/es/lib/dom_helpers' {
  declare module.exports: any;
}

declare module 'react-keydown/es/lib/keys' {
  declare module.exports: any;
}

declare module 'react-keydown/es/lib/listeners' {
  declare module.exports: any;
}

declare module 'react-keydown/es/lib/match_keys' {
  declare module.exports: any;
}

declare module 'react-keydown/es/lib/parse_keys' {
  declare module.exports: any;
}

declare module 'react-keydown/es/lib/uuid' {
  declare module.exports: any;
}

declare module 'react-keydown/es/store' {
  declare module.exports: any;
}

declare module 'react-keydown/example/public/js/app' {
  declare module.exports: any;
}

declare module 'react-keydown/example/public/prism' {
  declare module.exports: any;
}

declare module 'react-keydown/example/src/app/class_decorator/code' {
  declare module.exports: any;
}

declare module 'react-keydown/example/src/app/class_decorator' {
  declare module.exports: any;
}

declare module 'react-keydown/example/src/app' {
  declare module.exports: any;
}

declare module 'react-keydown/example/src/app/method_decorator/code' {
  declare module.exports: any;
}

declare module 'react-keydown/example/src/app/method_decorator' {
  declare module.exports: any;
}

declare module 'react-keydown/example/src' {
  declare module.exports: any;
}

declare module 'react-keydown/src/decorators/class_decorator' {
  declare module.exports: any;
}

declare module 'react-keydown/src/decorators' {
  declare module.exports: any;
}

declare module 'react-keydown/src/decorators/method_decorator_scoped' {
  declare module.exports: any;
}

declare module 'react-keydown/src/decorators/method_decorator' {
  declare module.exports: any;
}

declare module 'react-keydown/src/event_handlers' {
  declare module.exports: any;
}

declare module 'react-keydown/src' {
  declare module.exports: any;
}

declare module 'react-keydown/src/lib/array.from' {
  declare module.exports: any;
}

declare module 'react-keydown/src/lib/dom_helpers' {
  declare module.exports: any;
}

declare module 'react-keydown/src/lib/keys' {
  declare module.exports: any;
}

declare module 'react-keydown/src/lib/listeners' {
  declare module.exports: any;
}

declare module 'react-keydown/src/lib/match_keys' {
  declare module.exports: any;
}

declare module 'react-keydown/src/lib/parse_keys' {
  declare module.exports: any;
}

declare module 'react-keydown/src/lib/uuid' {
  declare module.exports: any;
}

declare module 'react-keydown/src/store' {
  declare module.exports: any;
}

declare module 'react-keydown/tests/event_handlers-test' {
  declare module.exports: any;
}

declare module 'react-keydown/tests/fixtures/event' {
  declare module.exports: any;
}

declare module 'react-keydown/tests/match_keys-test' {
  declare module.exports: any;
}

declare module 'react-keydown/tests/parse_keys-test' {
  declare module.exports: any;
}

declare module 'react-keydown/tests/store-test' {
  declare module.exports: any;
}

declare module 'react-keydown/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-keydown/dist/decorators/class_decorator.js' {
  declare module.exports: $Exports<'react-keydown/dist/decorators/class_decorator'>;
}
declare module 'react-keydown/dist/decorators/index' {
  declare module.exports: $Exports<'react-keydown/dist/decorators'>;
}
declare module 'react-keydown/dist/decorators/index.js' {
  declare module.exports: $Exports<'react-keydown/dist/decorators'>;
}
declare module 'react-keydown/dist/decorators/method_decorator_scoped.js' {
  declare module.exports: $Exports<'react-keydown/dist/decorators/method_decorator_scoped'>;
}
declare module 'react-keydown/dist/decorators/method_decorator.js' {
  declare module.exports: $Exports<'react-keydown/dist/decorators/method_decorator'>;
}
declare module 'react-keydown/dist/event_handlers.js' {
  declare module.exports: $Exports<'react-keydown/dist/event_handlers'>;
}
declare module 'react-keydown/dist/index' {
  declare module.exports: $Exports<'react-keydown/dist'>;
}
declare module 'react-keydown/dist/index.js' {
  declare module.exports: $Exports<'react-keydown/dist'>;
}
declare module 'react-keydown/dist/lib/array.from.js' {
  declare module.exports: $Exports<'react-keydown/dist/lib/array.from'>;
}
declare module 'react-keydown/dist/lib/dom_helpers.js' {
  declare module.exports: $Exports<'react-keydown/dist/lib/dom_helpers'>;
}
declare module 'react-keydown/dist/lib/keys.js' {
  declare module.exports: $Exports<'react-keydown/dist/lib/keys'>;
}
declare module 'react-keydown/dist/lib/listeners.js' {
  declare module.exports: $Exports<'react-keydown/dist/lib/listeners'>;
}
declare module 'react-keydown/dist/lib/match_keys.js' {
  declare module.exports: $Exports<'react-keydown/dist/lib/match_keys'>;
}
declare module 'react-keydown/dist/lib/parse_keys.js' {
  declare module.exports: $Exports<'react-keydown/dist/lib/parse_keys'>;
}
declare module 'react-keydown/dist/lib/uuid.js' {
  declare module.exports: $Exports<'react-keydown/dist/lib/uuid'>;
}
declare module 'react-keydown/dist/store.js' {
  declare module.exports: $Exports<'react-keydown/dist/store'>;
}
declare module 'react-keydown/es/decorators/class_decorator.js' {
  declare module.exports: $Exports<'react-keydown/es/decorators/class_decorator'>;
}
declare module 'react-keydown/es/decorators/index' {
  declare module.exports: $Exports<'react-keydown/es/decorators'>;
}
declare module 'react-keydown/es/decorators/index.js' {
  declare module.exports: $Exports<'react-keydown/es/decorators'>;
}
declare module 'react-keydown/es/decorators/method_decorator_scoped.js' {
  declare module.exports: $Exports<'react-keydown/es/decorators/method_decorator_scoped'>;
}
declare module 'react-keydown/es/decorators/method_decorator.js' {
  declare module.exports: $Exports<'react-keydown/es/decorators/method_decorator'>;
}
declare module 'react-keydown/es/event_handlers.js' {
  declare module.exports: $Exports<'react-keydown/es/event_handlers'>;
}
declare module 'react-keydown/es/index' {
  declare module.exports: $Exports<'react-keydown/es'>;
}
declare module 'react-keydown/es/index.js' {
  declare module.exports: $Exports<'react-keydown/es'>;
}
declare module 'react-keydown/es/lib/array.from.js' {
  declare module.exports: $Exports<'react-keydown/es/lib/array.from'>;
}
declare module 'react-keydown/es/lib/dom_helpers.js' {
  declare module.exports: $Exports<'react-keydown/es/lib/dom_helpers'>;
}
declare module 'react-keydown/es/lib/keys.js' {
  declare module.exports: $Exports<'react-keydown/es/lib/keys'>;
}
declare module 'react-keydown/es/lib/listeners.js' {
  declare module.exports: $Exports<'react-keydown/es/lib/listeners'>;
}
declare module 'react-keydown/es/lib/match_keys.js' {
  declare module.exports: $Exports<'react-keydown/es/lib/match_keys'>;
}
declare module 'react-keydown/es/lib/parse_keys.js' {
  declare module.exports: $Exports<'react-keydown/es/lib/parse_keys'>;
}
declare module 'react-keydown/es/lib/uuid.js' {
  declare module.exports: $Exports<'react-keydown/es/lib/uuid'>;
}
declare module 'react-keydown/es/store.js' {
  declare module.exports: $Exports<'react-keydown/es/store'>;
}
declare module 'react-keydown/example/public/js/app.js' {
  declare module.exports: $Exports<'react-keydown/example/public/js/app'>;
}
declare module 'react-keydown/example/public/prism.js' {
  declare module.exports: $Exports<'react-keydown/example/public/prism'>;
}
declare module 'react-keydown/example/src/app/class_decorator/code.js' {
  declare module.exports: $Exports<'react-keydown/example/src/app/class_decorator/code'>;
}
declare module 'react-keydown/example/src/app/class_decorator/index' {
  declare module.exports: $Exports<'react-keydown/example/src/app/class_decorator'>;
}
declare module 'react-keydown/example/src/app/class_decorator/index.js' {
  declare module.exports: $Exports<'react-keydown/example/src/app/class_decorator'>;
}
declare module 'react-keydown/example/src/app/index' {
  declare module.exports: $Exports<'react-keydown/example/src/app'>;
}
declare module 'react-keydown/example/src/app/index.js' {
  declare module.exports: $Exports<'react-keydown/example/src/app'>;
}
declare module 'react-keydown/example/src/app/method_decorator/code.js' {
  declare module.exports: $Exports<'react-keydown/example/src/app/method_decorator/code'>;
}
declare module 'react-keydown/example/src/app/method_decorator/index' {
  declare module.exports: $Exports<'react-keydown/example/src/app/method_decorator'>;
}
declare module 'react-keydown/example/src/app/method_decorator/index.js' {
  declare module.exports: $Exports<'react-keydown/example/src/app/method_decorator'>;
}
declare module 'react-keydown/example/src/index' {
  declare module.exports: $Exports<'react-keydown/example/src'>;
}
declare module 'react-keydown/example/src/index.js' {
  declare module.exports: $Exports<'react-keydown/example/src'>;
}
declare module 'react-keydown/src/decorators/class_decorator.js' {
  declare module.exports: $Exports<'react-keydown/src/decorators/class_decorator'>;
}
declare module 'react-keydown/src/decorators/index' {
  declare module.exports: $Exports<'react-keydown/src/decorators'>;
}
declare module 'react-keydown/src/decorators/index.js' {
  declare module.exports: $Exports<'react-keydown/src/decorators'>;
}
declare module 'react-keydown/src/decorators/method_decorator_scoped.js' {
  declare module.exports: $Exports<'react-keydown/src/decorators/method_decorator_scoped'>;
}
declare module 'react-keydown/src/decorators/method_decorator.js' {
  declare module.exports: $Exports<'react-keydown/src/decorators/method_decorator'>;
}
declare module 'react-keydown/src/event_handlers.js' {
  declare module.exports: $Exports<'react-keydown/src/event_handlers'>;
}
declare module 'react-keydown/src/index' {
  declare module.exports: $Exports<'react-keydown/src'>;
}
declare module 'react-keydown/src/index.js' {
  declare module.exports: $Exports<'react-keydown/src'>;
}
declare module 'react-keydown/src/lib/array.from.js' {
  declare module.exports: $Exports<'react-keydown/src/lib/array.from'>;
}
declare module 'react-keydown/src/lib/dom_helpers.js' {
  declare module.exports: $Exports<'react-keydown/src/lib/dom_helpers'>;
}
declare module 'react-keydown/src/lib/keys.js' {
  declare module.exports: $Exports<'react-keydown/src/lib/keys'>;
}
declare module 'react-keydown/src/lib/listeners.js' {
  declare module.exports: $Exports<'react-keydown/src/lib/listeners'>;
}
declare module 'react-keydown/src/lib/match_keys.js' {
  declare module.exports: $Exports<'react-keydown/src/lib/match_keys'>;
}
declare module 'react-keydown/src/lib/parse_keys.js' {
  declare module.exports: $Exports<'react-keydown/src/lib/parse_keys'>;
}
declare module 'react-keydown/src/lib/uuid.js' {
  declare module.exports: $Exports<'react-keydown/src/lib/uuid'>;
}
declare module 'react-keydown/src/store.js' {
  declare module.exports: $Exports<'react-keydown/src/store'>;
}
declare module 'react-keydown/tests/event_handlers-test.js' {
  declare module.exports: $Exports<'react-keydown/tests/event_handlers-test'>;
}
declare module 'react-keydown/tests/fixtures/event.js' {
  declare module.exports: $Exports<'react-keydown/tests/fixtures/event'>;
}
declare module 'react-keydown/tests/match_keys-test.js' {
  declare module.exports: $Exports<'react-keydown/tests/match_keys-test'>;
}
declare module 'react-keydown/tests/parse_keys-test.js' {
  declare module.exports: $Exports<'react-keydown/tests/parse_keys-test'>;
}
declare module 'react-keydown/tests/store-test.js' {
  declare module.exports: $Exports<'react-keydown/tests/store-test'>;
}
declare module 'react-keydown/webpack.config.js' {
  declare module.exports: $Exports<'react-keydown/webpack.config'>;
}
