// flow-typed signature: a79ed2c6a1de7304f17e06ece0d9e40c
// flow-typed version: <<STUB>>/react-dropzone_v3.6.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dropzone/dist/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/mocha-environment' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/index' {
  declare module.exports: any;
}

declare module 'react-dropzone/src/test' {
  declare module.exports: any;
}

declare module 'react-dropzone/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dropzone/dist/index.js' {
  declare module.exports: $Exports<'react-dropzone/dist/index'>;
}
declare module 'react-dropzone/mocha-environment.js' {
  declare module.exports: $Exports<'react-dropzone/mocha-environment'>;
}
declare module 'react-dropzone/src/index.js' {
  declare module.exports: $Exports<'react-dropzone/src/index'>;
}
declare module 'react-dropzone/src/test.js' {
  declare module.exports: $Exports<'react-dropzone/src/test'>;
}
declare module 'react-dropzone/webpack.config.js' {
  declare module.exports: $Exports<'react-dropzone/webpack.config'>;
}
