// flow-typed signature: 189e4b922f086cb6e0f8f7ff74e13e05
// flow-typed version: <<STUB>>/redis-lock_v^0.1.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redis-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redis-lock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redis-lock/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redis-lock/index' {
  declare module.exports: $Exports<'redis-lock'>;
}
declare module 'redis-lock/index.js' {
  declare module.exports: $Exports<'redis-lock'>;
}
declare module 'redis-lock/test/test.js' {
  declare module.exports: $Exports<'redis-lock/test/test'>;
}
