// flow-typed signature: 849627385e3d26a9aa753345ebf634c1
// flow-typed version: <<STUB>>/redis_v^2.6.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redis/lib/command' {
  declare module.exports: any;
}

declare module 'redis/lib/commands' {
  declare module.exports: any;
}

declare module 'redis/lib/createClient' {
  declare module.exports: any;
}

declare module 'redis/lib/customErrors' {
  declare module.exports: any;
}

declare module 'redis/lib/debug' {
  declare module.exports: any;
}

declare module 'redis/lib/extendedApi' {
  declare module.exports: any;
}

declare module 'redis/lib/individualCommands' {
  declare module.exports: any;
}

declare module 'redis/lib/multi' {
  declare module.exports: any;
}

declare module 'redis/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redis/index' {
  declare module.exports: $Exports<'redis'>;
}
declare module 'redis/index.js' {
  declare module.exports: $Exports<'redis'>;
}
declare module 'redis/lib/command.js' {
  declare module.exports: $Exports<'redis/lib/command'>;
}
declare module 'redis/lib/commands.js' {
  declare module.exports: $Exports<'redis/lib/commands'>;
}
declare module 'redis/lib/createClient.js' {
  declare module.exports: $Exports<'redis/lib/createClient'>;
}
declare module 'redis/lib/customErrors.js' {
  declare module.exports: $Exports<'redis/lib/customErrors'>;
}
declare module 'redis/lib/debug.js' {
  declare module.exports: $Exports<'redis/lib/debug'>;
}
declare module 'redis/lib/extendedApi.js' {
  declare module.exports: $Exports<'redis/lib/extendedApi'>;
}
declare module 'redis/lib/individualCommands.js' {
  declare module.exports: $Exports<'redis/lib/individualCommands'>;
}
declare module 'redis/lib/multi.js' {
  declare module.exports: $Exports<'redis/lib/multi'>;
}
declare module 'redis/lib/utils.js' {
  declare module.exports: $Exports<'redis/lib/utils'>;
}
