// flow-typed signature: 5b6ece64f471017b2f670f28e1dfeb64
// flow-typed version: <<STUB>>/safestart_v1.1.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'safestart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'safestart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'safestart/git_dependency_match' {
  declare module.exports: any;
}

declare module 'safestart/test/git_dependency_match' {
  declare module.exports: any;
}

declare module 'safestart/test/self' {
  declare module.exports: any;
}

// Filename aliases
declare module 'safestart/git_dependency_match.js' {
  declare module.exports: $Exports<'safestart/git_dependency_match'>;
}
declare module 'safestart/index' {
  declare module.exports: $Exports<'safestart'>;
}
declare module 'safestart/index.js' {
  declare module.exports: $Exports<'safestart'>;
}
declare module 'safestart/test/git_dependency_match.js' {
  declare module.exports: $Exports<'safestart/test/git_dependency_match'>;
}
declare module 'safestart/test/self.js' {
  declare module.exports: $Exports<'safestart/test/self'>;
}
