// flow-typed signature: 0c893165f0eaff8d04ce05629cdb5482
// flow-typed version: <<STUB>>/slate-prism_v^0.5.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-prism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-prism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-prism/dist/index' {
  declare module.exports: any;
}

declare module 'slate-prism/dist/options' {
  declare module.exports: any;
}

declare module 'slate-prism/dist/TOKEN_MARK' {
  declare module.exports: any;
}

declare module 'slate-prism/example/bundle' {
  declare module.exports: any;
}

declare module 'slate-prism/example/main' {
  declare module.exports: any;
}

declare module 'slate-prism/example/value' {
  declare module.exports: any;
}

declare module 'slate-prism/lib/index' {
  declare module.exports: any;
}

declare module 'slate-prism/lib/options' {
  declare module.exports: any;
}

declare module 'slate-prism/lib/TOKEN_MARK' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-prism/dist/index.js' {
  declare module.exports: $Exports<'slate-prism/dist/index'>;
}
declare module 'slate-prism/dist/options.js' {
  declare module.exports: $Exports<'slate-prism/dist/options'>;
}
declare module 'slate-prism/dist/TOKEN_MARK.js' {
  declare module.exports: $Exports<'slate-prism/dist/TOKEN_MARK'>;
}
declare module 'slate-prism/example/bundle.js' {
  declare module.exports: $Exports<'slate-prism/example/bundle'>;
}
declare module 'slate-prism/example/main.js' {
  declare module.exports: $Exports<'slate-prism/example/main'>;
}
declare module 'slate-prism/example/value.js' {
  declare module.exports: $Exports<'slate-prism/example/value'>;
}
declare module 'slate-prism/lib/index.js' {
  declare module.exports: $Exports<'slate-prism/lib/index'>;
}
declare module 'slate-prism/lib/options.js' {
  declare module.exports: $Exports<'slate-prism/lib/options'>;
}
declare module 'slate-prism/lib/TOKEN_MARK.js' {
  declare module.exports: $Exports<'slate-prism/lib/TOKEN_MARK'>;
}
