// flow-typed signature: 3342867a1417391927859a9c905d5366
// flow-typed version: <<STUB>>/slate_v^0.32.5/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate/dist/slate' {
  declare module.exports: any;
}

declare module 'slate/dist/slate.min' {
  declare module.exports: any;
}

declare module 'slate/lib/slate.es' {
  declare module.exports: any;
}

declare module 'slate/lib/slate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate/dist/slate.js' {
  declare module.exports: $Exports<'slate/dist/slate'>;
}
declare module 'slate/dist/slate.min.js' {
  declare module.exports: $Exports<'slate/dist/slate.min'>;
}
declare module 'slate/lib/slate.es.js' {
  declare module.exports: $Exports<'slate/lib/slate.es'>;
}
declare module 'slate/lib/slate.js' {
  declare module.exports: $Exports<'slate/lib/slate'>;
}
