// flow-typed signature: e35e89af8873cd5bae364d5238ccc4d9
// flow-typed version: <<STUB>>/string-replace-to-array_v^1.0.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-replace-to-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-replace-to-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string-replace-to-array/string-replace-to-array' {
  declare module.exports: any;
}

declare module 'string-replace-to-array/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string-replace-to-array/string-replace-to-array.js' {
  declare module.exports: $Exports<'string-replace-to-array/string-replace-to-array'>;
}
declare module 'string-replace-to-array/test.js' {
  declare module.exports: $Exports<'string-replace-to-array/test'>;
}
