// flow-typed signature: 8c9ecb5481ebe97f283678da6aa050db
// flow-typed version: <<STUB>>/string-hash_v^1.1.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string-hash/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string-hash/index' {
  declare module.exports: $Exports<'string-hash'>;
}
declare module 'string-hash/index.js' {
  declare module.exports: $Exports<'string-hash'>;
}
declare module 'string-hash/test.js' {
  declare module.exports: $Exports<'string-hash/test'>;
}
