// flow-typed signature: 04c6b5a073e3f6e139d773f3fa779b3f
// flow-typed version: <<STUB>>/style-loader_v^0.18.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-loader/lib/addStyles' {
  declare module.exports: any;
}

declare module 'style-loader/lib/addStyleUrl' {
  declare module.exports: any;
}

declare module 'style-loader/lib/urls' {
  declare module.exports: any;
}

declare module 'style-loader/url' {
  declare module.exports: any;
}

declare module 'style-loader/useable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-loader/index' {
  declare module.exports: $Exports<'style-loader'>;
}
declare module 'style-loader/index.js' {
  declare module.exports: $Exports<'style-loader'>;
}
declare module 'style-loader/lib/addStyles.js' {
  declare module.exports: $Exports<'style-loader/lib/addStyles'>;
}
declare module 'style-loader/lib/addStyleUrl.js' {
  declare module.exports: $Exports<'style-loader/lib/addStyleUrl'>;
}
declare module 'style-loader/lib/urls.js' {
  declare module.exports: $Exports<'style-loader/lib/urls'>;
}
declare module 'style-loader/url.js' {
  declare module.exports: $Exports<'style-loader/url'>;
}
declare module 'style-loader/useable.js' {
  declare module.exports: $Exports<'style-loader/useable'>;
}
