// flow-typed signature: b525340c11483ee196c00be38c191009
// flow-typed version: <<STUB>>/tiny-cookie_v^2.3.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tiny-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tiny-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tiny-cookie/dist/tiny-cookie' {
  declare module.exports: any;
}

declare module 'tiny-cookie/dist/tiny-cookie.min' {
  declare module.exports: any;
}

declare module 'tiny-cookie/es' {
  declare module.exports: any;
}

declare module 'tiny-cookie/es/util' {
  declare module.exports: any;
}

declare module 'tiny-cookie/flow' {
  declare module.exports: any;
}

declare module 'tiny-cookie/lib' {
  declare module.exports: any;
}

declare module 'tiny-cookie/lib/util' {
  declare module.exports: any;
}

declare module 'tiny-cookie/src' {
  declare module.exports: any;
}

declare module 'tiny-cookie/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tiny-cookie/dist/tiny-cookie.js' {
  declare module.exports: $Exports<'tiny-cookie/dist/tiny-cookie'>;
}
declare module 'tiny-cookie/dist/tiny-cookie.min.js' {
  declare module.exports: $Exports<'tiny-cookie/dist/tiny-cookie.min'>;
}
declare module 'tiny-cookie/es/index' {
  declare module.exports: $Exports<'tiny-cookie/es'>;
}
declare module 'tiny-cookie/es/index.js' {
  declare module.exports: $Exports<'tiny-cookie/es'>;
}
declare module 'tiny-cookie/es/util.js' {
  declare module.exports: $Exports<'tiny-cookie/es/util'>;
}
declare module 'tiny-cookie/flow/index' {
  declare module.exports: $Exports<'tiny-cookie/flow'>;
}
declare module 'tiny-cookie/flow/index.js' {
  declare module.exports: $Exports<'tiny-cookie/flow'>;
}
declare module 'tiny-cookie/lib/index' {
  declare module.exports: $Exports<'tiny-cookie/lib'>;
}
declare module 'tiny-cookie/lib/index.js' {
  declare module.exports: $Exports<'tiny-cookie/lib'>;
}
declare module 'tiny-cookie/lib/util.js' {
  declare module.exports: $Exports<'tiny-cookie/lib/util'>;
}
declare module 'tiny-cookie/src/index' {
  declare module.exports: $Exports<'tiny-cookie/src'>;
}
declare module 'tiny-cookie/src/index.js' {
  declare module.exports: $Exports<'tiny-cookie/src'>;
}
declare module 'tiny-cookie/src/util.js' {
  declare module.exports: $Exports<'tiny-cookie/src/util'>;
}
