// flow-typed signature: 6242762666c84f2b4d6ccae876aeef95
// flow-typed version: <<STUB>>/truncate-html_vhttps://github.com/jorilallo/truncate-html/tarball/master/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'truncate-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'truncate-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'truncate-html/lib/truncate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'truncate-html/lib/truncate.js' {
  declare module.exports: $Exports<'truncate-html/lib/truncate'>;
}
