// flow-typed signature: 2db53ec5dbb577a4e27bc465cd4670f3
// flow-typed version: <<STUB>>/y-prosemirror_v^0.3.7/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'y-prosemirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'y-prosemirror' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'y-prosemirror/dist/test' {
  declare module.exports: any;
}

declare module 'y-prosemirror/src/lib' {
  declare module.exports: any;
}

declare module 'y-prosemirror/src/plugins/cursor-plugin' {
  declare module.exports: any;
}

declare module 'y-prosemirror/src/plugins/sync-plugin' {
  declare module.exports: any;
}

declare module 'y-prosemirror/src/plugins/undo-plugin' {
  declare module.exports: any;
}

declare module 'y-prosemirror/src/y-prosemirror' {
  declare module.exports: any;
}

// Filename aliases
declare module 'y-prosemirror/dist/test.js' {
  declare module.exports: $Exports<'y-prosemirror/dist/test'>;
}
declare module 'y-prosemirror/src/lib.js' {
  declare module.exports: $Exports<'y-prosemirror/src/lib'>;
}
declare module 'y-prosemirror/src/plugins/cursor-plugin.js' {
  declare module.exports: $Exports<'y-prosemirror/src/plugins/cursor-plugin'>;
}
declare module 'y-prosemirror/src/plugins/sync-plugin.js' {
  declare module.exports: $Exports<'y-prosemirror/src/plugins/sync-plugin'>;
}
declare module 'y-prosemirror/src/plugins/undo-plugin.js' {
  declare module.exports: $Exports<'y-prosemirror/src/plugins/undo-plugin'>;
}
declare module 'y-prosemirror/src/y-prosemirror.js' {
  declare module.exports: $Exports<'y-prosemirror/src/y-prosemirror'>;
}
