// flow-typed signature: 3ef5e4dd42591ff15af5f507abd6aa97
// flow-typed version: <<STUB>>/y-protocols_v^1.0.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'y-protocols'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

// @flow
declare module "y-protocols" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "y-protocols/auth" {
  declare module.exports: any;
}

declare module "y-protocols/awareness" {
  declare module.exports: any;
}

declare module "y-protocols/awareness.test" {
  declare module.exports: any;
}

declare module "y-protocols/dist/test" {
  declare module.exports: any;
}

declare module "y-protocols/sync" {
  declare module.exports: any;
}

// Filename aliases
declare module "y-protocols/auth.js" {
  declare module.exports: $Exports<"y-protocols/auth">;
}
declare module "y-protocols/awareness.js" {
  declare module.exports: $Exports<"y-protocols/awareness">;
}
declare module "y-protocols/dist/awareness.cjs" {
  declare module.exports: $Exports<"y-protocols/awareness">;
}
declare module "y-protocols/awareness.test.js" {
  declare module.exports: $Exports<"y-protocols/awareness.test">;
}
declare module "y-protocols/dist/test.js" {
  declare module.exports: $Exports<"y-protocols/dist/test">;
}
declare module "y-protocols/sync.js" {
  declare module.exports: $Exports<"y-protocols/sync">;
}
declare module "y-protocols/dist/sync.cjs" {
  declare module.exports: $Exports<"y-protocols/sync">;
}
