// flow-typed signature: ec89eac307897bef104c76ce1dd14a4d
// flow-typed version: <<STUB>>/yjs_v^13.4.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yjs/dist/tests' {
  declare module.exports: any;
}

declare module 'yjs/docs/scripts/jquery.min' {
  declare module.exports: any;
}

declare module 'yjs/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'yjs/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'yjs/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'yjs/docs/scripts/tui-doc' {
  declare module.exports: any;
}

declare module 'yjs/src' {
  declare module.exports: any;
}

declare module 'yjs/src/internals' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/AbstractStruct' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentAny' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentBinary' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentDeleted' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentDoc' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentEmbed' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentFormat' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentJSON' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentString' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/ContentType' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/GC' {
  declare module.exports: any;
}

declare module 'yjs/src/structs/Item' {
  declare module.exports: any;
}

declare module 'yjs/src/types/AbstractType' {
  declare module.exports: any;
}

declare module 'yjs/src/types/YArray' {
  declare module.exports: any;
}

declare module 'yjs/src/types/YMap' {
  declare module.exports: any;
}

declare module 'yjs/src/types/YText' {
  declare module.exports: any;
}

declare module 'yjs/src/types/YXmlElement' {
  declare module.exports: any;
}

declare module 'yjs/src/types/YXmlEvent' {
  declare module.exports: any;
}

declare module 'yjs/src/types/YXmlFragment' {
  declare module.exports: any;
}

declare module 'yjs/src/types/YXmlHook' {
  declare module.exports: any;
}

declare module 'yjs/src/types/YXmlText' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/AbstractConnector' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/DeleteSet' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/Doc' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/encoding' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/EventHandler' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/ID' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/isParentOf' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/logging' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/PermanentUserData' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/RelativePosition' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/Snapshot' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/StructStore' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/Transaction' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/UndoManager' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/UpdateDecoder' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/UpdateEncoder' {
  declare module.exports: any;
}

declare module 'yjs/src/utils/YEvent' {
  declare module.exports: any;
}

declare module 'yjs/tests/compatibility.tests' {
  declare module.exports: any;
}

declare module 'yjs/tests/doc.tests' {
  declare module.exports: any;
}

declare module 'yjs/tests/encoding.tests' {
  declare module.exports: any;
}

declare module 'yjs/tests' {
  declare module.exports: any;
}

declare module 'yjs/tests/snapshot.tests' {
  declare module.exports: any;
}

declare module 'yjs/tests/testHelper' {
  declare module.exports: any;
}

declare module 'yjs/tests/undo-redo.tests' {
  declare module.exports: any;
}

declare module 'yjs/tests/y-array.tests' {
  declare module.exports: any;
}

declare module 'yjs/tests/y-map.tests' {
  declare module.exports: any;
}

declare module 'yjs/tests/y-text.tests' {
  declare module.exports: any;
}

declare module 'yjs/tests/y-xml.tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yjs/dist/tests.js' {
  declare module.exports: $Exports<'yjs/dist/tests'>;
}
declare module 'yjs/docs/scripts/jquery.min.js' {
  declare module.exports: $Exports<'yjs/docs/scripts/jquery.min'>;
}
declare module 'yjs/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'yjs/docs/scripts/linenumber'>;
}
declare module 'yjs/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'yjs/docs/scripts/prettify/lang-css'>;
}
declare module 'yjs/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'yjs/docs/scripts/prettify/prettify'>;
}
declare module 'yjs/docs/scripts/tui-doc.js' {
  declare module.exports: $Exports<'yjs/docs/scripts/tui-doc'>;
}
declare module 'yjs/src/index' {
  declare module.exports: $Exports<'yjs/src'>;
}
declare module 'yjs/src/index.js' {
  declare module.exports: $Exports<'yjs/src'>;
}
declare module 'yjs/src/internals.js' {
  declare module.exports: $Exports<'yjs/src/internals'>;
}
declare module 'yjs/src/structs/AbstractStruct.js' {
  declare module.exports: $Exports<'yjs/src/structs/AbstractStruct'>;
}
declare module 'yjs/src/structs/ContentAny.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentAny'>;
}
declare module 'yjs/src/structs/ContentBinary.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentBinary'>;
}
declare module 'yjs/src/structs/ContentDeleted.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentDeleted'>;
}
declare module 'yjs/src/structs/ContentDoc.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentDoc'>;
}
declare module 'yjs/src/structs/ContentEmbed.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentEmbed'>;
}
declare module 'yjs/src/structs/ContentFormat.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentFormat'>;
}
declare module 'yjs/src/structs/ContentJSON.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentJSON'>;
}
declare module 'yjs/src/structs/ContentString.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentString'>;
}
declare module 'yjs/src/structs/ContentType.js' {
  declare module.exports: $Exports<'yjs/src/structs/ContentType'>;
}
declare module 'yjs/src/structs/GC.js' {
  declare module.exports: $Exports<'yjs/src/structs/GC'>;
}
declare module 'yjs/src/structs/Item.js' {
  declare module.exports: $Exports<'yjs/src/structs/Item'>;
}
declare module 'yjs/src/types/AbstractType.js' {
  declare module.exports: $Exports<'yjs/src/types/AbstractType'>;
}
declare module 'yjs/src/types/YArray.js' {
  declare module.exports: $Exports<'yjs/src/types/YArray'>;
}
declare module 'yjs/src/types/YMap.js' {
  declare module.exports: $Exports<'yjs/src/types/YMap'>;
}
declare module 'yjs/src/types/YText.js' {
  declare module.exports: $Exports<'yjs/src/types/YText'>;
}
declare module 'yjs/src/types/YXmlElement.js' {
  declare module.exports: $Exports<'yjs/src/types/YXmlElement'>;
}
declare module 'yjs/src/types/YXmlEvent.js' {
  declare module.exports: $Exports<'yjs/src/types/YXmlEvent'>;
}
declare module 'yjs/src/types/YXmlFragment.js' {
  declare module.exports: $Exports<'yjs/src/types/YXmlFragment'>;
}
declare module 'yjs/src/types/YXmlHook.js' {
  declare module.exports: $Exports<'yjs/src/types/YXmlHook'>;
}
declare module 'yjs/src/types/YXmlText.js' {
  declare module.exports: $Exports<'yjs/src/types/YXmlText'>;
}
declare module 'yjs/src/utils/AbstractConnector.js' {
  declare module.exports: $Exports<'yjs/src/utils/AbstractConnector'>;
}
declare module 'yjs/src/utils/DeleteSet.js' {
  declare module.exports: $Exports<'yjs/src/utils/DeleteSet'>;
}
declare module 'yjs/src/utils/Doc.js' {
  declare module.exports: $Exports<'yjs/src/utils/Doc'>;
}
declare module 'yjs/src/utils/encoding.js' {
  declare module.exports: $Exports<'yjs/src/utils/encoding'>;
}
declare module 'yjs/src/utils/EventHandler.js' {
  declare module.exports: $Exports<'yjs/src/utils/EventHandler'>;
}
declare module 'yjs/src/utils/ID.js' {
  declare module.exports: $Exports<'yjs/src/utils/ID'>;
}
declare module 'yjs/src/utils/isParentOf.js' {
  declare module.exports: $Exports<'yjs/src/utils/isParentOf'>;
}
declare module 'yjs/src/utils/logging.js' {
  declare module.exports: $Exports<'yjs/src/utils/logging'>;
}
declare module 'yjs/src/utils/PermanentUserData.js' {
  declare module.exports: $Exports<'yjs/src/utils/PermanentUserData'>;
}
declare module 'yjs/src/utils/RelativePosition.js' {
  declare module.exports: $Exports<'yjs/src/utils/RelativePosition'>;
}
declare module 'yjs/src/utils/Snapshot.js' {
  declare module.exports: $Exports<'yjs/src/utils/Snapshot'>;
}
declare module 'yjs/src/utils/StructStore.js' {
  declare module.exports: $Exports<'yjs/src/utils/StructStore'>;
}
declare module 'yjs/src/utils/Transaction.js' {
  declare module.exports: $Exports<'yjs/src/utils/Transaction'>;
}
declare module 'yjs/src/utils/UndoManager.js' {
  declare module.exports: $Exports<'yjs/src/utils/UndoManager'>;
}
declare module 'yjs/src/utils/UpdateDecoder.js' {
  declare module.exports: $Exports<'yjs/src/utils/UpdateDecoder'>;
}
declare module 'yjs/src/utils/UpdateEncoder.js' {
  declare module.exports: $Exports<'yjs/src/utils/UpdateEncoder'>;
}
declare module 'yjs/src/utils/YEvent.js' {
  declare module.exports: $Exports<'yjs/src/utils/YEvent'>;
}
declare module 'yjs/tests/compatibility.tests.js' {
  declare module.exports: $Exports<'yjs/tests/compatibility.tests'>;
}
declare module 'yjs/tests/doc.tests.js' {
  declare module.exports: $Exports<'yjs/tests/doc.tests'>;
}
declare module 'yjs/tests/encoding.tests.js' {
  declare module.exports: $Exports<'yjs/tests/encoding.tests'>;
}
declare module 'yjs/tests/index' {
  declare module.exports: $Exports<'yjs/tests'>;
}
declare module 'yjs/tests/index.js' {
  declare module.exports: $Exports<'yjs/tests'>;
}
declare module 'yjs/tests/snapshot.tests.js' {
  declare module.exports: $Exports<'yjs/tests/snapshot.tests'>;
}
declare module 'yjs/tests/testHelper.js' {
  declare module.exports: $Exports<'yjs/tests/testHelper'>;
}
declare module 'yjs/tests/undo-redo.tests.js' {
  declare module.exports: $Exports<'yjs/tests/undo-redo.tests'>;
}
declare module 'yjs/tests/y-array.tests.js' {
  declare module.exports: $Exports<'yjs/tests/y-array.tests'>;
}
declare module 'yjs/tests/y-map.tests.js' {
  declare module.exports: $Exports<'yjs/tests/y-map.tests'>;
}
declare module 'yjs/tests/y-text.tests.js' {
  declare module.exports: $Exports<'yjs/tests/y-text.tests'>;
}
declare module 'yjs/tests/y-xml.tests.js' {
  declare module.exports: $Exports<'yjs/tests/y-xml.tests'>;
}
