// flow-typed signature: f0829e2354f9018de48c2d40fc24383f
// flow-typed version: <<STUB>>/@babel/plugin-transform-regenerator_v^7.10.4/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-regenerator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-regenerator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-regenerator/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-regenerator/lib/index' {
  declare module.exports: $Exports<'@babel/plugin-transform-regenerator/lib'>;
}
declare module '@babel/plugin-transform-regenerator/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-regenerator/lib'>;
}
