/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedBoardingsRouteImport } from './routes/_authenticated/boardings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGroomingRouteImport } from './routes/_authenticated/grooming'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedLoyaltyRouteImport } from './routes/_authenticated/loyalty'
import { Route as AuthenticatedOccupancyRouteImport } from './routes/_authenticated/occupancy'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsAccountingRouteImport } from './routes/docs/accounting'
import { Route as DocsAuthRouteImport } from './routes/docs/auth'
import { Route as DocsBoardingRouteImport } from './routes/docs/boarding'
import { Route as DocsBranchesRouteImport } from './routes/docs/branches'
import { Route as DocsDashboardRouteImport } from './routes/docs/dashboard'
import { Route as DocsLoyaltyRouteImport } from './routes/docs/loyalty'
import { Route as DocsPosRouteImport } from './routes/docs/pos'
import { Route as DocsProductsRouteImport } from './routes/docs/products'
import { Route as DocsStaffRouteImport } from './routes/docs/staff'
import { Route as DocsWhatsappRouteImport } from './routes/docs/whatsapp'
import { Route as AuthenticatedAccountingIndexRouteImport } from './routes/_authenticated/accounting.index'
import { Route as AuthenticatedAccountingAttendanceRouteImport } from './routes/_authenticated/accounting.attendance'
import { Route as AuthenticatedAccountingCommissionsRouteImport } from './routes/_authenticated/accounting.commissions'
import { Route as AuthenticatedAccountingExpensesRouteImport } from './routes/_authenticated/accounting.expenses'
import { Route as AuthenticatedAccountingJournalRouteImport } from './routes/_authenticated/accounting.journal'
import { Route as AuthenticatedAccountingPettycashRouteImport } from './routes/_authenticated/accounting.pettycash'
import { Route as AuthenticatedAccountingReportsRouteImport } from './routes/_authenticated/accounting.reports'
import { Route as AuthenticatedBoardingsIndexRouteImport } from './routes/_authenticated/boardings.index'
import { Route as AuthenticatedBoardingsIdRouteImport } from './routes/_authenticated/boardings.$id'
import { Route as AuthenticatedBoardingsNewRouteImport } from './routes/_authenticated/boardings.new'
import { Route as AuthenticatedBranchesIndexRouteImport } from './routes/_authenticated/branches.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedGroomingIndexRouteImport } from './routes/_authenticated/grooming.index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory.index'
import { Route as AuthenticatedInventoryBatchesRouteImport } from './routes/_authenticated/inventory.batches'
import { Route as AuthenticatedInventoryMovementsRouteImport } from './routes/_authenticated/inventory.movements'
import { Route as AuthenticatedInventoryWarehousesRouteImport } from './routes/_authenticated/inventory.warehouses'
import { Route as AuthenticatedInvoicesInvoiceIdRouteImport } from './routes/_authenticated/invoices/$invoiceId'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedProfilePreferencesRouteImport } from './routes/_authenticated/profile.preferences'
import { Route as AuthenticatedProfileSecurityRouteImport } from './routes/_authenticated/profile.security'
import { Route as AuthenticatedPurchaseOrdersIdRouteImport } from './routes/_authenticated/purchase-orders.$id'
import { Route as AuthenticatedPurchaseOrdersNewRouteImport } from './routes/_authenticated/purchase-orders.new'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings.billing'
import { Route as AuthenticatedSettingsDocumentsRouteImport } from './routes/_authenticated/settings.documents'
import { Route as AuthenticatedSettingsReceiptsRouteImport } from './routes/_authenticated/settings.receipts'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff.$staffId'
import { Route as DocsStoriesAuthRouteImport } from './routes/docs/stories/auth'
import { Route as DocsStoriesBoardingRouteImport } from './routes/docs/stories/boarding'
import { Route as DocsStoriesBranchesRouteImport } from './routes/docs/stories/branches'
import { Route as PBusinessSlugBoardingRouteImport } from './routes/p.$businessSlug.boarding'
import { Route as PBusinessSlugBookingRouteImport } from './routes/p.$businessSlug.booking'
import { Route as PBusinessSlugFeaturedRouteImport } from './routes/p.$businessSlug.featured'
import { Route as AuthenticatedBranchesBranchIdRoomsRouteImport } from './routes/_authenticated/branches.$branchId.rooms'
import { Route as PBusinessIdProductsProductIdRouteImport } from './routes/p.$businessId.products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBoardingsRoute = AuthenticatedBoardingsRouteImport.update({
  id: '/boardings',
  path: '/boardings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroomingRoute = AuthenticatedGroomingRouteImport.update({
  id: '/grooming',
  path: '/grooming',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoyaltyRoute = AuthenticatedLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOccupancyRoute = AuthenticatedOccupancyRouteImport.update({
  id: '/occupancy',
  path: '/occupancy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAccountingRoute = DocsAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAuthRoute = DocsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBoardingRoute = DocsBoardingRouteImport.update({
  id: '/boarding',
  path: '/boarding',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBranchesRoute = DocsBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDashboardRoute = DocsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLoyaltyRoute = DocsLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPosRoute = DocsPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProductsRoute = DocsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DocsRoute,
} as any)
const DocsStaffRoute = DocsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWhatsappRoute = DocsWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DocsRoute,
} as any)
const AuthenticatedAccountingIndexRoute =
  AuthenticatedAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingAttendanceRoute =
  AuthenticatedAccountingAttendanceRouteImport.update({
    id: '/accounting/attendance',
    path: '/accounting/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingCommissionsRoute =
  AuthenticatedAccountingCommissionsRouteImport.update({
    id: '/accounting/commissions',
    path: '/accounting/commissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingExpensesRoute =
  AuthenticatedAccountingExpensesRouteImport.update({
    id: '/accounting/expenses',
    path: '/accounting/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingJournalRoute =
  AuthenticatedAccountingJournalRouteImport.update({
    id: '/accounting/journal',
    path: '/accounting/journal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingPettycashRoute =
  AuthenticatedAccountingPettycashRouteImport.update({
    id: '/accounting/pettycash',
    path: '/accounting/pettycash',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingReportsRoute =
  AuthenticatedAccountingReportsRouteImport.update({
    id: '/accounting/reports',
    path: '/accounting/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBoardingsIndexRoute =
  AuthenticatedBoardingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBoardingsRoute,
  } as any)
const AuthenticatedBoardingsIdRoute =
  AuthenticatedBoardingsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedBoardingsRoute,
  } as any)
const AuthenticatedBoardingsNewRoute =
  AuthenticatedBoardingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBoardingsRoute,
  } as any)
const AuthenticatedBranchesIndexRoute =
  AuthenticatedBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroomingIndexRoute =
  AuthenticatedGroomingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGroomingRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedInventoryBatchesRoute =
  AuthenticatedInventoryBatchesRouteImport.update({
    id: '/batches',
    path: '/batches',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedInventoryMovementsRoute =
  AuthenticatedInventoryMovementsRouteImport.update({
    id: '/movements',
    path: '/movements',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedInventoryWarehousesRoute =
  AuthenticatedInventoryWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedInventoryRoute,
  } as any)
const AuthenticatedInvoicesInvoiceIdRoute =
  AuthenticatedInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInvoicesRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfilePreferencesRoute =
  AuthenticatedProfilePreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileSecurityRoute =
  AuthenticatedProfileSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdRoute =
  AuthenticatedPurchaseOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPurchaseOrdersRoute,
  } as any)
const AuthenticatedPurchaseOrdersNewRoute =
  AuthenticatedPurchaseOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedPurchaseOrdersRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsDocumentsRoute =
  AuthenticatedSettingsDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsReceiptsRoute =
  AuthenticatedSettingsReceiptsRouteImport.update({
    id: '/receipts',
    path: '/receipts',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const DocsStoriesAuthRoute = DocsStoriesAuthRouteImport.update({
  id: '/stories/auth',
  path: '/stories/auth',
  getParentRoute: () => DocsRoute,
} as any)
const DocsStoriesBoardingRoute = DocsStoriesBoardingRouteImport.update({
  id: '/stories/boarding',
  path: '/stories/boarding',
  getParentRoute: () => DocsRoute,
} as any)
const DocsStoriesBranchesRoute = DocsStoriesBranchesRouteImport.update({
  id: '/stories/branches',
  path: '/stories/branches',
  getParentRoute: () => DocsRoute,
} as any)
const PBusinessSlugBoardingRoute = PBusinessSlugBoardingRouteImport.update({
  id: '/p/$businessSlug/boarding',
  path: '/p/$businessSlug/boarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PBusinessSlugBookingRoute = PBusinessSlugBookingRouteImport.update({
  id: '/p/$businessSlug/booking',
  path: '/p/$businessSlug/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const PBusinessSlugFeaturedRoute = PBusinessSlugFeaturedRouteImport.update({
  id: '/p/$businessSlug/featured',
  path: '/p/$businessSlug/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBranchesBranchIdRoomsRoute =
  AuthenticatedBranchesBranchIdRoomsRouteImport.update({
    id: '/branches/$branchId/rooms',
    path: '/branches/$branchId/rooms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PBusinessIdProductsProductIdRoute =
  PBusinessIdProductsProductIdRouteImport.update({
    id: '/p/$businessId/products/$productId',
    path: '/p/$businessId/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/boardings': typeof AuthenticatedBoardingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grooming': typeof AuthenticatedGroomingRouteWithChildren
  '/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/occupancy': typeof AuthenticatedOccupancyRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/docs/accounting': typeof DocsAccountingRoute
  '/docs/auth': typeof DocsAuthRoute
  '/docs/boarding': typeof DocsBoardingRoute
  '/docs/branches': typeof DocsBranchesRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/loyalty': typeof DocsLoyaltyRoute
  '/docs/pos': typeof DocsPosRoute
  '/docs/products': typeof DocsProductsRoute
  '/docs/staff': typeof DocsStaffRoute
  '/docs/whatsapp': typeof DocsWhatsappRoute
  '/docs/': typeof DocsIndexRoute
  '/accounting/attendance': typeof AuthenticatedAccountingAttendanceRoute
  '/accounting/commissions': typeof AuthenticatedAccountingCommissionsRoute
  '/accounting/expenses': typeof AuthenticatedAccountingExpensesRoute
  '/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/accounting/pettycash': typeof AuthenticatedAccountingPettycashRoute
  '/accounting/reports': typeof AuthenticatedAccountingReportsRoute
  '/boardings/$id': typeof AuthenticatedBoardingsIdRoute
  '/boardings/new': typeof AuthenticatedBoardingsNewRoute
  '/inventory/batches': typeof AuthenticatedInventoryBatchesRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/profile/preferences': typeof AuthenticatedProfilePreferencesRoute
  '/profile/security': typeof AuthenticatedProfileSecurityRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/documents': typeof AuthenticatedSettingsDocumentsRoute
  '/settings/receipts': typeof AuthenticatedSettingsReceiptsRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/docs/stories/auth': typeof DocsStoriesAuthRoute
  '/docs/stories/boarding': typeof DocsStoriesBoardingRoute
  '/docs/stories/branches': typeof DocsStoriesBranchesRoute
  '/p/$businessSlug/boarding': typeof PBusinessSlugBoardingRoute
  '/p/$businessSlug/booking': typeof PBusinessSlugBookingRoute
  '/p/$businessSlug/featured': typeof PBusinessSlugFeaturedRoute
  '/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/boardings/': typeof AuthenticatedBoardingsIndexRoute
  '/branches/': typeof AuthenticatedBranchesIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/grooming/': typeof AuthenticatedGroomingIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/branches/$branchId/rooms': typeof AuthenticatedBranchesBranchIdRoomsRoute
  '/p/$businessId/products/$productId': typeof PBusinessIdProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/loyalty': typeof AuthenticatedLoyaltyRoute
  '/occupancy': typeof AuthenticatedOccupancyRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/pos': typeof AuthenticatedPosRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/docs/accounting': typeof DocsAccountingRoute
  '/docs/auth': typeof DocsAuthRoute
  '/docs/boarding': typeof DocsBoardingRoute
  '/docs/branches': typeof DocsBranchesRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/loyalty': typeof DocsLoyaltyRoute
  '/docs/pos': typeof DocsPosRoute
  '/docs/products': typeof DocsProductsRoute
  '/docs/staff': typeof DocsStaffRoute
  '/docs/whatsapp': typeof DocsWhatsappRoute
  '/docs': typeof DocsIndexRoute
  '/accounting/attendance': typeof AuthenticatedAccountingAttendanceRoute
  '/accounting/commissions': typeof AuthenticatedAccountingCommissionsRoute
  '/accounting/expenses': typeof AuthenticatedAccountingExpensesRoute
  '/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/accounting/pettycash': typeof AuthenticatedAccountingPettycashRoute
  '/accounting/reports': typeof AuthenticatedAccountingReportsRoute
  '/boardings/$id': typeof AuthenticatedBoardingsIdRoute
  '/boardings/new': typeof AuthenticatedBoardingsNewRoute
  '/inventory/batches': typeof AuthenticatedInventoryBatchesRoute
  '/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/profile/preferences': typeof AuthenticatedProfilePreferencesRoute
  '/profile/security': typeof AuthenticatedProfileSecurityRoute
  '/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/documents': typeof AuthenticatedSettingsDocumentsRoute
  '/settings/receipts': typeof AuthenticatedSettingsReceiptsRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/docs/stories/auth': typeof DocsStoriesAuthRoute
  '/docs/stories/boarding': typeof DocsStoriesBoardingRoute
  '/docs/stories/branches': typeof DocsStoriesBranchesRoute
  '/p/$businessSlug/boarding': typeof PBusinessSlugBoardingRoute
  '/p/$businessSlug/booking': typeof PBusinessSlugBookingRoute
  '/p/$businessSlug/featured': typeof PBusinessSlugFeaturedRoute
  '/accounting': typeof AuthenticatedAccountingIndexRoute
  '/boardings': typeof AuthenticatedBoardingsIndexRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/grooming': typeof AuthenticatedGroomingIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/branches/$branchId/rooms': typeof AuthenticatedBranchesBranchIdRoomsRoute
  '/p/$businessId/products/$productId': typeof PBusinessIdProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/download': typeof DownloadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/boardings': typeof AuthenticatedBoardingsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grooming': typeof AuthenticatedGroomingRouteWithChildren
  '/_authenticated/inventory': typeof AuthenticatedInventoryRouteWithChildren
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRouteWithChildren
  '/_authenticated/loyalty': typeof AuthenticatedLoyaltyRoute
  '/_authenticated/occupancy': typeof AuthenticatedOccupancyRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/docs/accounting': typeof DocsAccountingRoute
  '/docs/auth': typeof DocsAuthRoute
  '/docs/boarding': typeof DocsBoardingRoute
  '/docs/branches': typeof DocsBranchesRoute
  '/docs/dashboard': typeof DocsDashboardRoute
  '/docs/loyalty': typeof DocsLoyaltyRoute
  '/docs/pos': typeof DocsPosRoute
  '/docs/products': typeof DocsProductsRoute
  '/docs/staff': typeof DocsStaffRoute
  '/docs/whatsapp': typeof DocsWhatsappRoute
  '/docs/': typeof DocsIndexRoute
  '/_authenticated/accounting/attendance': typeof AuthenticatedAccountingAttendanceRoute
  '/_authenticated/accounting/commissions': typeof AuthenticatedAccountingCommissionsRoute
  '/_authenticated/accounting/expenses': typeof AuthenticatedAccountingExpensesRoute
  '/_authenticated/accounting/journal': typeof AuthenticatedAccountingJournalRoute
  '/_authenticated/accounting/pettycash': typeof AuthenticatedAccountingPettycashRoute
  '/_authenticated/accounting/reports': typeof AuthenticatedAccountingReportsRoute
  '/_authenticated/boardings/$id': typeof AuthenticatedBoardingsIdRoute
  '/_authenticated/boardings/new': typeof AuthenticatedBoardingsNewRoute
  '/_authenticated/inventory/batches': typeof AuthenticatedInventoryBatchesRoute
  '/_authenticated/inventory/movements': typeof AuthenticatedInventoryMovementsRoute
  '/_authenticated/inventory/warehouses': typeof AuthenticatedInventoryWarehousesRoute
  '/_authenticated/invoices/$invoiceId': typeof AuthenticatedInvoicesInvoiceIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/profile/preferences': typeof AuthenticatedProfilePreferencesRoute
  '/_authenticated/profile/security': typeof AuthenticatedProfileSecurityRoute
  '/_authenticated/purchase-orders/$id': typeof AuthenticatedPurchaseOrdersIdRoute
  '/_authenticated/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/documents': typeof AuthenticatedSettingsDocumentsRoute
  '/_authenticated/settings/receipts': typeof AuthenticatedSettingsReceiptsRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRoute
  '/docs/stories/auth': typeof DocsStoriesAuthRoute
  '/docs/stories/boarding': typeof DocsStoriesBoardingRoute
  '/docs/stories/branches': typeof DocsStoriesBranchesRoute
  '/p/$businessSlug/boarding': typeof PBusinessSlugBoardingRoute
  '/p/$businessSlug/booking': typeof PBusinessSlugBookingRoute
  '/p/$businessSlug/featured': typeof PBusinessSlugFeaturedRoute
  '/_authenticated/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/_authenticated/boardings/': typeof AuthenticatedBoardingsIndexRoute
  '/_authenticated/branches/': typeof AuthenticatedBranchesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/grooming/': typeof AuthenticatedGroomingIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/branches/$branchId/rooms': typeof AuthenticatedBranchesBranchIdRoomsRoute
  '/p/$businessId/products/$productId': typeof PBusinessIdProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/docs'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/boardings'
    | '/dashboard'
    | '/grooming'
    | '/inventory'
    | '/invoices'
    | '/loyalty'
    | '/occupancy'
    | '/orders'
    | '/portal'
    | '/pos'
    | '/products'
    | '/profile'
    | '/purchase-orders'
    | '/settings'
    | '/staff'
    | '/suppliers'
    | '/whatsapp'
    | '/docs/accounting'
    | '/docs/auth'
    | '/docs/boarding'
    | '/docs/branches'
    | '/docs/dashboard'
    | '/docs/loyalty'
    | '/docs/pos'
    | '/docs/products'
    | '/docs/staff'
    | '/docs/whatsapp'
    | '/docs/'
    | '/accounting/attendance'
    | '/accounting/commissions'
    | '/accounting/expenses'
    | '/accounting/journal'
    | '/accounting/pettycash'
    | '/accounting/reports'
    | '/boardings/$id'
    | '/boardings/new'
    | '/inventory/batches'
    | '/inventory/movements'
    | '/inventory/warehouses'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/profile/preferences'
    | '/profile/security'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/settings/billing'
    | '/settings/documents'
    | '/settings/receipts'
    | '/staff/$staffId'
    | '/docs/stories/auth'
    | '/docs/stories/boarding'
    | '/docs/stories/branches'
    | '/p/$businessSlug/boarding'
    | '/p/$businessSlug/booking'
    | '/p/$businessSlug/featured'
    | '/accounting/'
    | '/boardings/'
    | '/branches/'
    | '/customers/'
    | '/grooming/'
    | '/inventory/'
    | '/profile/'
    | '/settings/'
    | '/branches/$branchId/rooms'
    | '/p/$businessId/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/invoices'
    | '/loyalty'
    | '/occupancy'
    | '/orders'
    | '/portal'
    | '/pos'
    | '/products'
    | '/purchase-orders'
    | '/staff'
    | '/suppliers'
    | '/whatsapp'
    | '/docs/accounting'
    | '/docs/auth'
    | '/docs/boarding'
    | '/docs/branches'
    | '/docs/dashboard'
    | '/docs/loyalty'
    | '/docs/pos'
    | '/docs/products'
    | '/docs/staff'
    | '/docs/whatsapp'
    | '/docs'
    | '/accounting/attendance'
    | '/accounting/commissions'
    | '/accounting/expenses'
    | '/accounting/journal'
    | '/accounting/pettycash'
    | '/accounting/reports'
    | '/boardings/$id'
    | '/boardings/new'
    | '/inventory/batches'
    | '/inventory/movements'
    | '/inventory/warehouses'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/profile/preferences'
    | '/profile/security'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/settings/billing'
    | '/settings/documents'
    | '/settings/receipts'
    | '/staff/$staffId'
    | '/docs/stories/auth'
    | '/docs/stories/boarding'
    | '/docs/stories/branches'
    | '/p/$businessSlug/boarding'
    | '/p/$businessSlug/booking'
    | '/p/$businessSlug/featured'
    | '/accounting'
    | '/boardings'
    | '/branches'
    | '/customers'
    | '/grooming'
    | '/inventory'
    | '/profile'
    | '/settings'
    | '/branches/$branchId/rooms'
    | '/p/$businessId/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/docs'
    | '/download'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authenticated/boardings'
    | '/_authenticated/dashboard'
    | '/_authenticated/grooming'
    | '/_authenticated/inventory'
    | '/_authenticated/invoices'
    | '/_authenticated/loyalty'
    | '/_authenticated/occupancy'
    | '/_authenticated/orders'
    | '/_authenticated/portal'
    | '/_authenticated/pos'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/suppliers'
    | '/_authenticated/whatsapp'
    | '/docs/accounting'
    | '/docs/auth'
    | '/docs/boarding'
    | '/docs/branches'
    | '/docs/dashboard'
    | '/docs/loyalty'
    | '/docs/pos'
    | '/docs/products'
    | '/docs/staff'
    | '/docs/whatsapp'
    | '/docs/'
    | '/_authenticated/accounting/attendance'
    | '/_authenticated/accounting/commissions'
    | '/_authenticated/accounting/expenses'
    | '/_authenticated/accounting/journal'
    | '/_authenticated/accounting/pettycash'
    | '/_authenticated/accounting/reports'
    | '/_authenticated/boardings/$id'
    | '/_authenticated/boardings/new'
    | '/_authenticated/inventory/batches'
    | '/_authenticated/inventory/movements'
    | '/_authenticated/inventory/warehouses'
    | '/_authenticated/invoices/$invoiceId'
    | '/_authenticated/invoices/new'
    | '/_authenticated/profile/preferences'
    | '/_authenticated/profile/security'
    | '/_authenticated/purchase-orders/$id'
    | '/_authenticated/purchase-orders/new'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/documents'
    | '/_authenticated/settings/receipts'
    | '/_authenticated/staff/$staffId'
    | '/docs/stories/auth'
    | '/docs/stories/boarding'
    | '/docs/stories/branches'
    | '/p/$businessSlug/boarding'
    | '/p/$businessSlug/booking'
    | '/p/$businessSlug/featured'
    | '/_authenticated/accounting/'
    | '/_authenticated/boardings/'
    | '/_authenticated/branches/'
    | '/_authenticated/customers/'
    | '/_authenticated/grooming/'
    | '/_authenticated/inventory/'
    | '/_authenticated/profile/'
    | '/_authenticated/settings/'
    | '/_authenticated/branches/$branchId/rooms'
    | '/p/$businessId/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  PBusinessSlugBoardingRoute: typeof PBusinessSlugBoardingRoute
  PBusinessSlugBookingRoute: typeof PBusinessSlugBookingRoute
  PBusinessSlugFeaturedRoute: typeof PBusinessSlugFeaturedRoute
  PBusinessIdProductsProductIdRoute: typeof PBusinessIdProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/boardings': {
      id: '/_authenticated/boardings'
      path: '/boardings'
      fullPath: '/boardings'
      preLoaderRoute: typeof AuthenticatedBoardingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grooming': {
      id: '/_authenticated/grooming'
      path: '/grooming'
      fullPath: '/grooming'
      preLoaderRoute: typeof AuthenticatedGroomingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/loyalty': {
      id: '/_authenticated/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof AuthenticatedLoyaltyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/occupancy': {
      id: '/_authenticated/occupancy'
      path: '/occupancy'
      fullPath: '/occupancy'
      preLoaderRoute: typeof AuthenticatedOccupancyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/accounting': {
      id: '/docs/accounting'
      path: '/accounting'
      fullPath: '/docs/accounting'
      preLoaderRoute: typeof DocsAccountingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/auth': {
      id: '/docs/auth'
      path: '/auth'
      fullPath: '/docs/auth'
      preLoaderRoute: typeof DocsAuthRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/boarding': {
      id: '/docs/boarding'
      path: '/boarding'
      fullPath: '/docs/boarding'
      preLoaderRoute: typeof DocsBoardingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/branches': {
      id: '/docs/branches'
      path: '/branches'
      fullPath: '/docs/branches'
      preLoaderRoute: typeof DocsBranchesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dashboard': {
      id: '/docs/dashboard'
      path: '/dashboard'
      fullPath: '/docs/dashboard'
      preLoaderRoute: typeof DocsDashboardRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/loyalty': {
      id: '/docs/loyalty'
      path: '/loyalty'
      fullPath: '/docs/loyalty'
      preLoaderRoute: typeof DocsLoyaltyRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/pos': {
      id: '/docs/pos'
      path: '/pos'
      fullPath: '/docs/pos'
      preLoaderRoute: typeof DocsPosRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/products': {
      id: '/docs/products'
      path: '/products'
      fullPath: '/docs/products'
      preLoaderRoute: typeof DocsProductsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/staff': {
      id: '/docs/staff'
      path: '/staff'
      fullPath: '/docs/staff'
      preLoaderRoute: typeof DocsStaffRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/whatsapp': {
      id: '/docs/whatsapp'
      path: '/whatsapp'
      fullPath: '/docs/whatsapp'
      preLoaderRoute: typeof DocsWhatsappRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_authenticated/accounting/': {
      id: '/_authenticated/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthenticatedAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/attendance': {
      id: '/_authenticated/accounting/attendance'
      path: '/accounting/attendance'
      fullPath: '/accounting/attendance'
      preLoaderRoute: typeof AuthenticatedAccountingAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/commissions': {
      id: '/_authenticated/accounting/commissions'
      path: '/accounting/commissions'
      fullPath: '/accounting/commissions'
      preLoaderRoute: typeof AuthenticatedAccountingCommissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/expenses': {
      id: '/_authenticated/accounting/expenses'
      path: '/accounting/expenses'
      fullPath: '/accounting/expenses'
      preLoaderRoute: typeof AuthenticatedAccountingExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/journal': {
      id: '/_authenticated/accounting/journal'
      path: '/accounting/journal'
      fullPath: '/accounting/journal'
      preLoaderRoute: typeof AuthenticatedAccountingJournalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/pettycash': {
      id: '/_authenticated/accounting/pettycash'
      path: '/accounting/pettycash'
      fullPath: '/accounting/pettycash'
      preLoaderRoute: typeof AuthenticatedAccountingPettycashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/reports': {
      id: '/_authenticated/accounting/reports'
      path: '/accounting/reports'
      fullPath: '/accounting/reports'
      preLoaderRoute: typeof AuthenticatedAccountingReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/boardings/': {
      id: '/_authenticated/boardings/'
      path: '/'
      fullPath: '/boardings/'
      preLoaderRoute: typeof AuthenticatedBoardingsIndexRouteImport
      parentRoute: typeof AuthenticatedBoardingsRoute
    }
    '/_authenticated/boardings/$id': {
      id: '/_authenticated/boardings/$id'
      path: '/$id'
      fullPath: '/boardings/$id'
      preLoaderRoute: typeof AuthenticatedBoardingsIdRouteImport
      parentRoute: typeof AuthenticatedBoardingsRoute
    }
    '/_authenticated/boardings/new': {
      id: '/_authenticated/boardings/new'
      path: '/new'
      fullPath: '/boardings/new'
      preLoaderRoute: typeof AuthenticatedBoardingsNewRouteImport
      parentRoute: typeof AuthenticatedBoardingsRoute
    }
    '/_authenticated/branches/': {
      id: '/_authenticated/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof AuthenticatedBranchesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grooming/': {
      id: '/_authenticated/grooming/'
      path: '/'
      fullPath: '/grooming/'
      preLoaderRoute: typeof AuthenticatedGroomingIndexRouteImport
      parentRoute: typeof AuthenticatedGroomingRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/inventory/batches': {
      id: '/_authenticated/inventory/batches'
      path: '/batches'
      fullPath: '/inventory/batches'
      preLoaderRoute: typeof AuthenticatedInventoryBatchesRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/inventory/movements': {
      id: '/_authenticated/inventory/movements'
      path: '/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AuthenticatedInventoryMovementsRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/inventory/warehouses': {
      id: '/_authenticated/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof AuthenticatedInventoryWarehousesRouteImport
      parentRoute: typeof AuthenticatedInventoryRoute
    }
    '/_authenticated/invoices/$invoiceId': {
      id: '/_authenticated/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedInvoicesRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/preferences': {
      id: '/_authenticated/profile/preferences'
      path: '/preferences'
      fullPath: '/profile/preferences'
      preLoaderRoute: typeof AuthenticatedProfilePreferencesRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/security': {
      id: '/_authenticated/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof AuthenticatedProfileSecurityRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/purchase-orders/$id': {
      id: '/_authenticated/purchase-orders/$id'
      path: '/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdRouteImport
      parentRoute: typeof AuthenticatedPurchaseOrdersRoute
    }
    '/_authenticated/purchase-orders/new': {
      id: '/_authenticated/purchase-orders/new'
      path: '/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedPurchaseOrdersRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/documents': {
      id: '/_authenticated/settings/documents'
      path: '/documents'
      fullPath: '/settings/documents'
      preLoaderRoute: typeof AuthenticatedSettingsDocumentsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/receipts': {
      id: '/_authenticated/settings/receipts'
      path: '/receipts'
      fullPath: '/settings/receipts'
      preLoaderRoute: typeof AuthenticatedSettingsReceiptsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/docs/stories/auth': {
      id: '/docs/stories/auth'
      path: '/stories/auth'
      fullPath: '/docs/stories/auth'
      preLoaderRoute: typeof DocsStoriesAuthRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/stories/boarding': {
      id: '/docs/stories/boarding'
      path: '/stories/boarding'
      fullPath: '/docs/stories/boarding'
      preLoaderRoute: typeof DocsStoriesBoardingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/stories/branches': {
      id: '/docs/stories/branches'
      path: '/stories/branches'
      fullPath: '/docs/stories/branches'
      preLoaderRoute: typeof DocsStoriesBranchesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/p/$businessSlug/boarding': {
      id: '/p/$businessSlug/boarding'
      path: '/p/$businessSlug/boarding'
      fullPath: '/p/$businessSlug/boarding'
      preLoaderRoute: typeof PBusinessSlugBoardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$businessSlug/booking': {
      id: '/p/$businessSlug/booking'
      path: '/p/$businessSlug/booking'
      fullPath: '/p/$businessSlug/booking'
      preLoaderRoute: typeof PBusinessSlugBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$businessSlug/featured': {
      id: '/p/$businessSlug/featured'
      path: '/p/$businessSlug/featured'
      fullPath: '/p/$businessSlug/featured'
      preLoaderRoute: typeof PBusinessSlugFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/branches/$branchId/rooms': {
      id: '/_authenticated/branches/$branchId/rooms'
      path: '/branches/$branchId/rooms'
      fullPath: '/branches/$branchId/rooms'
      preLoaderRoute: typeof AuthenticatedBranchesBranchIdRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/p/$businessId/products/$productId': {
      id: '/p/$businessId/products/$productId'
      path: '/p/$businessId/products/$productId'
      fullPath: '/p/$businessId/products/$productId'
      preLoaderRoute: typeof PBusinessIdProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedBoardingsRouteChildren {
  AuthenticatedBoardingsIdRoute: typeof AuthenticatedBoardingsIdRoute
  AuthenticatedBoardingsNewRoute: typeof AuthenticatedBoardingsNewRoute
  AuthenticatedBoardingsIndexRoute: typeof AuthenticatedBoardingsIndexRoute
}

const AuthenticatedBoardingsRouteChildren: AuthenticatedBoardingsRouteChildren =
  {
    AuthenticatedBoardingsIdRoute: AuthenticatedBoardingsIdRoute,
    AuthenticatedBoardingsNewRoute: AuthenticatedBoardingsNewRoute,
    AuthenticatedBoardingsIndexRoute: AuthenticatedBoardingsIndexRoute,
  }

const AuthenticatedBoardingsRouteWithChildren =
  AuthenticatedBoardingsRoute._addFileChildren(
    AuthenticatedBoardingsRouteChildren,
  )

interface AuthenticatedGroomingRouteChildren {
  AuthenticatedGroomingIndexRoute: typeof AuthenticatedGroomingIndexRoute
}

const AuthenticatedGroomingRouteChildren: AuthenticatedGroomingRouteChildren = {
  AuthenticatedGroomingIndexRoute: AuthenticatedGroomingIndexRoute,
}

const AuthenticatedGroomingRouteWithChildren =
  AuthenticatedGroomingRoute._addFileChildren(
    AuthenticatedGroomingRouteChildren,
  )

interface AuthenticatedInventoryRouteChildren {
  AuthenticatedInventoryBatchesRoute: typeof AuthenticatedInventoryBatchesRoute
  AuthenticatedInventoryMovementsRoute: typeof AuthenticatedInventoryMovementsRoute
  AuthenticatedInventoryWarehousesRoute: typeof AuthenticatedInventoryWarehousesRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
}

const AuthenticatedInventoryRouteChildren: AuthenticatedInventoryRouteChildren =
  {
    AuthenticatedInventoryBatchesRoute: AuthenticatedInventoryBatchesRoute,
    AuthenticatedInventoryMovementsRoute: AuthenticatedInventoryMovementsRoute,
    AuthenticatedInventoryWarehousesRoute:
      AuthenticatedInventoryWarehousesRoute,
    AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  }

const AuthenticatedInventoryRouteWithChildren =
  AuthenticatedInventoryRoute._addFileChildren(
    AuthenticatedInventoryRouteChildren,
  )

interface AuthenticatedInvoicesRouteChildren {
  AuthenticatedInvoicesInvoiceIdRoute: typeof AuthenticatedInvoicesInvoiceIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
}

const AuthenticatedInvoicesRouteChildren: AuthenticatedInvoicesRouteChildren = {
  AuthenticatedInvoicesInvoiceIdRoute: AuthenticatedInvoicesInvoiceIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
}

const AuthenticatedInvoicesRouteWithChildren =
  AuthenticatedInvoicesRoute._addFileChildren(
    AuthenticatedInvoicesRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfilePreferencesRoute: typeof AuthenticatedProfilePreferencesRoute
  AuthenticatedProfileSecurityRoute: typeof AuthenticatedProfileSecurityRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfilePreferencesRoute: AuthenticatedProfilePreferencesRoute,
  AuthenticatedProfileSecurityRoute: AuthenticatedProfileSecurityRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedPurchaseOrdersRouteChildren {
  AuthenticatedPurchaseOrdersIdRoute: typeof AuthenticatedPurchaseOrdersIdRoute
  AuthenticatedPurchaseOrdersNewRoute: typeof AuthenticatedPurchaseOrdersNewRoute
}

const AuthenticatedPurchaseOrdersRouteChildren: AuthenticatedPurchaseOrdersRouteChildren =
  {
    AuthenticatedPurchaseOrdersIdRoute: AuthenticatedPurchaseOrdersIdRoute,
    AuthenticatedPurchaseOrdersNewRoute: AuthenticatedPurchaseOrdersNewRoute,
  }

const AuthenticatedPurchaseOrdersRouteWithChildren =
  AuthenticatedPurchaseOrdersRoute._addFileChildren(
    AuthenticatedPurchaseOrdersRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsDocumentsRoute: typeof AuthenticatedSettingsDocumentsRoute
  AuthenticatedSettingsReceiptsRoute: typeof AuthenticatedSettingsReceiptsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsDocumentsRoute: AuthenticatedSettingsDocumentsRoute,
  AuthenticatedSettingsReceiptsRoute: AuthenticatedSettingsReceiptsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBoardingsRoute: typeof AuthenticatedBoardingsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGroomingRoute: typeof AuthenticatedGroomingRouteWithChildren
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRouteWithChildren
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRouteWithChildren
  AuthenticatedLoyaltyRoute: typeof AuthenticatedLoyaltyRoute
  AuthenticatedOccupancyRoute: typeof AuthenticatedOccupancyRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedAccountingAttendanceRoute: typeof AuthenticatedAccountingAttendanceRoute
  AuthenticatedAccountingCommissionsRoute: typeof AuthenticatedAccountingCommissionsRoute
  AuthenticatedAccountingExpensesRoute: typeof AuthenticatedAccountingExpensesRoute
  AuthenticatedAccountingJournalRoute: typeof AuthenticatedAccountingJournalRoute
  AuthenticatedAccountingPettycashRoute: typeof AuthenticatedAccountingPettycashRoute
  AuthenticatedAccountingReportsRoute: typeof AuthenticatedAccountingReportsRoute
  AuthenticatedAccountingIndexRoute: typeof AuthenticatedAccountingIndexRoute
  AuthenticatedBranchesIndexRoute: typeof AuthenticatedBranchesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedBranchesBranchIdRoomsRoute: typeof AuthenticatedBranchesBranchIdRoomsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBoardingsRoute: AuthenticatedBoardingsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGroomingRoute: AuthenticatedGroomingRouteWithChildren,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRouteWithChildren,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRouteWithChildren,
  AuthenticatedLoyaltyRoute: AuthenticatedLoyaltyRoute,
  AuthenticatedOccupancyRoute: AuthenticatedOccupancyRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedPurchaseOrdersRoute:
    AuthenticatedPurchaseOrdersRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedAccountingAttendanceRoute:
    AuthenticatedAccountingAttendanceRoute,
  AuthenticatedAccountingCommissionsRoute:
    AuthenticatedAccountingCommissionsRoute,
  AuthenticatedAccountingExpensesRoute: AuthenticatedAccountingExpensesRoute,
  AuthenticatedAccountingJournalRoute: AuthenticatedAccountingJournalRoute,
  AuthenticatedAccountingPettycashRoute: AuthenticatedAccountingPettycashRoute,
  AuthenticatedAccountingReportsRoute: AuthenticatedAccountingReportsRoute,
  AuthenticatedAccountingIndexRoute: AuthenticatedAccountingIndexRoute,
  AuthenticatedBranchesIndexRoute: AuthenticatedBranchesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedBranchesBranchIdRoomsRoute:
    AuthenticatedBranchesBranchIdRoomsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DocsRouteChildren {
  DocsAccountingRoute: typeof DocsAccountingRoute
  DocsAuthRoute: typeof DocsAuthRoute
  DocsBoardingRoute: typeof DocsBoardingRoute
  DocsBranchesRoute: typeof DocsBranchesRoute
  DocsDashboardRoute: typeof DocsDashboardRoute
  DocsLoyaltyRoute: typeof DocsLoyaltyRoute
  DocsPosRoute: typeof DocsPosRoute
  DocsProductsRoute: typeof DocsProductsRoute
  DocsStaffRoute: typeof DocsStaffRoute
  DocsWhatsappRoute: typeof DocsWhatsappRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsStoriesAuthRoute: typeof DocsStoriesAuthRoute
  DocsStoriesBoardingRoute: typeof DocsStoriesBoardingRoute
  DocsStoriesBranchesRoute: typeof DocsStoriesBranchesRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAccountingRoute: DocsAccountingRoute,
  DocsAuthRoute: DocsAuthRoute,
  DocsBoardingRoute: DocsBoardingRoute,
  DocsBranchesRoute: DocsBranchesRoute,
  DocsDashboardRoute: DocsDashboardRoute,
  DocsLoyaltyRoute: DocsLoyaltyRoute,
  DocsPosRoute: DocsPosRoute,
  DocsProductsRoute: DocsProductsRoute,
  DocsStaffRoute: DocsStaffRoute,
  DocsWhatsappRoute: DocsWhatsappRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsStoriesAuthRoute: DocsStoriesAuthRoute,
  DocsStoriesBoardingRoute: DocsStoriesBoardingRoute,
  DocsStoriesBranchesRoute: DocsStoriesBranchesRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  DownloadRoute: DownloadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  PBusinessSlugBoardingRoute: PBusinessSlugBoardingRoute,
  PBusinessSlugBookingRoute: PBusinessSlugBookingRoute,
  PBusinessSlugFeaturedRoute: PBusinessSlugFeaturedRoute,
  PBusinessIdProductsProductIdRoute: PBusinessIdProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
