// flow-typed signature: 300612c60dee7fa8f0828284182b3ef6
// flow-typed version: <<STUB>>/@tommoor/remove-markdown_v0.3.1/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tommoor/remove-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tommoor/remove-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tommoor/remove-markdown/test/remove-markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tommoor/remove-markdown/index' {
  declare module.exports: $Exports<'@tommoor/remove-markdown'>;
}
declare module '@tommoor/remove-markdown/index.js' {
  declare module.exports: $Exports<'@tommoor/remove-markdown'>;
}
declare module '@tommoor/remove-markdown/test/remove-markdown.js' {
  declare module.exports: $Exports<'@tommoor/remove-markdown/test/remove-markdown'>;
}
