import {
  TrashIcon,
  DownloadIcon,
  ReplaceIcon,
  AlignImageLeftIcon,
  AlignImageRightIcon,
  AlignImageCenterIcon,
  AlignFullWidthIcon,
  EditIcon,
  CommentIcon,
  LinkIcon,
} from "outline-icons";
import { NodeSelection } from "prosemirror-state";
import type { EditorState } from "prosemirror-state";
import { isNodeActive } from "@shared/editor/queries/isNodeActive";
import { InlineIconMaxWidth } from "@shared/editor/components/Image";
import type { MenuItem, SelectionContext } from "@shared/editor/types";
import { metaDisplay } from "@shared/utils/keyboard";
import { ImageSource } from "@shared/editor/lib/FileHelper";
import Desktop from "~/utils/Desktop";
import { isMarkActive } from "@shared/editor/queries/isMarkActive";
import { t } from "i18next";

/**
 * Returns menu items for the image selection toolbar.
 *
 * @param ctx - the current selection context.
 * @returns an array of menu items.
 */
export default function imageMenuItems(ctx: SelectionContext): MenuItem[] {
  if (ctx.readOnly) {
    return [];
  }
  const { schema, state } = ctx;
  const isLeftAligned = isNodeActive(schema.nodes.image, {
    layoutClass: "left-50",
  });
  const isRightAligned = isNodeActive(schema.nodes.image, {
    layoutClass: "right-50",
  });
  const isFullWidthAligned = isNodeActive(schema.nodes.image, {
    layoutClass: "full-width",
  });
  const isDiagram = isNodeActive(schema.nodes.image, {
    source: ImageSource.DiagramsNet,
  });
  const isEmptyDiagram = isNodeActive(schema.nodes.image, {
    source: ImageSource.DiagramsNet,
    src: "",
  });
  const isExcalidraw = isNodeActive(schema.nodes.image, {
    source: ImageSource.Excalidraw,
  });
  const isEmptyExcalidraw = isNodeActive(schema.nodes.image, {
    source: ImageSource.Excalidraw,
    src: "",
  });
  // Diagram-like nodes (diagrams.net or Excalidraw) share toolbar behavior:
  // alignment/dimension/replace controls are hidden while empty, and "Replace
  // image" is never offered because the content is generated by an editor.
  const isAnyDiagram = (state: EditorState) =>
    isDiagram(state) || isExcalidraw(state);
  const isAnyEmptyDiagram = (state: EditorState) =>
    isEmptyDiagram(state) || isEmptyExcalidraw(state);

  // Small images are displayed as inline icons, so alignment controls don't apply.
  const selectedNode =
    state.selection instanceof NodeSelection ? state.selection.node : undefined;
  const isInlineIcon =
    selectedNode?.type === schema.nodes.image &&
    selectedNode.attrs.layoutClass !== "full-width" &&
    !!selectedNode.attrs.width &&
    selectedNode.attrs.width < InlineIconMaxWidth;

  return [
    {
      name: "alignLeft",
      tooltip: t("Align left"),
      icon: <AlignImageLeftIcon />,
      active: isLeftAligned,
      visible: !isAnyEmptyDiagram(state) && !isInlineIcon,
    },
    {
      name: "alignCenter",
      tooltip: t("Align center"),
      icon: <AlignImageCenterIcon />,
      active: (state) =>
        isNodeActive(schema.nodes.image)(state) &&
        !isLeftAligned(state) &&
        !isRightAligned(state) &&
        !isFullWidthAligned(state),
      visible: !isAnyEmptyDiagram(state) && !isInlineIcon,
    },
    {
      name: "alignRight",
      tooltip: t("Align right"),
      icon: <AlignImageRightIcon />,
      active: isRightAligned,
      visible: !isAnyEmptyDiagram(state) && !isInlineIcon,
    },
    {
      name: "alignFullWidth",
      tooltip: t("Full width"),
      icon: <AlignFullWidthIcon />,
      active: isFullWidthAligned,
      visible: !isAnyEmptyDiagram(state) && !isInlineIcon,
    },
    {
      name: "separator",
      visible: !isInlineIcon,
    },
    {
      name: "dimensions",
      tooltip: `${t("Width")} × ${t("Height")}`,
      visible: !isFullWidthAligned(state) && !isAnyEmptyDiagram(state),
      skipIcon: true,
    },
    {
      name: "separator",
    },
    {
      name: "editDiagram",
      tooltip: t("Edit diagram"),
      icon: <EditIcon />,
      visible: isDiagram(state) && !Desktop.isElectron(),
    },
    {
      name: "editExcalidraw",
      tooltip: t("Edit diagram"),
      icon: <EditIcon />,
      visible: isExcalidraw(state),
    },
    {
      name: "downloadImage",
      tooltip: t("Download image"),
      icon: <DownloadIcon />,
      visible: !!fetch && !isAnyEmptyDiagram(state),
    },
    {
      tooltip: t("Replace image"),
      icon: <ReplaceIcon />,
      visible: !isAnyDiagram(state),
      children: [
        {
          name: "replaceImage",
          label: t("Upload an image"),
        },
        {
          name: "editImageUrl",
          label: t("Edit image URL"),
        },
      ],
    },
    {
      name: "deleteImage",
      tooltip: t("Delete image"),
      icon: <TrashIcon />,
    },
    {
      name: "separator",
    },
    {
      name: "linkOnImage",
      tooltip: t("Create link"),
      shortcut: `${metaDisplay}+K`,
      active: isMarkActive(schema.marks.link),
      icon: <LinkIcon />,
    },
    {
      name: "commentOnImage",
      tooltip: t("Comment"),
      shortcut: `${metaDisplay}+⌥+M`,
      icon: <CommentIcon />,
    },
  ];
}
