import { z } from "zod";
import type { IntegrationService, ProsemirrorDoc } from "./types";
import {
  CollectionPermission,
  type ImportableIntegrationService,
  IssueTrackerIntegrationService,
} from "./types";
import { PageType } from "plugins/notion/shared/types";

const BaseImportInputItemSchema = z.object({
  permission: z.enum(CollectionPermission).optional(),
});

export type BaseImportInput = z.infer<typeof BaseImportInputItemSchema>[];

export const NotionImportInputItemSchema = BaseImportInputItemSchema.extend({
  type: z.enum(PageType).optional(),
  externalId: z.string().optional(),
});

export type NotionImportInput = z.infer<typeof NotionImportInputItemSchema>[];

export const MarkdownImportInputItemSchema = BaseImportInputItemSchema.extend({
  externalId: z.string(),
  /**
   * Storage key of the uploaded zip. Present on the bootstrap entry; absent
   * on entries appended by the bootstrap task to mark discovered collections.
   */
  storageKey: z.string().optional(),
});

export type MarkdownImportInput = z.infer<
  typeof MarkdownImportInputItemSchema
>[];

export type ImportInput<T extends ImportableIntegrationService> =
  T extends IntegrationService.Notion
    ? NotionImportInput
    : T extends IntegrationService.Markdown
      ? MarkdownImportInput
      : BaseImportInput;

export const BaseImportTaskInputItemSchema = z.object({
  externalId: z.string(),
  parentExternalId: z.string().optional(),
  collectionExternalId: z.string().optional(),
});

export type BaseImportTaskInput = z.infer<
  typeof BaseImportTaskInputItemSchema
>[];

export const NotionImportTaskInputItemSchema =
  BaseImportTaskInputItemSchema.extend({
    type: z.enum(PageType),
  });

export type NotionImportTaskInput = z.infer<
  typeof NotionImportTaskInputItemSchema
>[];

/**
 * Manifest entry describing a single attachment discovered during the
 * Markdown zip bootstrap phase. The `id` is a pre-assigned UUID used both
 * as the attachment node id in per-page prosemirror output and as the
 * Attachment row id created during completion.
 */
export const MarkdownAttachmentManifestItemSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  mimeType: z.string(),
  pathInZip: z.string(),
});

export type MarkdownAttachmentManifestItem = z.infer<
  typeof MarkdownAttachmentManifestItemSchema
>;

/**
 * Bootstrap task input — single item carrying the storage key of the
 * uploaded zip. Produced by the import creation route and consumed by
 * MarkdownAPIImportTask. After the bootstrap phase completes, the task
 * mutates its own input to embed the discovered attachment manifest so the
 * completion phase can rehydrate it without a model schema change. The
 * row's `phase` column (`ImportTaskPhase.Bootstrap`) tells the dispatcher
 * which shape to expect; the input items themselves carry no discriminator.
 */
const MarkdownZipImportTaskInputItemSchema =
  BaseImportTaskInputItemSchema.extend({
    storageKey: z.string(),
    manifest: z.array(MarkdownAttachmentManifestItemSchema).optional(),
  });

export type MarkdownZipImportTaskInputItem = z.infer<
  typeof MarkdownZipImportTaskInputItemSchema
>;

/**
 * Per-page task input. Generated by the bootstrap task and consumed by
 * subsequent MarkdownAPIImportTask runs. `children` carries this document's
 * direct descendants so that each level of the document tree is scheduled
 * as a separate task wave; this preserves parent-before-child ordering
 * during persistence (createdAt of child tasks is strictly later than
 * parents'). The type is defined as a TypeScript interface rather than via
 * z.infer because it is only consumed internally — never validated at an
 * API boundary — and zod's recursive-schema ergonomics aren't worth the
 * cost here.
 */
export interface MarkdownPageImportTaskInputItem {
  externalId: string;
  parentExternalId?: string;
  collectionExternalId?: string;
  title: string;
  path: string;
  markdownText: string;
  attachmentMap: MarkdownAttachmentManifestItem[];
  docMap: Record<string, string>;
  children?: MarkdownPageImportTaskInputItem[];
}

export type MarkdownImportTaskInput = (
  | MarkdownZipImportTaskInputItem
  | MarkdownPageImportTaskInputItem
)[];

export type ImportTaskInput<T extends ImportableIntegrationService> =
  T extends IntegrationService.Notion
    ? NotionImportTaskInput
    : T extends IntegrationService.Markdown
      ? MarkdownImportTaskInput
      : BaseImportTaskInput;

// No reason to be here except for co-location with import task input.
export type ImportTaskOutput = {
  externalId: string;
  title: string;
  icon?: string;
  author?: string;
  content: ProsemirrorDoc;
  createdAt?: Date;
  updatedAt?: Date;
}[];

export const IssueSource = z.object({
  id: z.string().nonempty(),
  name: z.string().nonempty(),
  owner: z.object({
    id: z.string().nonempty(),
    name: z.string().nonempty(),
  }),
  service: z.enum(IssueTrackerIntegrationService),
});

export type IssueSource = z.infer<typeof IssueSource>;
