export const iso6393To1: Record<string, string | undefined> = {
  eng: "en",
  fra: "fr",
  deu: "de",
  spa: "es",
  ita: "it",
  por: "pt",
  rus: "ru",
  jpn: "ja",
  zho: "zh",
  ara: "ar",
  hin: "hi",
  ben: "bn",
  und: undefined,
};
