import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export type TReportData = {
	title: string;
	businessName: string;
	date: string;
	sections: {
		title: string;
		items: { label: string; value: string | number }[];
	}[];
};

/**
 * Generates a PDF report for the store owner.
 */
export async function generatePDFReport(data: TReportData) {
	const pdfDoc = await PDFDocument.create();
	const page = pdfDoc.addPage([600, 800]);
	const { width, height } = page.getSize();

	const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
	const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

	let currentY = height - 50;

	// Header: Business Name
	page.drawText(data.businessName, {
		x: 50,
		y: currentY,
		size: 20,
		font: boldFont,
		color: rgb(0.06, 0.73, 0.51), // Mint green
	});
	currentY -= 30;

	// Title
	page.drawText(data.title, {
		x: 50,
		y: currentY,
		size: 24,
		font: boldFont,
		color: rgb(0, 0, 0),
	});
	currentY -= 20;

	// Date
	page.drawText(`Generated on: ${data.date}`, {
		x: 50,
		y: currentY,
		size: 10,
		font: font,
		color: rgb(0.5, 0.5, 0.5),
	});
	currentY -= 40;

	// Sections
	for (const section of data.sections) {
		if (currentY < 100) {
			// Basic pagination check
			// For a real production app, we'd handle page breaks properly
			break;
		}

		page.drawText(section.title.toUpperCase(), {
			x: 50,
			y: currentY,
			size: 12,
			font: boldFont,
			color: rgb(0.3, 0.3, 0.3),
		});
		currentY -= 5;
		page.drawLine({
			start: { x: 50, y: currentY },
			end: { x: width - 50, y: currentY },
			thickness: 1,
			color: rgb(0.9, 0.9, 0.9),
		});
		currentY -= 20;

		for (const item of section.items) {
			page.drawText(item.label, {
				x: 60,
				y: currentY,
				size: 11,
				font: font,
			});
			page.drawText(String(item.value), {
				x: 400,
				y: currentY,
				size: 11,
				font: boldFont,
			});
			currentY -= 18;
		}
		currentY -= 25;
	}

	// Footer
	page.drawText("Generated by Petso - Confidential Store Report", {
		x: 50,
		y: 30,
		size: 8,
		font: font,
		color: rgb(0.7, 0.7, 0.7),
	});

	const pdfBytes = await pdfDoc.save();
	const blob = new Blob([pdfBytes as unknown as BlobPart], {
		type: "application/pdf",
	});
	const url = URL.createObjectURL(blob);

	const link = document.createElement("a");
	link.href = url;
	link.download = `${data.title.replace(/\s+/g, "-").toLowerCase()}.pdf`;
	document.body.appendChild(link);
	link.click();
	document.body.removeChild(link);
}
