name: Publish build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      tags: |
        type=ref,event=branch
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
