name: Docker Build Check

on:
  push:
    paths:
      - "Dockerfile"
      - "Dockerfile.base"
  pull_request:
    paths:
      - "Dockerfile"
      - "Dockerfile.base"

env:
  BASE_IMAGE_NAME: outline-base

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Blacksmith Builder
        uses: useblacksmith/setup-docker-builder@v1

      - name: Build base image
        uses: useblacksmith/build-push-action@v2
        with:
          context: .
          file: Dockerfile.base
          tags: ${{ env.BASE_IMAGE_NAME }}:latest
          push: false

      - name: Build main image
        uses: useblacksmith/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE_NAME }}:latest
